### ISSUE TITLE
Can we use final Roslyn API with roslynpad?

### ISSUE THREAD

**Issue by CyberSinh** [aelij/roslynpad#1]
Hi,

The roslyn scripting API is now RTM (requires .NET 4.6) : 
https://www.nuget.org/packages/Microsoft.CodeAnalysis.CSharp.Scripting/

Roslypad uses a specially compiled version of Roslyn that exposes some internal members used for completion. Can we now use the public roslyn API (through nuget) with roslypad, without hacking ?

Thanks.

**Comment by aelij** [comment]
Unfortunately, no. The scripting APIs do not help with completion. This is on the Roslyn roadmap, though (see this issue for example - https://github.com/dotnet/roslyn/issues/3538).
