### ISSUE TITLE
Is there a way to compile exe and copy all dependent dlls to output folder?

### ISSUE THREAD

**Issue by NathanielACollier** [aelij/RoslynPad#101]
I'd like to be able to compile to exe (Which I realize is there), but copy all of the dlls to the folder where the exe was written.  Is there a way to currently do that?

Is there a way to use one of the RoslynPad libraries to load up a csx file, compile it to exe, and get a list of the dlls?  That would be another way I could get the result I'm looking for.

The reason I'm looking to do this, is that I've written a tool to parse LINQPad scripts, pull out all the references, and produce an exe file with all it's dlls.  That was alot of work though and I don't really want to do the same for RoslynPad, so I'm looking for an easier solution.

**Comment by StingyJack** [comment]
Are you parsing textually or using something like the  CSharpCompilation.Create() to get the metadata references?

**Comment by drxs3v3n** [comment]
For LINQPad I parse manually, for RoslynPad I'd want to know what the right way is.  That's probably most of my problem there may be a way people load up csx files grab #r dependencies and compile it, but that is knowledge I can't seem to find.  I've looked through RoslynPad and can sort of see what it's doing, but I'm just not that good to figure it out.

**Comment by aelij** [comment]
RoslynPad files use the standard C# scripting format. So as @StingyJack suggested, you can use a `CSharpCompilation` to easily parse .csx files for references (including following ones that are in `#load`ed files).

Something like:

```csharp
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.Scripting;

var path = @"c:\path\to\my.csx"
var code = File.ReadAllText(path);
var basePath = Path.GetDirectoryName(path);

var c = CSharpCompilation.Create("C", new[] { 
        SyntaxFactory.ParseSyntaxTree(code, CSharpParseOptions.Default.WithKind(SourceCodeKind.Script)) }, 
    options: new CSharpCompilationOptions(OutputKind.DynamicallyLinkedLibrary, 
        sourceReferenceResolver: new SourceFileResolver(searchPaths: Array.Empty<string>(), baseDirectory: basePath), 
        metadataReferenceResolver: ScriptMetadataResolver.Default.WithBaseDirectory(basePath)));

c.DirectiveReferences
```

**Comment by drxs3v3n** [comment]
What I want to do is take a csx file that contains nuget references and GAC references, compile it to exe and get it to run.  RoslynPad will take me half way it will dump the exe.  The exe won't run though because the dlls aren't copied for the nuget references. 

The code c.DirectiveReferences is only giving me the GAC, and not the nuget references.

**Comment by aelij** [comment]
It does make sense to build this functionality into RP.

`DirectiveReferences` may have not work because in RP I replace `$NuGet` in the reference path with the NuGet cache path. Without this, the resolver can't find the file.
