### ISSUE TITLE
Why aren't certain assemblies available by default (System.Xml)

### ISSUE THREAD

**Issue by RobertOwenJack** [aelij/RoslynPad#103]
I found that in a simple script the intellisense noticed that System.Xml.XmlReader and System.Xml.XmlDocument weren't directly available. I found that I had to use the nuget tool which inserted the #r references directly in the code.  Other assembly references are present by default eg System.Diagnostics and wondered why such common libraries such as those in System.Xml are not.

**Comment by aelij** [comment]
I added the assemblies I thought were most useful for everyone. Loading assemblies has its costs, and `System.Xml` is a large one. If others vote for this issue, I'll add it to the default.

Once #20 is done, you'll be able to configure your own defaults.

**Comment by aelij** [comment]
Closing for now.
