### ISSUE TITLE
Out Of Memory exception

### ISSUE THREAD

**Issue by SlowLogicBoy** [aelij/RoslynPad#105]
When I run script for a long period of time (logging), after RoslynPad reaches 1.5-2 GB ram of usage it crashes. 

The problem is that Console/Dump section fills up and uses a lot of memory, it would be nice if I could clear it while script is running (without restarting it) or set maximum number of latest entries and oldest entries would be removed.

I usually run 2 - 5 scripts at a time and I like to see logs/dumps.

**Comment by aelij** [comment]
I think a maximum would be the best choice here, but I'll have to check how to implement it without hurting perf too much (removing entries from the middle of an `ObservableCollection` is an _O(n)_ operation).

BTW, you should be able to run RP as a 64 bit process by using `corflags.exe /32BITPREF-` ;)

**Comment by aelij** [comment]
Closing as the new process model should not have this issue.
