### ISSUE TITLE
#r for Nuget Package with Version having 0 as last digit

### ISSUE THREAD

**Issue by drxs3v3n** [aelij/RoslynPad#106]
It looks like if a nuget package has a 0 as the last digit in it's version then RoslynPad or something creates a #r without the .0.  An example is nuget package DocumentFormat.OpenXml.

When I pulled it in with RoslynPad it made a #r of:
#r "$NuGet\DocumentFormat.OpenXml\2.5\lib\DocumentFormat.OpenXml.dll"

The package filepath is 
%userprofile%\.nuget\packages\documentformat.openxml\2.5.0
so manually changing the #r to the below made the code work:
#r "$NuGet\DocumentFormat.OpenXml\2.5.0\lib\DocumentFormat.OpenXml.dll"

**Comment by aelij** [comment]
Thanks for reporting this. Must be a problem with the new implementation of the NuGet v4 libraries (they removed a crucial virtual method I was using, so I had to find a workaround).

I'm rewriting most of RP using net-standard libraries, so NuGet will have to change as well anyhow.
