### ISSUE TITLE
Automatically expand single/last enumerable dump

### ISSUE THREAD

**Issue by robhol** [aelij/RoslynPad#107]
I often run snippets that dump some kind of IEnumerable<T> for display purposes. In Roslynpad, this means I have to manually expand the resulting entry in the list every time I execute the script.

I think it'd be a small but noticeable improvement if this weren't necessary. It might be a good idea to make it configurable.

**Comment by aelij** [comment]
Expanding the last level won't be good UX. It's annoying to have the UI change while you interact with it.

I think I'll just auto-expand everything up to the _n_ th levels (3?)

**Comment by aelij** [comment]
I've decided on a default expansion level of **1**. Additionally, you can control the level in the dump method, e.g. `x.Dump(maxExpandedDepth: 5)`
