### ISSUE TITLE
NuGet - show the latest stable version by default

### ISSUE THREAD

**Issue by ohadschn** [aelij/RoslynPad#108]
When searching for NuGet packages, by default the latest version is shown, even if it is pre-release.  I think it would be more prudent to show the latest *stable* version, like nuget.org itself does when you navigate to the "main" package page (where the version isn't specified in the URL, e.g. https://www.nuget.org/packages/Microsoft.Extensions.Caching.Memory/).

**Comment by aelij** [comment]
Don't you like living on the edge? :)

I think I'll add a checkbox like in VS that would allow searching preview releases.
