### ISSUE TITLE
Support extension methods

### ISSUE THREAD

**Issue by imgen** [aelij/RoslynPad#110]
When I try to add extension methods, it give me error saying "Extension methods must be defined in top level class". I guess it is because that there is a implicit class wrapping around the code. Is there anyway to walkaround this

**Comment by aelij** [comment]
I'm afraid not. This is a limitation's in Roslyn's C# script variant, which RP relies on. I may introduce a mode in the future which would allow creating a full program (with a class and a Main method).

Meanwhile, you can write extension methods as top level methods in the script, as I suggested in [this answer](https://stackoverflow.com/a/40496006).

**Comment by imgen** [comment]
@aelij thanks for the info
