### ISSUE TITLE
Write XAML

### ISSUE THREAD

**Issue by RealAquilus** [aelij/RoslynPad#112]
Hi Guys! RoslynPad will have in the future a way to write xaml to make GUI? This will make RoslynPad really awesome and complete IMHO. 

(RoslynPad actually is the only C# editor that run on UWP, make UWP from an UWP app would be simply perfect!)

**Comment by aelij** [comment]
Hey @RealAquilus! Thanks for the suggestion, but this is not a direction I currently see RoslynPad going. My current focus is making RP cross-platform (run on Mac/Linux and .NET Core).

BTW, RP is a desktop WPF app, not UWP. It just uses the Desktop Bridge so it could be distributed via the Microsoft Store.
