### ISSUE TITLE
Unable to build/run - Unable to load DLL 'api-ms-win-core-localization-obsolete-l1-2-0.dll'

### ISSUE THREAD

**Issue by jianyunli** [aelij/RoslynPad#115]
Open the RoslynPad.sln using Visual Studio 2017 Community on Windows 7, when run got the error above and program crashed.

thanks

**Comment by aelij** [comment]
Can you provide a stack trace?

**Comment by jianyunli** [comment]
It's a run time error - crash
![image](https://user-images.githubusercontent.com/6001923/29344407-a3d4b732-8205-11e7-91a3-57f98b29867e.png)

**Comment by aelij** [comment]
This is a bug .NET (dotnet/corefx#13566). I'll stop using this function for now.

**Comment by ohadschn** [comment]
😅

**Comment by slawak** [comment]
I am still experiencing this issue with Win 7 on v 13.1 either on provided builds or if i build myself. The issue occurs on two completely different Win 7 installs.
I can start RoslynPad but as soon as I start a script i get the following error:

![image](https://user-images.githubusercontent.com/5278810/30094338-f7a12e3c-92cb-11e7-89c0-2640191ad190.png)

It seems that the type ServerImpl somehow references this dll but I cant find this reference in the code.

**Comment by aelij** [comment]
@slawak This is a similar issue but in a different place in the code. I've now fixed both, so please wait for the next version (probably today).
