### ISSUE TITLE
Crashes on Launch

### ISSUE THREAD

**Issue by aluitink** [aelij/RoslynPad#12]
Crashes on open:

Problem signature:
  Problem Event Name:	CLR20r3
  Problem Signature 01:	RoslynPad.exe
  Problem Signature 02:	1.0.0.0
  Problem Signature 03:	572a190b
  Problem Signature 04:	PresentationFramework
  Problem Signature 05:	4.6.1055.0
  Problem Signature 06:	563c1d45
  Problem Signature 07:	21df
  Problem Signature 08:	f6
  Problem Signature 09:	System.Windows.Markup.XamlParse
  OS Version:	6.3.9600.2.0.0.256.48
  Locale ID:	1033
  Additional Information 1:	5861
  Additional Information 2:	5861822e1919d7c014bbb064c64908b2
  Additional Information 3:	1318
  Additional Information 4:	13181ae637ac2592fac0ca2dd662cdcc

Read our privacy statement online:
  http://go.microsoft.com/fwlink/?linkid=280262

If the online privacy statement is not available, please read our privacy statement offline:
  C:\Windows\system32\en-US\erofflps.txt

![image](https://cloud.githubusercontent.com/assets/3255752/15032798/e095d6e2-1221-11e6-9600-31a5dfddb644.png)

**Comment by aelij** [comment]
Thanks for reporting this! The zips were missing a few DLLs. Fixed.
