### ISSUE TITLE
Live Mode

### ISSUE THREAD

**Issue by jcansdale** [aelij/RoslynPad#120]
Could you add a live mode checkbox, so that it runs as soon as it's able to compile? 😄

**Comment by aelij** [comment]
Yeah, that shouldn't be too hard :)

**Comment by aelij** [comment]
I've also been considering dumping values inline in the editor (like [OzCode](https://oz-code.com/main#/features#simplify) or Alive). But that may be confusing (what happens if a value is dumped more than once during a run?) WDYT?

**Comment by aelij** [comment]
I mean - in addition to the result pane, not as a replacement of course. Maybe using a different dump method.

**Comment by jcansdale** [comment]
> I've also been considering dumping values inline in the editor (like OzCode or Alive). But that may be confusing (what happens if a value is dumped more than once during a run?) WDYT?

I imagine that could start getting quite involved! I like its simplicity at the moment and the way it boots so much faster than VS. 😉

**Comment by aelij** [comment]
Note that I've set the default delay to 2 seconds. There's no UI to change it, but it's in the configuration file (`Documents\RoslynPad\RoslynPad.json`).

**Comment by jcansdale** [comment]
Great, thanks for the heads up! Could you ping me when it make it into a release?

**Comment by aelij** [comment]
Sure

**Comment by aelij** [comment]
@jcansdale It's out

**Comment by jcansdale** [comment]
Woot, thanks. 👍

**Comment by jcansdale** [comment]
https://twitter.com/jcansdale/status/926220594290614275

![image](https://user-images.githubusercontent.com/11719160/32354221-ad3c6a78-c020-11e7-91e6-311b3786dadb.png)

**Comment by aelij** [comment]
Cool. You can guess where I got the idea for the icon ;)

**Comment by jcansdale** [comment]
It wasn't just a coincidence? I'm honored. 😃 

You'd never guess where I got the icon from. 😉 

![image](https://user-images.githubusercontent.com/11719160/32390646-22f2d148-c0c7-11e7-92d3-0eb2381e3c2f.png)
