### ISSUE TITLE
Brace completion

### ISSUE THREAD

**Issue by aelij** [aelij/RoslynPad#121]

**Comment by Guris** [comment]
Thanks for this great feature.
It might work in more clever way though.

Current behavior:
- Type **(**
  - Result: **()**
- Type **)** (no other character between)
  - Result: **())**

This should work like in Visual Studio - typing closing bracket immediatelly after the opening one should overwrite automatically generated closing bracket. So:
- Type **(**
  - Result: **()**
- Type **)** (no other character between)
  - Result: **()**

Applies to all pair autocompleted characters (braces, brackets, parentheses...)
Thanks for considering this fix.

**Comment by aelij** [comment]
Thanks, I'm aware of this small annoyance, and in fact the pieces are already in place to implement it (search of `AllowOverType` if you're interested).

**Comment by ohadschn** [comment]
@aelij does your fix include quotes too (single+double)?

**Comment by aelij** [comment]
If you’re referring to what @Guris requested, it hasn’t been fixed yet. But yes, a fix would apply to all kinds of braces.

**Comment by ohadschn** [comment]
Cool. Shouldn't this be re-opened then?

**Comment by jogibear9988** [comment]
do you still work on this? I'm not sure how the use of your AllowOverType should be used

**Comment by Guris** [comment]
Hi. Is there any progress?
This issue forces me to use version 13.0.

Thanks

**Comment by aelij** [comment]
It turned out to be more complex than I originally thought. Hopefully will be fixed in the next version.
