### ISSUE TITLE
Search Documents OnKeyPressed

### ISSUE THREAD

**Issue by SlowLogicBoy** [aelij/RoslynPad#124]
Right now documents are updated only when I press Enter key, it would be nice if it updated on every key press so see results immediately

**Comment by aelij** [comment]
I actually prefer it this way. I'll leave this issue open though. If more people vote for it, I'll change the behavior.

**Comment by SlowLogicBoy** [comment]
Maybe, it would be easier to add config to config file which says by default false, or something like that?

**Comment by dsmailys** [comment]
I like the config idea.

**Comment by aelij** [comment]
Would anyone like to submit a PR? Guidance:

* Add a setting in `IApplicationSettings` named `bool SearchWhileTyping`
* In the `MainViewModelBase.SearchText` setter invoke `SearchCommand` if this setting is set to true
