### ISSUE TITLE
Huge memory leak

### ISSUE THREAD

**Issue by SlowLogicBoy** [aelij/RoslynPad#125]
Code:
`_viewModel.PropertyChanged += SomeMethod;`

`SomeMethod` - doesn't exist, pressing Ctrl+. on it many times shows nothing, but memory increases a lot.

RP Version: 13.1 WPF
OS: Windows 10 x64

Script files:
https://gist.github.com/SlowLogicBoy/8260f188c27fdcd5a6104c426722d8a5

Navigate to line 64 in Test.csx, and press Ctrl+. on SomeMethod

**Comment by aelij** [comment]
Thanks, I'm aware. I'll issue a fix soon. Ironically, this is because of a performance optimization I introduced in 13.1.
