### ISSUE TITLE
Ability to add custom assembly to references in RoslynPad.Editor.Windows

### ISSUE THREAD

**Issue by LarsWesselius** [aelij/RoslynPad#129]
Hi,

Is it at all possible to add custom references to RoslynPad.Editor.Windows auto completion editors? I'm getting errors because obviously it cannot recognize my custom classes defined in another assembly.

Thanks

**Comment by aelij** [comment]
Sure. When you create an instance of `RoslynHost`, you can pass a `RoslynHostReferences` object that represents both metadata references (assemblies) or imports (usings). You can use the `Default` and expand on it. For example, the following would import the type `X` (i.e. the entire assembly assembly and namespace):

```csharp
new RoslynHost(references: RoslynHostReferences.Default.With(typeNamespaceImports: new[] { typeof(X) }))
```

(the `With` method accepts references/imports in many forms - choose the one most convenient to you)


Note that `RoslynHost` is built for script language scenarios, but by implementing the `IRoslynHost` interface you can build your own host that creates Roslyn workspaces, projects and documents any way you like.

**Comment by LarsWesselius** [comment]
Thanks a lot, that's exactly what I was looking for and it's working perfectly!
