### ISSUE TITLE
Documents folder forgotten after store update

### ISSUE THREAD

**Issue by ohadschn** [aelij/RoslynPad#132]
I just received the 13.2 update from the store (🎉) and both my auto-saved documents and the manually saved documents in the left pane disappeared. 

So I clicked the "Change Documents Location" button and put the old folder there but nothing happened. Only after I restarted RP did everything come back to normal (including the auto-saved "New" tabs).

**Comment by aelij** [comment]
Hmm, did you by any chance delete the directory `Documents\RoslynPad`? In v13 I moved the settings from .NET app settings to a JSON file stored in that location.

**Comment by ohadschn** [comment]
No I didn't touch it... I just checked and it's still there, with `RoslynPad.json` intact.

**Comment by aelij** [comment]
Was the previous version 12 or 13?

**Comment by ohadschn** [comment]
Pretty sure it was 13.

**Comment by aelij** [comment]
Closing, since I can't find a bug that could cause this. Please reopen if that happens in the next upgrade.
