### ISSUE TITLE
Version for Windows Phone

### ISSUE THREAD

**Issue by gh3x78E** [aelij/RoslynPad#134]
Is it viable to create a version of RoslynPad for mobile devices?

**Comment by aelij** [comment]
You mean Windows Mobile, right? ;) It may be possible to create one based on Avalonia. But currently I'm focused on a Mac/Linux version.

May I ask why would you need such a thing?

**Comment by gh3x78E** [comment]
Coding on the go on my Windows Mobile device would be really awesome! :-)

**Comment by aelij** [comment]
Closing for now, since Avalonia doesn't support UWP, and I don't have the resources to support yet another platform :)
Will reconsider in the future if that changes.
