### ISSUE TITLE
Console output and input

### ISSUE THREAD

**Issue by gh3x78E** [aelij/RoslynPad#138]
Is there a way to see what was written out via `Console.Write(...)`? Is there a window for this? Or is there some other mechanism which can be used as a substitute?

**Comment by ohadschn** [comment]
What do you mean? You can see all the output in the bottom pane:
![image](https://user-images.githubusercontent.com/8555641/30758674-077ce540-9fdc-11e7-8bf0-757e709af467.png)

**Comment by gh3x78E** [comment]
Great. What about `Console.ReadLine(...)`?

**Comment by aelij** [comment]
Closing as dup of #10 #18
