### ISSUE TITLE
[Question] Using RoslynPad.Roslyn in my own code editor

### ISSUE THREAD

**Issue by jamesqo** [aelij/RoslynPad#139]
Hi @aelij,

I am building my own C# code editor at https://github.com/jamesqo/Repository. I would like to add some IDE-like functionality for C# such as brace matching, code completion, Intellisense, etc. in my editor, but I want to reuse existing code if possible instead of implementing that from scratch.

I noticed you have a `RoslynPad.Roslyn` NuGet package and, looking at the names of the folders under that in your repo (`AutomaticCompletion`, `BraceMatching`, etc.), it looks like you've already implemented a lot of the features I was looking for. Is it possible to use this package in my project and adapt it to work with my editor? If it is, could you show me an example/give a pointer or two on how to do so? Thanks.

**Comment by aelij** [comment]
The packages `RoslynPad.Editor.Windows` package contains a WPF control named `RoslynCodeEditor`, which implements everything you need. See the samples folder.

**Comment by aelij** [comment]
Oh, you’re building an Android editor from scratch. :) You should look in `RoslynPad.Editor.Shared` to see how Roslyn services are hooked into AvalonEdit.
