### ISSUE TITLE
Editor improvements

### ISSUE THREAD

**Issue by aelij** [aelij/RoslynPad#14]
- [x] Customize font size
- [ ] Search & replace

**Comment by pKami** [comment]
A great editor imrovement would be the ability to copy output (selected line) from the bottom pane. Currently there is no right click context menu on those elements, and no other way to copy an exception, error, or variable output.

**Comment by aelij** [comment]
@pKami There's a copy button on every line in the tree (it looks like one square over the other). It will copy the entire graph recursively from the node you click. Maybe I should add a tool-tip if that's not clear enough.

**Comment by pKami** [comment]
Yeah, that would be useful. It wasn't very clear for me. Good to hear this functionality is available.
