### ISSUE TITLE
Add Support for .Net Core 2.0

### ISSUE THREAD

**Issue by iDaN5x** [aelij/RoslynPad#141]
Please add support for running RoslynPad with .Net Core 2.0

<img width="1194" alt="screen shot 2017-09-24 at 0 04 42" src="https://user-images.githubusercontent.com/3427523/30777087-fa6adbf6-a0bb-11e7-8d4c-267da57044b6.png">

**Comment by aelij** [comment]
RoslynPad will run only on .NET Core 2.0 once I upgrade to the latest version of Avalonia. You can try running it now by tweaking global.json and RoslynPad.NetCore.csproj, but I haven’t tested it.
