### ISSUE TITLE
Additional hidden source code

### ISSUE THREAD

**Issue by tonithenhausen** [aelij/RoslynPad#143]
I would like to include the RoslynPad editor in my own application. However, I would like to declare custom variables, methods, etc. that can be used in the editor. These declarations should not be visible in the editor. The easiest way would be to specify a hidden source text that is prepended to the script.

Example:

Hidden Source Code:
`var test = "Hello World";`

Source Code visible in the editor (the user can only edit the text below):
`Console.WriteLine(test)`

**Comment by aelij** [comment]
You can do that by using `RoslynHost.AddDocument`, which would contain your "hidden" code, then use `RoslynHost.AddRelatedDocument` to host your actual code and bind it to the editor. This is how the REPL sample works (see [here](https://github.com/aelij/RoslynPad/blob/2deb586f8a14bd400d608d694f47ace9fb236b4f/samples/RoslynPadReplSample/MainWindow.xaml.cs#L71)) - each REPL line is a separate document that's linked to the previous one. To execute this code, you can use the same scripting API in that sample, by creating an initial script object with the hidden code, and using `Script.ContinueWith` for the code from the editor session.

**Comment by tonithenhausen** [comment]
Thanks aelij for the hint to the REPL sample. Unfortunately, both my hidden code and the visible code are shown. 

First I tried to call Initialize on the RosylnCodeEditor twice and use the AddRelatedDocument to link to the hidden code:

```
var hiddenDocumentId = roslynCodeEditor.Initialize(_host, new ClassificationHighlightColors(), Directory.GetCurrentDirectory(), "var portfolio = new Portfolio();");
roslynCodeEditor.CreatingDocument += (o, args) =>
{
    args.DocumentId = _host.AddRelatedDocument(hiddenDocumentId, args.TextContainer, Directory.GetCurrentDirectory(), args.ProcessDiagnostics, a => args.TextContainer.UpdateText(a));
};
roslynCodeEditor.Initialize(_host, new ClassificationHighlightColors(), Directory.GetCurrentDirectory(), GetMember(m => m.AgpCheckCode) ?? "");
```

Additionally I tried to create a hidden document with AddDocument, and bind it to my actual document using AddRelatedDocument:

```
 roslynCodeEditor.CreatingDocument += (o, args) =>
            {
                var hiddenDocumentId = _host.AddDocument(args.TextContainer, Directory.GetCurrentDirectory(), args.ProcessDiagnostics, a => args.TextContainer.UpdateText(a));
                _host.UpdateDocument(_host.GetDocument(hiddenDocumentId).WithText(SourceText.From("var portfolio = new Portfolio();")));

                args.DocumentId = _host.AddRelatedDocument(hiddenDocumentId, args.TextContainer, Directory.GetCurrentDirectory(), args.ProcessDiagnostics, a => args.TextContainer.UpdateText(a));
            };
            roslynCodeEditor.Initialize(_host, new ClassificationHighlightColors(), Directory.GetCurrentDirectory(), GetMember(m => m.AgpCheckCode) ?? "");
```

**Comment by aelij** [comment]
Yep, you don't need an editor control for the hidden document, just the document. Also, you don't really need `AvalonEditTextContainer`, you can do something like:

```
var text = SourceText.From("var test = 1;"))
var hiddenDocumentId = _host.AddDocument(text.Container, Directory.GetCurrentDirectory(), null, null);
args.DocumentId = _host.AddRelatedDocument(hiddenDocumentId, args.TextContainer, Directory.GetCurrentDirectory(), args.ProcessDiagnostics, a => args.TextContainer.UpdateText(a));
```

**Comment by tonithenhausen** [comment]
Thank you, I will try that out!
