### ISSUE TITLE
RoslynCodeEditor fails trying to access AvalonEdit

### ISSUE THREAD

**Issue by ogkennyhobo** [aelij/RoslynPad#144]
I get an error trying to use the code editor like in the example:

Attempt by method 'RoslynPad.Editor.SearchReplacePanel..ctor()' to access method 'ICSharpCode.AvalonEdit.Search.SearchPanel..ctor()' failed.

Any idea what I need to do to fix this?

**Comment by aelij** [comment]
Dup of #128
