### ISSUE TITLE
Unhandled Exception - System.ArgumentOutOfRangeException - Parameter name: startOffset

### ISSUE THREAD

**Issue by brouckaertd** [aelij/RoslynPad#145]
Hi,

I'm having regularly an ArgumentOutOfRangeExcpetion while editing my code in RoslynPad.
![image](https://user-images.githubusercontent.com/2621475/30901637-ed28dad8-a368-11e7-852e-5c2b7bb637d7.png)

**Comment by SlowLogicBoy** [comment]
dup of #130 it has been fixed we'll need to wait for release :)
