### ISSUE TITLE
Update Avalonedit

### ISSUE THREAD

**Issue by jogibear9988** [aelij/RoslynPad#147]
Is it possible to Update Avalonedit to the newest Nuget Package?

**Comment by jogibear9988** [comment]
For me, it does not run with the old Version. And the new one is 2 years newer...

**Comment by aelij** [comment]
Can you be more specific? What kind of error/exception are you seeing?

**Comment by jogibear9988** [comment]
<img width="424" alt="bildschirmfoto 2017-10-07 um 00 24 18" src="https://user-images.githubusercontent.com/364896/31300780-eea5a1fe-aaf5-11e7-8be8-4b9378140ec5.png">

**Comment by aelij** [comment]
See #128

**Comment by jogibear9988** [comment]
is this fix in the nuget?

**Comment by aelij** [comment]
It hasn’t been published yet, but there’s a workaround - you can force NuGet to use AvalonEdit 5.0.2.

**Comment by jogibear9988** [comment]
I can not force to use 5.0.2, because we already use AvalonEdit 5.0.3 in our Solution. Is it possible to publish?
Why don't you use Appveyor to generate a new Release automaticaly after a Update of the Repo?

**Comment by aelij** [comment]
The NuGet packages are relatively new. I may set up CI when I find the time :)

I'll probably release a new version of the packages next week, but it would be helpful if you could test the fix (clone & compile master).

**Comment by jogibear9988** [comment]
I've tested it, works...

**Comment by aelij** [comment]
Great, thanks!

**Comment by jogibear9988** [comment]
What aboutnew Nugets?
