### ISSUE TITLE
Exception when trying to use RoslynPad Component

### ISSUE THREAD

**Issue by jogibear9988** [aelij/RoslynPad#148]
<img width="979" alt="bildschirmfoto 2017-10-08 um 12 44 46" src="https://user-images.githubusercontent.com/364896/31316101-930c6a8a-ac26-11e7-97cb-297a65c15799.png">

**Comment by aelij** [comment]
When creating `RoslynHost`, you need to specify platform assemblies (Windows or Avalonia), like in the sample: https://github.com/aelij/RoslynPad/blob/faa3795a43c6dbbd44e7d107538d2a36218ec390/samples/RoslynPadReplSample/MainWindow.xaml.cs#L43
