### ISSUE TITLE
.cs support (instead of .csx)

### ISSUE THREAD

**Issue by jogibear9988** [aelij/RoslynPad#150]
i tried to support "cs" source files. For a first step i changed only the "(kind: SourceCodeKind.Regular," in your RoslynHost.cs, but I did not get any source completion after this.

**Comment by aelij** [comment]
Have you copied the `RoslynHost` implementation and created a custom one? If so, you need to change a few more things (note I haven't tested this):

In `CreateSubmissionProject`:
* Remove `isSubmission: true`
* Remove `compilationOptions: compilationOptions.WithScriptClassName(name)`

You can also (optionally) remove `sourceReferenceResolver` and `metadataReferenceResolver` in `CreateCompilationOptions`.

In the next version these methods would be virtual in order to simplify custom scenarios.

**Comment by jogibear9988** [comment]
the isSubmission: true was the one I've missed...

After these changes it works

**Comment by jogibear9988** [comment]
I've created a pull req: https://github.com/aelij/RoslynPad/pull/153

**Comment by aelij** [comment]
Hey, can I ask what's your scenario? Usually when you need a whole program (as opposed to a script), there's an entire `Project` with several `Document`s involved. `RoslynHost` is currently designed for scripts, with a single document per project. I'm considering how to enable more scenarios, but essentially it may be just simpler to implement a host that fits your needs.

**Comment by jogibear9988** [comment]
I have a application, where a User can Run Extension Scripts. This Scripts are Classes wich need to implement a specific Interface. So I need to support to compile a class

**Comment by aelij** [comment]
You can create classes in the Script kind. The only limitation is that you can't use namespaces, since the entire script is compiled into a class, and any type you define within it is compiled as a nested type.

**Comment by jogibear9988** [comment]
yes, but that is what i want to!
Sometimes we include the classes later in our Software!

**Comment by jogibear9988** [comment]
@aelij I now tried to copy your RoslynHost to my software and implement my own, but IDocumentationProviderService is not public and RoslynWorkspace is also not...

how can I switch to c# mode then?

**Comment by aelij** [comment]
I'll be releasing a new version soon that would enable your scenario (and many others).

For the time being, you do not have to copy `RoslynHost`, you can create a wrapper:

```csharp
class MyHost : IRoslynHost
{
    private readonly RoslynHost _host = new RoslynHost();

    private readonly ConcurrentDictionary<DocumentId, Workspace> _workspaces =
        new ConcurrentDictionary<DocumentId, Workspace>();

    public DocumentId AddDocument(SourceTextContainer container, string workingDirectory, Action<DiagnosticsUpdatedArgs> onDiagnosticsUpdated, Action<SourceText> onTextUpdated)
    {
        var workspace = _host.CreateWorkspace();
        var projectId = ProjectId.CreateNewId();
        var solution = workspace.CurrentSolution.AddProject(ProjectInfo.Create(projectId, ...));
        var project = solution.GetProject(projectId);
        var document = project.AddDocument(...);
        var documentId = document.Id;

        if (onTextUpdated != null)
        {
            workspace.ApplyingTextChange += (d, s) =>
            {
                if (documentId == d) onTextUpdated(s);
            };
        }

        workspace.SetCurrentSolution(document.Project.Solution);
        workspace.OpenDocument(documentId, container);

        return documentId;
    }

    public void CloseDocument(DocumentId documentId)
    {
        if (_workspaces.TryRemove(documentId, out var workspace))
        {
            workspace.Dispose();
        }
    }

    public Document GetDocument(DocumentId documentId)
    {
        if (_workspaces.TryGetValue(documentId, out var workspace))
        {
            workspace.CurrentSolution.GetDocument(documentId);
        }

        return null;
    }

    public TService GetService<TService>()
    {
        return _host.GetService<TService>();
    }
}
```

**Comment by jogibear9988** [comment]
thx...

have you also seen, a new version of avalonedit is out

**Comment by jogibear9988** [comment]
This is now my working code:


using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.Text;
using RoslynPad.Roslyn.Diagnostics;
using System;
using System.Collections.Concurrent;
using System.Collections.Immutable;
using System.Reflection;
using RoslynPad.Roslyn;

namespace MCC.Configurator.DesignTimeScripting
{
    public class MccRoslynHost : IRoslynHost
    {
        public MccRoslynHost(Assembly[] additionalAssemblies)
        {
            _host = new RoslynHost(additionalAssemblies: additionalAssemblies);
        }

        private readonly RoslynHost _host;

        private readonly ConcurrentDictionary<DocumentId, Workspace> _workspaces =
            new ConcurrentDictionary<DocumentId, Workspace>();

        public DocumentId AddDocument(SourceTextContainer container, string workingDirectory, Action<DiagnosticsUpdatedArgs> onDiagnosticsUpdated, Action<SourceText> onTextUpdated)
        {
            var workspace = _host.CreateWorkspace();
            var projectId = ProjectId.CreateNewId();
       
            var name = "Program";
            var id = ProjectId.CreateNewId(name);
            var prj=ProjectInfo.Create(
                id,
                VersionStamp.Create(),
                name,
                name,
                LanguageNames.CSharp,
                parseOptions: new CSharpParseOptions(kind: SourceCodeKind.Regular,
                    preprocessorSymbols: ImmutableArray.CreateRange(new[] {"__DEMO__", "__DEMO_EXPERIMENTAL__", "TRACE", "DEBUG"}), languageVersion: LanguageVersion.Latest),
                compilationOptions: new CSharpCompilationOptions(OutputKind.DynamicallyLinkedLibrary,
                    usings: ImmutableArray<string>.Empty,
                    allowUnsafe: true));

            var solution = workspace.CurrentSolution.AddProject(prj);
            var project = solution.GetProject(projectId);
            var docId = DocumentId.CreateNewId(project.Id);
            solution = project.Solution.AddDocument(docId, prj.Name, "");
            workspace.SetCurrentSolution(solution);
            workspace.OpenDocument(docId, container);
            var document = solution.GetDocument(docId);
            var documentId = document.Id;

            if (onTextUpdated != null)
            {
                workspace.ApplyingTextChange += (d, s) =>
                {
                    if (documentId == d)
                        onTextUpdated(s);
                };
            }

            workspace.SetCurrentSolution(document.Project.Solution);
            workspace.OpenDocument(documentId, container);

            return documentId;
        }

        public void CloseDocument(DocumentId documentId)
        {
            if (_workspaces.TryRemove(documentId, out var workspace))
            {
                workspace.Dispose();
            }
        }

        public Document GetDocument(DocumentId documentId)
        {
            if (_workspaces.TryGetValue(documentId, out var workspace))
            {
                workspace.CurrentSolution.GetDocument(documentId);
            }

            return null;
        }

        public TService GetService<TService>()
        {
            return _host.GetService<TService>();
        }
    }
}

**Comment by jogibear9988** [comment]
I've one bug: wrong code is not red underlined, don't know why.

**Comment by aelij** [comment]
You should be able to override the `CreateDefaultParseOptions` method now.
