### ISSUE TITLE
Any plans for debugging support in the near future?

### ISSUE THREAD

**Issue by billybobpersonal** [aelij/RoslynPad#155]
Hi there

I recently started using Roslyn Pad as a standalone tool for our implementations developers that 
implement client specific business rules via C# scripting that gets loaded at runtime.
Everything that it currently supports is amazing and works really well. Thanks!

But I was wondering whether you are planning on supporting debugging any time soon? 

Thanks for all the good work!

**Comment by aelij** [comment]
Dup of #42 

To answer your question, not sure when I'll get to it.
