### ISSUE TITLE
Better support for nuget packages

### ISSUE THREAD

**Issue by SlowLogicBoy** [aelij/RoslynPad#157]
Right now if you add nuget package in RP, it just adds path to nuget dll:
`#r "$NuGet\Newtonsoft.Json\9.0.1\lib\net45\Newtonsoft.Json.dll"`
If I transfer that script to another PC, or give to one of my colleagues, and they don't have that nuget, script fails.

I like what cake build does with theirs:
`#tool "nuget:?package=OpenCover&version=4.6.519"`

My suggestion would be something like:
`#nuget "Newtonsoft.Json&version=9.0.1"`
this checks if nuget package exists in cache ($NuGet\Newtonsoft.Json\9.0.1\lib\net45\Newtonsoft.Json.dll) and if it doesn't it downloads that package.
If you don't specify version, you always get latest stable (or not, depends on some kind of option)

Downsides:
`#nuget` would be custom thing for RP...
ScriptCS uses packages.config for this, maybe this would be a better idea, in RP document directory...

**Comment by aelij** [comment]
There's actually a piece of code that restores packages if they're missing when you run. Did it actually not work or did you just assume it wouldn't?

BTW Roslyn has a NuGet #r resolver but it's not implemented yet:
https://github.com/dotnet/roslyn/blob/614299ff83da9959fa07131c6d0ffbc58873b6ae/src/Scripting/Core/Hosting/Resolvers/NuGetPackageResolver.cs

They use the syntax `#r "nuget:name[/version]"`.

**Comment by aelij** [comment]
The thing with my method is that it's dead simple. If I use a package name only (rather than a path), I'd have to calculate the dependency tree on every run (or at least when refs change). But it does have the advantage of being cleaner and platform-agnostic.

Definitely worth rethinking this.

**Comment by SlowLogicBoy** [comment]
Right, it works... but only on current `.csx` file, my example:
Create `Dependencies.csx`
add some nugets in it
remove them from nuget cache directory

Create `MyScript.csx`
#load "Dependencies.csx"
use that nuget
run `MyScript.csx` it will not run (missing references)

workaround:
run `Dependencies.csx`
run `MyScript.csx`

**Comment by aelij** [comment]
They actually had an [implementation](https://github.com/dotnet/roslyn/blob/e52caf41540324405f49970cda75328f9d29b7e4/src/Interactive/Features/Interactive/Core/NuGetPackageResolverImpl.cs) but removed it since then (maybe because it was based on the now defunct project.json).
