### ISSUE TITLE
Time Schedule for new release?

### ISSUE THREAD

**Issue by jogibear9988** [aelij/RoslynPad#158]
Have you any schedule for your new release? Because I now switched to old avalonedit, but I've some problems with other dlls referencing new avalonedit!

And will you also switch to avalonedit 5.0.4?

**Comment by aelij** [comment]
I was planning on getting to it last week but couldn't find the time (as you may have guessed, this is just a side project... ;)

Perhaps I'll just issue a patch for the AvalonEdit problem.

**Comment by jogibear9988** [comment]
Would be nice if you could do so...

**Comment by aelij** [comment]
Released
