### ISSUE TITLE
REPL support

### ISSUE THREAD

**Issue by Ben3094** [aelij/RoslynPad#163]
Line by line execution while keeping the .csx script context alive.
This way RoslynPad would align with ScriptCS regarding features while offering a user friendly interface. 😉

**Comment by aelij** [comment]
Thanks for the suggestion but this is not a direction I see RP going in. There's already REPL for .NET in C# Interactive and Xamarin Workbooks.

**Comment by Ben3094** [comment]
True, but the setup is not as easy as RP... Today, there are no solution with only advantages... RP only needs this feature for me to become the first 😊

**Comment by aelij** [comment]
BTW there's a REPL [sample](https://github.com/aelij/RoslynPad/tree/master/samples).

**Comment by Ben3094** [comment]
It's interesting but doesn't solve the problem...
Now, there is no real playground for C# but your program is so close
Visual Studio Code configuration is awful
CShell doesn't use #r references and ask the user to create a proprietary solution
ScriptCS doesn't have a user friendly interface and so, no auto-completion
RP works great with a great UI but you can't continue to edit a script line by line 😕

**Comment by aelij** [comment]
Can you explain what's good about REPL vs editing and running a document? To me REPL is very limiting.

There's also a new [Live Mode](https://github.com/aelij/RoslynPad/issues/120) in the next version you may find interesting.

**Comment by Ben3094** [comment]
The idea is to combine the 2 methods
The advantage with REPL is that if your not sure about the next line your adding to the script you can construct it line by line (or by block e.g. foreach)

**Comment by Ben3094** [comment]
It allows you to try new commands until it works after a script that builds the context. If the script is slow, you don't want to execute it each time you try something.
