### ISSUE TITLE
Text overlays can stay forever

### ISSUE THREAD

**Issue by Ark-kun** [aelij/RoslynPad#164]
This editor has no text actually:

![image](https://user-images.githubusercontent.com/1829149/32412447-7c75bdf4-c1b5-11e7-90c5-c9e5ab7e7667.png)

I think this happens dud to some exceptions that are not getting handled properly.

**Comment by aelij** [comment]
Thanks for reporting this. Could you please check if it still happens in v13.3? I believe it was fixed there.
