### ISSUE TITLE
Completition for Types in own Assemblies

### ISSUE THREAD

**Issue by jogibear9988** [aelij/RoslynPad#165]
I now use the following Roslyn Host:

    using Microsoft.CodeAnalysis;
    using Microsoft.CodeAnalysis.CSharp;
    using System.Collections.Immutable;
    using RoslynPad.Roslyn;
    using System.Collections.Generic;
    using System.Reflection;

    namespace MCC.Configurator.DesignTimeScripting
    {
        public class MccRoslynHost : RoslynHost
        {
            internal static readonly ImmutableArray<string> PreprocessorSymbols = ImmutableArray.CreateRange(new[] { "TRACE", "DEBUG" });

            public MccRoslynHost(IEnumerable<Assembly> additionalAssemblies)
                : base(additionalAssemblies: additionalAssemblies)
            {
            }

            protected override ParseOptions CreateDefaultParseOptions()
            {
                return new CSharpParseOptions(
                    kind: SourceCodeKind.Regular,
                    preprocessorSymbols: PreprocessorSymbols, languageVersion: LanguageVersion.Latest);
            }

            protected override CompilationOptions CreateCompilationOptions(DocumentCreationArgs args, bool addDefaultImports)
            {
                var compilationOptions = new CSharpCompilationOptions(
                    OutputKind.DynamicallyLinkedLibrary,
                    usings: ImmutableArray<string>.Empty,
                    allowUnsafe: true);
                return compilationOptions;
            }
        }
    }

but the Types in the Assemblies I hand over in the constructor are not found!

**Comment by aelij** [comment]
`additionalAssemblies` refers to MEF composition assemblies, like `RoslynPad.Editor.Windows`. You need to use the other parameter, `references`.

Please search the issues before posting - this has already been asked and answered in #129.

**Comment by jogibear9988** [comment]
I tried:

        public MccRoslynHost(IEnumerable<Assembly> additionalAssemblies)
            : base(additionalAssemblies: additionalAssemblies, references: RoslynHostReferences.Default.With(assemblyReferences: additionalAssemblies))
        {
        }

and 

        public MccRoslynHost(IEnumerable<Assembly> additionalAssemblies)
            : base(additionalAssemblies: additionalAssemblies, references: RoslynHostReferences.Default.With(typeNamespaceImports: additionalAssemblies.SelectMany(x => x.GetTypes())))
        {
        }

and if I remove the "additionalAssemblies: additionalAssemblies," I get the error "No export was found for the contract IDefferedQuickInfoProvider..."

**Comment by aelij** [comment]
Please include the code you use to instantiate `MccRoslynHost`. It doesn't make sense to use the same parameter for both purposes. If you follow the [sample](https://github.com/aelij/RoslynPad/tree/master/samples), it should be something like:

```csharp
new RoslynHost(
            additionalAssemblies: new[]
            {
                Assembly.Load("RoslynPad.Roslyn.Windows"),
                Assembly.Load("RoslynPad.Editor.Windows")
            },
            references: RoslynHostReferences.Default
                .With(assemblyReferences: Assembly.Load("MyAssembly"));
```

**Comment by jogibear9988** [comment]
i know, i did this change yesterday ;-)
i only include your 2 dlls for the additionalAssemblies parameter, this was only a quick hack!

But my namespaces are not found, all usings from my assemblys are red

**Comment by aelij** [comment]
Hmm, I'm not sure what's wrong then. This code definitely works for me.

**Comment by aelij** [comment]
Does it work if you add the assembly using an `#r` directive?

**Comment by jogibear9988** [comment]
#r

sais: "#r is only allowed in scripts"

**Comment by jogibear9988** [comment]
solved,,, i missed to add one Assembly... all my fault ;-(
