### ISSUE TITLE
UWP API access

### ISSUE THREAD

**Issue by Ben3094** [aelij/RoslynPad#169]
It would be delightful to access high level interfaces like Windows.Devices from RoslynPad

**Comment by aelij** [comment]
You can actually already do that if you have the UWP SDK installed. For example:

```csharp
#r "System.Runtime.WindowsRuntime"
#r "C:\Program Files (x86)\Windows Kits\10\UnionMetadata\Windows.winmd"

var locator = new Windows.Devices.Geolocation.Geolocator();
var location = await locator.GetGeopositionAsync();
location.Dump();
```

**Comment by Ben3094** [comment]
Fantastic 😀
But I couldn't find information about that on the web. Is it possible to advertise this feature more ? (At least, this thread will show the solution) Because access to this high level layer is a killer feature 😉
Thank you for your work 👍

**Comment by aelij** [comment]
The following blog post has all the information:

https://blogs.windows.com/buildingapps/2017/01/25/calling-windows-10-apis-desktop-application/

**Comment by Ben3094** [comment]
Thank you 😊
