### ISSUE TITLE
Bug Xml exception using private nuget feed with remote machine

### ISSUE THREAD

**Issue by jrgcubano** [aelij/RoslynPad#170]
- Version: **RosylindPad 13.3**
- Exception:

![image](https://user-images.githubusercontent.com/3245617/33133567-7e0581e0-cf9d-11e7-815d-57b59e0431c4.png)

- NuGet.config (C:\Users\myuser\AppData\Roaming\NuGet\NuGet.config)
```
<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <packageSources>
    <add key="PrivateFeed" value="\\privateServer\nugetServer" />
    <add key="nuget.org" value="https://api.nuget.org/v3/index.json" protocolVersion="3" />
    <add key="CliFallbackFolder" value="C:\Users\j.rodriguez.WINHOTELSOLUTIO\.dotnet\NuGetFallbackFolder" />
  </packageSources>
  <disabledPackageSources>
    <add key="Microsoft and .NET" value="true" />
  </disabledPackageSources>
  <packageRestore>
    <add key="enabled" value="True" />
    <add key="automatic" value="True" />
  </packageRestore>
  <bindingRedirects>
    <add key="skip" value="False" />
  </bindingRedirects>
  <packageManagement>
    <add key="format" value="0" />
    <add key="disabled" value="False" />
  </packageManagement>
</configuration>
```

**Comment by aelij** [comment]
@jrgcubano I've copied the XML you provided and it works fine. 

As you can see from the stack trace, RoslynPad just uses the standard NuGet libraries, which uses `XDocument.Load`, so not much chance of something being wrong there. Are you sure the file didn't have any errors? Note that you have to restart RP after changing it.

**Comment by jrgcubano** [comment]
@aelij Sorry I paste other config! Can you try again using "CliFallbackFolder" value....

**Comment by aelij** [comment]
It's working on my machine. This must be a configuration issue on your machine.

**Comment by jrgcubano** [comment]
@aelij working! thanks!

**Comment by yyjdelete** [comment]
Install RoslynPad from Microsoft Store, and get the same issue.

Delete the `NuGet.Config` from
`C:\Users\<username>\AppData\Local\Packages\34685EliArbel.RoslynPad_zyksrj6kvnp3g\LocalCache\Roaming\NuGet\NuGet.Config` works for me.

Not sure why there is an invalid file with all '\0' here, just leave the message in case someone has the same issue.
