### ISSUE TITLE
Multi-line comments not highlighted unless closed on same line

### ISSUE THREAD

**Issue by trigger-death** [aelij/RoslynPad#171]
Multi-line comments seem to be completely broken. Functionally they work fine but they are not colored when not closed as well as not colored if closed on another line.

Example:
![Example](https://i.imgur.com/cfE5CM5.png)

**Comment by trigger-death** [comment]
I have a proposed fix for this until the semantic highlighter itself manages multi-line anything. I haven't had any problems with this and I've even extended it for extra comment features like AvalonEdit's default C# HACK/TODO/etc highlighting.

**CSharpMultilineHighlighting.xshd**
**Build Action:** Embedded Resource
```XML
<?xml version="1.0"?>
<SyntaxDefinition name="C#" extensions=".cs" xmlns="http://icsharpcode.net/sharpdevelop/syntaxdefinition/2008">
  <Color name="Comment" foreground="Green" exampleText="// comment" />

  <!-- This is the main ruleset. -->
  <RuleSet>
    <Span color="Comment" ruleSet="CommentMarkerSet" multiline="true">
      <Begin>/\*</Begin>
      <End>\*/</End>
    </Span>
  </RuleSet>
</SyntaxDefinition>
```

**Where ever your editor is:**
```C#
// It's preferable to load and store this statically to avoid needing to load it multiple times.
IHighlightingDefinition highlightingDefinition;
var fullName = "FILENAMESPACE.CSharpMultilineHighlighting.xshd";
using (var stream = Assembly.GetExecutingAssembly().GetManifestResourceStream(fullName))
using (var reader = new XmlTextReader(stream))
	highlightingDefinition = HighlightingLoader.Load(reader, HighlightingManager.Instance);

// RoslynCodeEditor editor;
editor.TextArea.TextView.LineTransformers.Add(new HighlightingColorizer(highlightingDefinition));
```

**Comment by aelij** [comment]
Thanks @trigger-death, but I'd much rather fix this is in the semantic highlighter. It's not complicated :)

**Comment by trigger-death** [comment]
Yeah I'm sure that's the case. Was just leaving this here for people to manually fix it in the meantime.
