### ISSUE TITLE
[Compiler] Null-Propagation out vars in Code-Root

### ISSUE THREAD

**Issue by Kirides** [aelij/RoslynPad#172]
Related: [Reddit -> C#7 + Null-Propagation problem](https://www.reddit.com/r/csharp/comments/7i6d9i/c7_nullpropagation_problem/)
----
While having a discussion with a fellow programmer over at [reddit.com/r/csharp](https://www.reddit.com/r/csharp/) i found out that RoslynPad handles a certain use-case that i wish for in regular C#, which is Nullable<bool> out var  
`if (dict?.TryGetValue("", out var value) == true) ... `

How exactly does RoslynPad handle compilation to support the following syntax
(which is invalid in LinqPad and Visual Studio 2017, C#7)
```cs
var dict = new Dictionary<string, IEnumerable<string>>
{ ["token"] = new List<string> { "abc" } };

if (dict?.TryGetValue("token", out var values) == true)
{
    // Error in LinqPad/VS: use of unassigned local variable "values"
    Console.WriteLine(values.First());
}
```
Funny enough, this code does _not_ work
```cs
{
    var dict = new Dictionary<string, IEnumerable<string>>
    { ["token"] = new List<string> { "abc" } };

    if (dict?.TryGetValue("token", out var values) == true)
    {
        // Error also in RoslynPad: use of unassigned local variable "values"
        Console.WriteLine(values.First());
    }
}
```

**Comment by Kirides** [comment]
Turns out, the `out var values` becomes a field after compilation

```
IL_003a: ldstr "token"
IL_003f: ldloc.0
IL_0040: ldflda class [mscorlib]System.Collections.Generic.IEnumerable`1<string> Program::values
IL_0045: call instance bool class [mscorlib]System.Collections.Generic.Dictionary`2<string, class [mscorlib]System.Collections.Generic.IEnumerable`1<string>>::TryGetValue(!0, !1&)
IL_004a: pop
IL_004b: ldnull
IL_004c: stloc.1
IL_004d: leave.s IL_0066
...
.field public class [mscorlib]System.Collections.Generic.IEnumerable`1<string> values
```

This does not seem right, does it? This makes code in Roslynpad behave differently that expected

**Comment by aelij** [comment]
RoslynPad uses Roslyn's C# script language kind. The reason it works in the first example, is that variables defined in the script's main body are lifted into fields in the generated script class.

**Comment by aelij** [comment]
This is not specific to RP. If you try it in the C# Interactive window in VS it would work the same way.

**Comment by Kirides** [comment]
Just reproduced it inside the C# Interactive window, like you (@aelij) said.
Is this the expected behaviour? Should RoslynPad not rather mimic a regular C# environment (eg. VS), other than Interactive?

**Comment by aelij** [comment]
The reason for it is so you could reference variables in continuing scripts. If they'd only been stack elements, it would not be possible. For example:

```csharp
var state = await CSharpScript.RunAsync("int x = 1;");
state = await state.ContinueWithAsync("int y = 2;");
state = await state.ContinueWithAsync("x+y");
Console.WriteLine(state.ReturnValue);
```

> Is this the expected behaviour? 

Yes - it's entirely determined by Roslyn. I may introduce a "regular" code mode which would require a main method and also allow things like namespaces, which are not allowed in the script kind.
