### ISSUE TITLE
roslynpad.net website video

### ISSUE THREAD

**Issue by YanYas** [aelij/RoslynPad#173]
The video seems to only contain one frame

**Comment by ohadschn** [comment]
The video is working fine for me... have you tried a different browser?

**Comment by aelij** [comment]
Fine here as well. Perhaps it was a corrupted download? Maybe force a refresh.

**Comment by aelij** [comment]
Closing as it appears to be a local issue

**Comment by YanYas** [comment]
Yep, seems to have cleared . Strange one. Tried two separate browsers and my IPod and had the same problem at the time. Thanks
