### ISSUE TITLE
System.Drawing.Printing?

### ISSUE THREAD

**Issue by rgomez90** [aelij/RoslynPad#176]
I recenty started to use RoslynPad and when trying to get a list of installed printers RoslynPad says it can't find **System.Drawing.Printing** but my programm runs right and I get the installed printer list.

![image](https://user-images.githubusercontent.com/12009909/34476135-97955836-ef8e-11e7-80a5-69ae32d74145.png)

I am doing sth wrong or forgot to configure sth or is this a small bug? I tried to find some info but couldn't find anything so decided to ask here.

**Comment by ohadschn** [comment]
You're missing `#r "System.Drawing"` at the top of your file.

**Comment by rgomez90** [comment]
Thank you @ohadschn. Was sure I was forgetting something
