### ISSUE TITLE
Host RoslyinPad in Winforms

### ISSUE THREAD

**Issue by tosatoandrea** [aelij/RoslynPad#177]
Hi, I'm trying to host RP with ElementHost control in Winforms. RoslynHost object creation with assembly load:
Assembly.Load("RoslynPad.Roslyn.Windows"),
Assembly.Load("RoslynPad.Editor.Windows")
throw TypeLoaderException.

The exception said:

Impossible to load type 'Roslyn.Utilities.PooledObject`1' from assembly 'Microsoft.CodeAnalysis.Workspaces, Version=2.6.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'.

I update all nuget packages to latest version.

Any suggetions please? Thank you

**Comment by anglodutch** [comment]
This is because you're using Roslyn 2.6 and the latest version of RoslynPad doesn't work with 2.6. I have a pull request #179 that fixes this.

**Comment by aelij** [comment]
Note that if you don't necessarily need Roslyn 2.6, you can have NuGet reference v2.4 and it should work fine.

**Comment by tosatoandrea** [comment]
It works fine! Thank you.

**Comment by FabioGoncalves** [comment]
Hi, Did you fixed?
I have the NuGet RoselynPad 2.4 version.
I'm getting the same error, but with a more recent version of Microsoft.CodeAnalysis.Workspaces...
Impossible to load type 'Roslyn.Utilities.PooledObject`1' from assembly 'Microsoft.CodeAnalysis.Workspaces, Version=2.10.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'.
