### ISSUE TITLE
Update to support Roslyn 2.6.1

### ISSUE THREAD

**Issue by anglodutch** [aelij/RoslynPad#178]
We are using the RoslynPad Nuget packages to create a business rule editor which is a plugin to visual studio. Yes it may seem odd to have another code editor inside VS but using RoslynPad and c# script has make it easy to pass a global object that allows the scripts to interact with each other and the rest of the system.

The latest version of Visual studio (2017.5) ships with Roslyn 2.6 breaks the plugin because some of the Roslyn internals that are accessed by RoslynPad have been moved (PooledObject) or removed (FixAllState.Create and FixAllDiagnosticProvider).

**Comment by aelij** [comment]
That's the price I pay for using internal APIs :) But without them RP won't be nearly as good.
