### ISSUE TITLE
Redirect Console In

### ISSUE THREAD

**Issue by aelij** [aelij/RoslynPad#18]

**Comment by IcecreamBurglar** [comment]
Hi! Is this still something you'd accept as a PR?
If so, how would you like for it to be added in?
I've recently run into an instance where this would be handy, and I'd love for it to be implemented.

**Comment by aelij** [comment]
Hey @JMikeW. Sure, I'd love a contribution.

Start with `ExeutionHost`, which is the host process for RP. You can see there's redirection for the out/err streams there, add one for the in stream. Then, add a method `ReceiveConsoleInput` to `IServiceCallback` notifying the client to show the UI for entering input, and a method `SendConsoleInput` to `IService` that sends the text from the UI to the server. Expose the callback method as an event `ReceiveConsoleInput` (like the `Dumped` event).

On the UI side, you'll need to register to `ReceiveConsoleInput` in the `OpenDocumentViewModel.SetDocument` method, and use binding to display the textbox. When the user enters text and hits enter, use the `SendConsoleInput` method to send it to the server.

I hope that's clear enough.

**Comment by JMikeW** [comment]
Sounds good, I'll start tinkering with it next weekend!
It looks clear enough; however, if something snags me up I'll be sure to check back with you.

**Comment by aelij** [comment]
I've completely changed the hosting model. It should be even simpler now, hook into the input stream of the process in `AssemblyExecutionHost` and fire an event.
