### ISSUE TITLE
Prefix and Suffix Text for Editor

### ISSUE THREAD

**Issue by jogibear9988** [aelij/RoslynPad#180]
I have a Application, where I've splited the Code the User can Edit in 3 Parts.

Means, I've a header and a footer wich the user cannot edit. But I need to handover the full text to Roslyn, so CodeCompletition and Suggestions would work.

Would it be possible to extend your component in a way that this scenario would work?

**Comment by jogibear9988** [comment]
/Users/jkuehner/Desktop/Bildschirmfoto 2018-01-17 um 22.50.48.png

**Comment by jogibear9988** [comment]
<img width="1066" alt="bildschirmfoto 2018-01-17 um 22 50 48" src="https://user-images.githubusercontent.com/364896/35069048-461a48fc-fbd9-11e7-9632-50d57bc37888.png">

**Comment by jogibear9988** [comment]
I think I also could work on this... But at first I wanted to here your thoughts...

**Comment by aelij** [comment]
I think the simplest solution would be to extend AvalonEdit and make those lines read-only. See this answer:

https://stackoverflow.com/a/14426095

**Comment by jogibear9988** [comment]
Thanks for your Tip. I've got it working using this Code:

            var p = new TextSegmentReadOnlySectionProvider<TextSegment>(designTimeScriptEditor.roslynCodeEditor.TextArea.Document);
            p.Segments.Add(new TextSegment() { StartOffset = 0, Length = header.Length });
            p.Segments.Add(new TextSegment() { StartOffset = text.Length - footer.Length - 1, Length = footer.Length });
            designTimeScriptEditor.roslynCodeEditor.TextArea.ReadOnlySectionProvider = p;

But I now have one problem! If I Enter a char in the Header (in the readonly section) after a opening bracket, a closing bracket is added to the document. I think this is in your code wich adds closing brackets automaticaly.

**Comment by aelij** [comment]
How do you add a char if it's read only? :)
Perhaps you could intercept the `TextArea.TextEntering` event and cancel it if it's in the RO section.

**Comment by jogibear9988** [comment]
I could not Enter a Character, but after Pressing a key after a bracket in readonly section (and no character is inserted), a closing bracket will be inserted!

**Comment by aelij** [comment]
Closing, as this is not an RP issue directly. Have you tried my suggestion above, using `TextArea.TextEntering` to cancel the entered text?

**Comment by jogibear9988** [comment]
No, not yet.

But why does RoslyPad insert a closing braket, when the opening braket was already present. I thought it would only add one, if I enter a new opening one!
