### ISSUE TITLE
References not loading when not used in code

### ISSUE THREAD

**Issue by Roemer** [aelij/RoslynPad#184]
Hello

I have a reproducible example (code at the end of the post) where referenced assemblies are not copied correctly and therefore crash the running application.
The situation is as follows:
- Two nuget packages are referenced (OxyPlot.Core and OxyPlot.Wpf
- There is no direct using of anything in OxyPlot.Wpf
- There is a XAML string which is parsed on runtime which needs OxyPlot.Wpf

If I run that application, it will crash saying XAML cannot create the unknown type found in OxyPlot.Wpf.
If I now add a line which uses this assembly (like `var tmp = OxyPlot.Wpf.MoreColors.Automatic;`), it runs correctly.
If I now remove this line again and kill the host process, it stops working again until I add this line again.
I suspect that somehow the reference is removed when no code is found that uses it.
Is there some way (beside just using something from the assembly) to force using a reference?

Thanks
Roman

Here's the code:
```csharp
#r "$NuGet\OxyPlot.Core\1.0.0\lib\net45\OxyPlot.dll"
#r "$NuGet\OxyPlot.Wpf\1.0.0\lib\net45\OxyPlot.Wpf.dll"
#r "System.Xaml"
#r "System.Xml"
#r "System.Xml.Linq"

using System.Windows;
using System.Windows.Markup;
using System.Xml;
using System.Xml.Linq;
using OxyPlot;
using OxyPlot.Series;
using OxyPlot.Wpf;

string XAMLMain = @"
<Window  
        xmlns=""http://schemas.microsoft.com/winfx/2006/xaml/presentation""
        xmlns:x=""http://schemas.microsoft.com/winfx/2006/xaml""
        xmlns:oxy=""http://oxyplot.org/wpf""
        Title=""OxyPlot"" Height=""600"" Width=""1000"">
        <Grid>
            <ScrollViewer>
                <oxy:PlotView Model=""{Binding}"" Height=""300"" />
            </ScrollViewer>
        </Grid>
</Window>
";

var plotModel = new PlotModel { Title = "Test" };
plotModel.Series.Add(new FunctionSeries(Math.Sin, -10, 10, 0.1, "sin(x)"));
// Uncomment this line and it will work
//var tmp = OxyPlot.Wpf.MoreColors.Automatic;

Window win = (Window)XamlReader.Parse(XAMLMain);
win.DataContext = plotModel;
try
{
    win.ShowDialog();
}
catch (Exception ex)
{
    Console.WriteLine(ex);
}
```

**Comment by aelij** [comment]
I'm closing this as a no-fix. The same issue manifests in the C# Interactive window in VS, since both use Roslyn's `InteractiveAssemblyLoader`. If you want, you can open an issue in the Roslyn repo.
