### ISSUE TITLE
Option to disable brace completion

### ISSUE THREAD

**Issue by vitjok** [aelij/RoslynPad#185]
Brace completion was added with #121.

Is there an option to disable brace completion?

I dont use brace completion in any text editor, so this feature is very unaccustomed for me. I am all the time deleting the automatically added characters.

I was searching for an appropriate option in TextEditorOptions, but didnt find.
I can set CompletionProvider to null, but then AutoCompletion is disabled at all. I want disable only the brace completion.

**Comment by aelij** [comment]
Currently, no. I'll try to add a property to disable it in the next release.

**Comment by Daloupe** [comment]
Roslyn pad is awesome, but those auto braces drive me insane.

**Comment by trigger-death** [comment]
In the meantime, here's a fix for people to use with Reflection:

**NoBraceCompletionProvider.cs**
```C#
using Microsoft.CodeAnalysis;
using RoslynPad.Roslyn.AutomaticCompletion;

namespace RoslynPad.Editor {
	/// <summary>Disables brace completion..</summary>
	public class NoBraceCompletionProvider : IBraceCompletionProvider {
		/// <summary>Never completes a brace.</summary>
		public bool TryComplete(Document document, int position) {
			return false;
		}
	}
}
```

**File where your editor is:**
```C#
// RoslynCodeEditor editor;
var fieldInfo = typeof(RoslynCodeEditor).GetField(
		"_braceCompletionProvider",
		BindingFlags.NonPublic | BindingFlags.Instance);
fieldInfo.SetValue(editor, new NoBraceCompletionProvider());
```

**Comment by EmileSonneveld** [comment]
Or like how SublimeText does it: When a user types a closing brace, while the cursor is before an automatically added closing brace, it will just 'overwrite' it.

For me this seems best of both worlds, as when people type the closing brace instinctively there will not be duplicated closing braces.

**Comment by Merovech** [comment]
So, I've started looking into this, and have so far managed to implement a solution locally:

* I added a button next to the Optimize Code option at the bottom of the main window.
  * Keyboard shortcut: CTRL+SHIFT+B
* The setting it is bound to is correctly saved in the settings file, and defaults to `true` (use automatic bracket completion) the first time the user opens the application after the PR goes through.  This preserves the current behavior while allowing the user to turn it off.
* The setting is respected in a live manner; that is, turning it on or off takes effect immediately in open files.

I'm not sure if this is the *best* solution, per se -- I'd imagine smarter bracket completion behavior would be preferable to just an option to shut the whole thing off -- but it'll do the trick.

Two option issues on my end:
* I've only implemented this on the standard WPF version, I think.  I'm not even sure how to test it on other platforms, so I haven't modified them.  The modified projects are:
  * `RoslynPad`
  * `RoslynPad.Common.UI`
  * `RoslynPad.Editor.Shared`
* I would *love* to get an image better than the one I used (I used `FormatDocument`), but I haven't a clue how to turn one into the `DrawingGroup` I'd need.

**Comment by aelij** [comment]
@Merovech Thanks for your effort, but I'm in the process of fixing brace completion so hopefully it won't bother anyone.

I'm therefore closing this issue. :)

**Comment by Merovech** [comment]
@aelij Sounds good!  I started working on it because I was getting frustrated with the feature, so I'm glad to hear it's getting fixed. :)

**Comment by jogibear9988** [comment]
@aelij for me brace completition does not work like it should. would it be possible to add this option?

**Comment by aelij** [comment]
@jogibear9988 It was added in v14

**Comment by jogibear9988** [comment]
couldn‘t find it. can you tell me how to do?

**Comment by aelij** [comment]
There's a braces icon `{>}` on the bottom toolbar.
