### ISSUE TITLE
How to update assembly references while running?

### ISSUE THREAD

**Issue by tebjan** [aelij/RoslynPad#186]
hello,

in our system we dynamically add and remove assemeblies and want to tell RoslynPad which ones are available without losing the undo stack. We tried to call Initialize(...) but that doesn't seem to work.
is this possible somehow?

thanks!

**Comment by aelij** [comment]
This scenario is currently not directly supported, but you can try using `RoslynHost.UpdateDocument`.

For example (not tested, just off the top of my head):

```csharp
var d = RoslynHost.GetDocument(id);
var p = d.Project.WithMetadataReferences(d.Project.MetadataReferences
    .Concat(new MetadataReference[] { }));
d = p.GetDocument(id);
RoslynPad.UpdateDocument(d);
```

**Comment by aelij** [comment]
Note that you can also write your own `IRoslynHost` and build/update the projects whichever way you like.

**Comment by tebjan** [comment]
thanks for the quick reply, i'll try your suggestions.

**Comment by aelij** [comment]
Closing. Please let me know if you need more info.

**Comment by tebjan** [comment]
hello @aelij i just saw the recent updates, would the new host make dynamic assemble add/remove more easy? if yes, would you mind to post some pseudo code on how to achieve that? i am back on this project and try to implement that now.

**Comment by aelij** [comment]
@tebjan these updates should not effect your scenario, if I understand correctly.
