### ISSUE TITLE
Delete the brace automatically created if the one that prompted it is deleted

### ISSUE THREAD

**Issue by StingyJack** [aelij/RoslynPad#187]
I end up with too many }}]]])))))) because the automatic closing brace. 

Also, undo will get rid of the c;losing brace, but should probably get rid of the set,

I have decades of muscle memory hitting () {} [] that just turns into ()) {}} []], I really just want to disable this feature but someone else put that request in already.

**Comment by aelij** [comment]
Already discussed in #121
