### ISSUE TITLE
Namespaces, no Intellisence etc.

### ISSUE THREAD

**Issue by rs38** [aelij/RoslynPad#188]
this code compiles and runs, but the red "squigglies" remain under XmlReader etc. and there is no intellisense for my reader variable...
What did I miss?

```
using System.Xml;

using (XmlReader reader = XmlReader.Create(@"D:\sheet1.xml.txt"))
{
    reader.ReadStartElement("table");
}

```

**Comment by aelij** [comment]
You need to reference the assembly. Add `#r "System.Xml"` at the top of the document.

**Comment by rs38** [comment]
oh well.... fast and easy fix.

when do I need this reference. in Azure functions .csx I do not need it for most namespaces inside the .NET Framework??!

some examples would be nice.

**Comment by aelij** [comment]
See my answer here: https://github.com/aelij/RoslynPad/issues/103#issuecomment-313843994
This is the list of default imports (each type references its assembly and entire namespace):

https://github.com/aelij/RoslynPad/blob/83cc426ffbd320ac7ce8e1df5a91af425e0d62e8/src/RoslynPad.Roslyn/RoslynHostReferences.cs#L26-L39

**Comment by rs38** [comment]
I searched the issue for exactly this but did not find that. Thank you anyway, great app!

**Comment by ohadschn** [comment]
Isn't it kind of inconsistent that the code compiles and runs though, whereas the editor shows red squigglies and does not provide intellisense? I would expect parity between the two...
