### ISSUE TITLE
[Question] Hidden Code to Encompass script in a class

### ISSUE THREAD

**Issue by trigger-death** [aelij/RoslynPad#191]
I'm attempting to incorporate RoslynPad into a script editor for a game. I only want code relevant to a single individual script to be visible in the `RoslynCodeEditor` but I want outside code to exist around the editor text so that certain members and other information are available through the intellisense.

I've tried defining a custom `SourceTextContainer` that inserts the required code around the editor script text yet this messes up the syntax highlighting, tooltips, and the likes.

Scripts are generated as functions within a single class with a few members for access to the game objects. Note that the ability to use the compiled code is not necissary. I just need to the syntax highlighting, code completion, and other helpful features.

Another alternative to this would be assigning variables for each of the classes required members and method parameters before the script starts. But I'm unsure of how to do that as well.

Here is an example of what a script would be output to as code.

```C#
//usings go here

namespace GameAPI.CustomScripts {
	public class CustomScript : CustomScriptBase {
		//Members for game access are defined in CustomScriptBase
		
		public void script_name(/*Any script parameters go here*/) {
			// Only code inside this function is visible in the editor
		}
		
		// Rest of the scripts are defined in the same manner...
	}
}
```

I've looked at #150 but it doesn't really clear up how to get script classes working.

**Comment by aelij** [comment]
I think your best bet would be to manipulate the editor not to show or lock the encompassing lines. You should take a look at my answer here:
https://stackoverflow.com/a/48754083

**Comment by trigger-death** [comment]
This looks very promising. Thank you!

**Comment by trigger-death** [comment]
I decided to go with the variable approach as it was much cleaner to implement and easier to read in the long run.

Here's my code and the result:
```C#
// Generate the code and get the true start of the script
string code = ScriptManager.CreateRoslynScriptCode(script, out scriptStart);

// Standard editor initialization
documentID = editor.Initialize(host, new ClassificationHighlightColors(),
	workDir, code);

// Make the members/parameters readonly
var p = new TextSegmentReadOnlySectionProvider<TextSegment>(editor.TextArea.Document);
p.Segments.Add(new TextSegment() { StartOffset = 0, Length = scriptStart });

// Fold the members/parameters by default so the user doesn't have to see them
var foldingManager = FoldingManager.Install(editor.TextArea);
var foldings = new NewFolding[1] {
	new NewFolding(0, scriptStart - Environment.NewLine.Length) { // end before the newline
		Name = "Members/Parameters",
		DefaultClosed = true
	}
};
foldingManager.UpdateFoldings(foldings, scriptStart);
```

Preview:
![Preview](https://i.imgur.com/Sk5drLh.png)
