### ISSUE TITLE
TaskCanceledException caused when setting Text during Loaded event

### ISSUE THREAD

**Issue by trigger-death** [aelij/RoslynPad#194]
**How to reproduce:**
* This seems to be something like a race condition. It is not guaranteed to occur, but changing certain things in my own project increases or decreases its chances. (Like overriding the `BraceMatchingProvider` or adding an extra `LineTransformer`)
* Set `RoslynCodeEditor.Text` after `RoslynCodeEditor.Initialize()` during the `Loaded` event.
* At the moment I don't have sample code to reliably reproduce this but I have encountered it with the following code from the sample project provided with RoslynPad's source: (I've only hit it with this method once so far)

**MainWindow.xaml.cs**
```C#
private void OnItemLoaded(object sender, EventArgs e) {
    // ...

    var documentId = editor.Initialize(_host, new ClassificationHighlightColors(),
        workingDirectory, string.Empty);

    editor.Text = "using System;\nnamespace Foo{class Hello {}}";

    // ...
}
```

**[Full Exception Callstack](https://pastebin.com/51dCmu9P)**

I'm able to reproduce this more reliably in my own project due to all of the features piled onto RoslynPad but it's not really feasible to make a sample out of that. Unlike the sample project, I hit it almost every time in my project. I should mention my project is also in VS2015 which may or may not have something to do with it.

**Comment by aelij** [comment]
A `TaskCanceledException` usually does not incidate a problem. Are you seeing this in a debugger? Just configure it not to stop on those.

**Comment by trigger-death** [comment]
Ah thank you. That'll make life a bit easier. I've been catching them in my root catch-all exception handlers but I'll just tell it to ignore execptions of this type. Strangely enough, I'm not even encountering it in the first place today.
