### ISSUE TITLE
Broken UI on Ubuntu 18.04

### ISSUE THREAD

**Issue by Ma3yTa** [aelij/RoslynPad#195]
builded from source code using .NET Command Line Tools (2.1.103)

![](https://i.gyazo.com/675221ab6c2c8fc2a861be593785fb3e.png)

**Comment by aelij** [comment]
Hey, could you explain what do you mean by 'broken'? What's not working?
Note that not everything is hooked up properly. And the editor still needs a lot of work.
That's why I called it an 'alpha' version :)
