### ISSUE TITLE
variable

### ISSUE THREAD

**Issue by CSharpDummy** [aelij/RoslynPad#198]
Hi,

Is there a way to pass a variable to RoslynHost?

**Comment by aelij** [comment]
See this answer, might fit your needs:

https://stackoverflow.com/questions/47293326/is-it-possible-to-include-intellisense-for-the-object-global-of-globalstype-in-t

**Comment by CSharpDummy** [comment]
Yes I saw that, but I don't think it works. In the example an object of type MyContext was created:
MyContext context = new MyContext();
context.Data = data;

But in your code you are just passing the type:
hostObjectType: typeof(MyContext)

The object is not passed anywhere. I ran the example and the editor is aware of the type but not the object.

**Comment by Panuon** [comment]
Hi,

what about dynamic variables ?
