### ISSUE TITLE
Exception: System.Composition.Hosting.CompositionFailedException: 'No export was found for the contract 

### ISSUE THREAD

**Issue by Antonytm** [aelij/RoslynPad#199]
I am trying to run this code:
```
var rh = new RoslynHost();
var wrkSpace = rh.CreateWorkspace();
```
I get exception:
_System.Composition.Hosting.CompositionFailedException: 'No export was found for the contract 'ExportFactory<IPickMembersDialog>'
 -> required by import 'dialogFactory' of part 'PickMembersService'
 -> required by import 'value' of part 'Lazy<IWorkspaceService, WorkspaceServiceMetadata>'
 -> required by import 'item' of part 'Lazy`2[]'
 -> required by initial request for contract 'IEnumerable<Lazy<IWorkspaceService, WorkspaceServiceMetadata>> { IsImportMany = True }''_

**Comment by aelij** [comment]
You need to add platform assemblies (e.g. `RoslynPad.Roslyn.Windows`) to the composition to create `RoslynHost`. See the sample:

https://github.com/aelij/RoslynPad/blob/7f63cb27ae47fddd56666694785526539c6c8aef/samples/RoslynPadReplSample/MainWindow.xaml.cs#L43-L47

**Comment by Antonytm** [comment]
Thank you @aelij, it works!
