### ISSUE TITLE
AvaloniaEdit version doesn't match

### ISSUE THREAD

**Issue by johannesegger** [aelij/RoslynPad#200]
`RoslynPad.Editor.Avalonia 1.0.4` has a dependency on `Avalonia.AvaloniaEdit >= 0.2.2-alpha`. However when using these two versions I get the following exception when instantiating a `RoslynCodeEditor`:

```
System.TypeLoadException : Method 'get_CanHorizontallyScroll' in type 'AvaloniaEdit.Editing.TextArea' from assembly 'AvaloniaEdit, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.
   at RoslynPad.Editor.RoslynCodeEditor..ctor()
```

Which suggests that `RoslynPad.Editor.Avalonia` was compiled against a different version of `Avalonia.AvaloniaEdit`. I then manually updated `Avalonia.AvaloniaEdit` to version 0.6.0, but then got the following exception when calling `RoslynCodeEditor.Initialize` (so a bit later in the execution than with v0.2.2-alpha):

```
Exception thrown: 'System.MissingMethodException' in RoslynPad.Editor.Avalonia.dll: 'Method not found: 'Avalonia.Media.Brush AvaloniaEdit.Highlighting.HighlightingBrush.GetBrush(AvaloniaEdit.Rendering.ITextRunConstructionContext)'.'
   at RoslynPad.Editor.BraceMatcherHighlightRenderer..ctor(TextView textView, IClassificationHighlightColors classificationHighlightColors)
   at RoslynPad.Editor.RoslynCodeEditor.Initialize(IRoslynHost roslynHost, IClassificationHighlightColors highlightColors, String workingDirectory, String documentText)
```

Which again suggests that `RoslynPad.Editor.Avalonia` was compiled against a different version.
What did you compile this against? Do you have a custom build or something like that?

**Comment by aelij** [comment]
Sorry for not replying earlier. I need to update the NuGet packages - the latest code uses Avalonia 0.6.

**Comment by aelij** [comment]
Should be fixed with the latest packages
