### ISSUE TITLE
question: complice code in Roslynpad shows error

### ISSUE THREAD

**Issue by ChrisFeng** [aelij/RoslynPad#203]
I try to compile the code in RoslynPad, but it is always error;
Does someone have experience to compile code in RoslynPad and could give me some example?
for (int i = 0; i < 10; i++) { MessageBox.Show("a"); }

![image](https://user-images.githubusercontent.com/20559354/41812520-f5dd8332-7756-11e8-8eb3-d388d5ba23d6.png)

**Comment by aelij** [comment]
Hi @ChrisFeng, RoslynPad doesn't add UI assemblies to its context by default. So you'd need to reference an assembly first, e.g. `#r "PresentationFramework"`
