### ISSUE TITLE
Better Documentation 

### ISSUE THREAD

**Issue by okreka** [aelij/RoslynPad#204]
There should be more explained examples on how to use ex: windows form or a project with multiple .cs file.

**Comment by SlowLogicBoy** [comment]
WinForms:
```csharp
#r "System.Windows.Forms"

using System.Windows.Forms;

Application.Run(new Form {
    Text = "Hello World"
});
```
Multiple files:
![image](https://user-images.githubusercontent.com/3121637/42807751-47fd3408-89ba-11e8-806e-d33ed65c10c5.png)

it won't work with .cs files only .csx since this is a C# scripting app not C# ide.

**Comment by okreka** [comment]
Thank you very much for the quick replay

**Comment by aelij** [comment]
Docs are nice to have, but I'm afraid I'll never get to it :)
Also, even were I to write docs I wouldn't include usage of specific frameworks in them. As you can see, if you add the right references you can pretty much invoke any library.

Regarding multiple .cs(x) files, the solution @SlowLogicBoy proposed is fine. I don't intend on supporting full projects, as RoslynPad is intended to be a scratchpad. You can use full VS for those kind of things.
