### ISSUE TITLE
VB.NET

### ISSUE THREAD

**Issue by CSharpDummy** [aelij/RoslynPad#205]
Does RoslynPad also support VB.NET? What changes would I need to do ?

**Comment by aelij** [comment]
Hi @CSharpDummy,

I could've supported VB.NET from the start, but I've decided not to as a token protest 👼. I believe Microsoft's resources would've been better spent on C#, especially considering the amount of code poured into Roslyn for rebuilding the compiler, and the extreme similarities between these languages.

Also – I have a very limited amount of time to work on RP, and I'd like to focus on features that have broad use. Even if someone were to contribute the code, I'd have to maintain it for the long run.

I may introduce a plugin model which would allow extending RoslynPad to that effect. In the meantime, you're more than welcome to fork and create your own VB-enabled 'Pad. 😁 I can give you a bit of guidance, but mostly it's searching for `CSharp` in the `RoslynPad.Roslyn` assembly and adding VB where appropriate. Note some classes would have to be imported from the VB Roslyn repo. For basic support, I think you could just modify the `RoslynHost` class (i.e. create a `VisualBasicCompilation` and change the language of the `Project`).

Eli.

**Comment by CSharpDummy** [comment]
Hi,

I agree with and if was me, I would stick with c#. But we had a requirement
to support both. I ended up buying the actipro syntaxeditor ... It has it
own lexer which has it pros and cons. Bit overall the project came out
nicely.

I will for sure using your editor in the future ...

Great job and the look is great.

Holger
