### ISSUE TITLE
Update libraries to .NET Core / Standard 2.0 and applications to .NET 4.6.1

### ISSUE THREAD

**Issue by rtigithub** [aelij/RoslynPad#210]
To help maintain forward momentum for this project I have updated the projects to .NET Core / Standard 2.0 and .NET framework 4.6.1.  I have not had a chance to test the Avalonia framework.  I can issue a PR if the community is interested.

**Comment by aelij** [comment]
Thanks @rtigithub, but I've already upgraded to .NET Standard 2.0 in order to upgrade to Avalonia 0.6 :)

I did not change the desktop framework version, though. Why was it necessary?

**Comment by rtigithub** [comment]
@aelij Any chance you could push your private branch? All of the work that I am doing is using the updated version that I created.  This may help explain why Intellisense is working properly for me, but not for others.

**Comment by thomaslevesque** [comment]
> I did not change the desktop framework version, though. Why was it necessary?

.NET 4.6 doesn't support .NET Standard 2.0 packages. .NET 4.6.1 does
