### ISSUE TITLE
The assembly manifest definition found does not match the assembly reference

### ISSUE THREAD

**Issue by Chickenbrother** [aelij/RoslynPad#213]
After the code is downloaded, open it with Visual studio 2017, then start the run. After the nuget package is restored, this error occurs.

  | Message | "未能加载文件或程序集“System.Collections.Immutable, Version=1.2.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a”或它的某一个依赖项。找到的程序集清单定义与程序集引用不匹配。 (异常来自 HRESULT:0x80131040)" 

               `var partTypes = assemblies
                .SelectMany(x => x.DefinedTypes)
                .Select(x => x.AsType());
            _compositionContext = new ContainerConfiguration()
                .WithParts(partTypes)
                .CreateContainer();`

in RoslynHost.cs  file

**Comment by iveksp** [comment]
Try put this config in App.config file:
```
<runtime>
    <assemblyBinding xmlns="urn:schemas-microsoft-com:asm.v1">
      <dependentAssembly>
        <assemblyIdentity name="System.Collections.Immutable" publicKeyToken="b03f5f7f11d50a3a" culture="neutral"/>
        <bindingRedirect oldVersion="0.0.0.0-4.0.0.0" newVersion="1.2.1.0"/>
      </dependentAssembly>
    </assemblyBinding>
  </runtime>
```

**Comment by aelij** [comment]
@Chickenbrother  I'm unable to repro this. Must be an issue on your machine. I suggest you clean and rebuild. Maybe also clear your NuGet caches.

@iveksp Binding redirects should be auto-generated.
