### ISSUE TITLE
Request for Access

### ISSUE THREAD

**Issue by Merovech** [aelij/RoslynPad#215]
Please forgive me if this isn't the correct place.  This is my first contribution to... well, any open source git project, actually, so I'm not sure what protocol is here.

I would like to contribute to RoslynPad.  I use it a lot, and there are a few things I think could be done to improve things.  (That sounded ominous; really I have a few ideas and the ability to implement the myself, so I thought I would try to contribute.)

What triggered this message is the fact that I actually have implemented a solution to [Issue 185](https://github.com/aelij/RoslynPad/issues/185) (option to disable bracket completion).  I tried to push the branch from Visual Studio and got a 403 error.  So here I am. :)

What do I need to do in order to get permissions to create a branch?

Thanks!

-Merovech

**Comment by ohadschn** [comment]
Hey @Merovech - you might want to read up a little on Pull Requests, which is the standard for contributing on GitHub: https://help.github.com/articles/about-pull-requests/

Might I also suggest you open separate issues for the improvements you have and discuss them with @aelij just in case he has other ideas for their implementation, or even implemented them already in a private branch (these things happen all the time)...

**Comment by Merovech** [comment]
Hi @ohadschn !

Thanks for the reply.  I'm more than happy to adjust with whatever I need to; I'm just trying to understand the process so I can get started. :)

I actually use git at work, so I'm familiar with branching and pull requests.  That's what got me to making this post, in fact - I cloned the repo, made a topic branch for my changes (`bracket-disable-option`), applied my changes to it, then went to publish the branch so I could make a PR out of it.  When I went to publish the branch (really, sync to GitHub for the first time), I got this:

> Error encountered while pushing branch to the remote repository: Git failed with a fatal error.
unable to access 'https://github.com/aelij/RoslynPad.git/': The requested URL returned error: 403

I assumed that it was a permissions error, so here I am.

Looking at the article you linked, though, I'm wondering: should I be requesting permissions to contribute here or is it preferred that I fork the whole thing and create a Pull Request across forks?

One more question: I did post about the improvements I have on the original issue.  I'm perfectly happy to open a new issue for it, but is that the preferred method here?  I'm used to looking at two issues addressing the same thing and one being declared a duplicate and closed. :)

**Comment by aelij** [comment]
@Merovech I think the problem is that you cloned the repo from here and not your fork. You can use `git remote` to change it, then push to your fork.

As @ohadschn pointed out, GitHub has detailed docs, so please consult them :) There's no special access required to create a PR to any public repo.

**Comment by Merovech** [comment]
@aelij Makes sense.  Didn't realize we should PR from forks and not branches.  Thanks!

**Comment by ohadschn** [comment]
@Merovech regarding duplicate issues, that is a valid concern, but that's what the search button is for :)
