### ISSUE TITLE
Xamarin.Forms MacOS , GTK, WPF

### ISSUE THREAD

**Issue by rmarinho** [aelij/RoslynPad#217]
Hi, found this project while trying to look at something like LinqPad for MacOS. 
Seems this could work but at same time not very familiar with Avalonia. I got it working but UI was .. well you know :) 

Would like to know if you know about Xamarin.Forms, and it's backend on MacOS as well as well as WPF or GTK, I wonder if it could be a good approach. I m looking at the code now seems is based on netstandard 1.3, could the base projects move to netstandard 2.0 ? 

Is this something that would be interesting ?

**Comment by aelij** [comment]
Hey @rmarinho. I'm not sure exactly what you're suggesting... rewrite RoslynPad using Xamarin.Forms? :) That's not a viable option at the moment. I rely heavily on AvalonEdit, an open source editor (which I also ported to Avalonia, being very similar to WPF).

The Mac version is very much in alpha. Once I get more time to work on it, it will get better. Avalonia itself is constantly improving, and I find it superior to Xamarin.Forms.
