### ISSUE TITLE
Unable to run v13.3 in Linux

### ISSUE THREAD

**Issue by shanewalters** [aelij/RoslynPad#219]
Ignoring the UI issues already reported (https://github.com/aelij/RoslynPad/issues/216), I can't actually get a snippet to run.

For example, attempting to run the code `"asdf".Dump();` results in `Unable to create host process`:

![screenshot from 2018-10-20 20-42-19](https://user-images.githubusercontent.com/3628703/47262565-fda76380-d4a8-11e8-9bd1-a53d7171a3e3.png)

I am running Linux Mint 18.3.

$ lsb_release -a
No LSB modules are available.
Distributor ID:	LinuxMint
Description:	Linux Mint 18.3 Sylvia
Release:	18.3
Codename:	sylvia

$ dotnet --info
.NET Command Line Tools (2.1.200)

Product Information:
 Version:            2.1.200
 Commit SHA-1 hash:  2edba8d7f1

Runtime Environment:
 OS Name:     linuxmint
 OS Version:  18.3
 OS Platform: Linux
 RID:         linuxmint.18.3-x64
 Base Path:   /usr/share/dotnet/sdk/2.1.200/

Microsoft .NET Core Shared Framework Host

  Version  : 2.0.7
  Build    : 2d61d0b043915bc948ebf98836fefe9ba942be11

**Comment by jdonohoo** [comment]
I'm having the same issue.
There is an untapped market if you supported this product as the cross platform linqpad.
Linqpad has over 2million downloads... There is nothing like this for OSX, this could be the thing!

**Comment by jdonohoo** [comment]
This is happening because RoslynPad is expecting dotnetcore 1 not 2.X

**Comment by aelij** [comment]
I've updated RP to .NET Core 2.1 (latest master). Give it another go.

**Comment by aelij** [comment]
Closing this issue for now as the Avalonia version is still work in progress :) I'd still welcome any feedback you have.
