### ISSUE TITLE
System.NullReferenceException when searching for Nuget packages with the Exact checkbox unchecked

### ISSUE THREAD

**Issue by Habush** [aelij/RoslynPad#22]
When I try to search for a package without checking the Exact checkbox, it raises System.NullReferenceException.
Here is the full stack trace:
![roslynpadexception](https://cloud.githubusercontent.com/assets/6312328/15652814/87ba0b72-2691-11e6-9209-9043bc036891.png)

**Comment by aelij** [comment]
Thanks for taking the time to report this. This bug has already been fixed for the upcoming 0.8 release.

BTW, you can hit Ctrl-C to copy the entire contents of the dialog.

**Comment by Habush** [comment]
Great! Thanks for making such an awesome tool. When will v0.8 be out?

**Comment by aelij** [comment]
Soon :)
