### ISSUE TITLE
Invalid Nuget configuration

### ISSUE THREAD

**Issue by Bartolomeus-649** [aelij/RoslynPad#228]
When searching for a nuget package I get this exception
_(to bad you can't copy the exception, or the exception text from the application)_

![image](https://user-images.githubusercontent.com/7513795/50913641-120a5500-1435-11e9-813f-9eb80f15a7be.png)

**Comment by aelij** [comment]
Hi, this must be an issue with your local NuGet.config file. Please see my answer in #170
