### ISSUE TITLE
RoslynPad Hosting

### ISSUE THREAD

**Issue by sadasd1** [aelij/RoslynPad#229]
When I run script in RoslynPad, it throws error "Unable to create host process", anybody faced this issue and got any solution?
![image](https://user-images.githubusercontent.com/25536966/50928740-745d5880-1429-11e9-8336-342b238f0483.png)

**Comment by aelij** [comment]
This means that the runner host process (RoslynPad.Host32.exe in this case) is crashing. As I don't collect telemetry from this process, I have no way of know what went wrong. If you want, you can collect a crash dump and send it to me.

**Comment by aelij** [comment]
The host process is gone - I've changed the entire way RP runs code. This change is in master, and will be part of v14.
