### ISSUE TITLE
failed to load assembly with #r in v14

### ISSUE THREAD

**Issue by weihuajiang** [aelij/RoslynPad#232]
my script with #r command can work in v13.3, but it can not run with v14. the exception could not load file or assembly. But after add the assembly to GAC, then the problem can be fixed. So I think some change on the assembly loader caused this problem

**Comment by aelij** [comment]
Where is the assembly? Do you use a full path? Please provide a code sample.

**Comment by weihuajiang** [comment]
I used full path, and my script is very simple,

`#r "C:\Workspace\STARTool\STARLine\bin\Release\STARLine.dll"
var STAR=new STARLine.STARCommand();`

STARLine.dll is linked to two dll in other path, and both of these two linked dll was in GAC

**Comment by aelij** [comment]
The execution runtime is being completely redone, so this will be resolved by #239.

**Comment by aelij** [comment]
@weihuajiang I've merged the changes to master, can you please check if it works for you? Note that RP now defaults to .NET Core (if it's installed). You can set the value of `DefaultPlatformName` under `Documents\RoslynPad\RoslynPad.json` to `Desktop x64` (or `x86`) to change it.

**Comment by weihuajiang** [comment]
Hello Aelij,

Thank you very much for your work. I have tested my code, it worked. But the only problem is I have to add using package namespace after #r. Without the using command, the problem can not run correctly. The code is as below,

````csharp
#r "C:\Workspace\STARTool\STARLine\bin\Release\STARLine.dll"
var STAR=new STARLine.STARCommand();
STAR.Init(true);
STAR.Start();
STAR.Initialize();
STAR.End();
````
I have add " using STARLine;" after #r.

many thanks again.

**Comment by weihuajiang** [comment]
Hello Aelij,

another problem is that current version did not support Mixed mode assembly. My lib referenced to anther lib in old dotnet runtime. When I run the script to use the libary of old dotnet version, there will be an error,
"Mixed mode assembly is built against version 'v1.1.4322' of the runtime and cannot be loaded in the 4.0 runtime without additional configuration information."

In the prevous version, the script is ok for old version dotnet.

**Comment by aelij** [comment]
Please try with the latest master @weihuajiang, I think I fixed it.
