### ISSUE TITLE
Nuget packages?

### ISSUE THREAD

**Issue by paralaxsd** [aelij/RoslynPad#233]
Hi,

This is less of an issue and more of a question:
The latest Nuget package is from Nov 2017 and still targets Roslyn 2.4. Meanwhile 78 commits have happened on master.

I'd be really keen on hosting a newer version of the Roslyn editor in my application but I'm  stuck with VS 2017 for now and thus depend on the Nuget packages since the code won't even compile 

So: how long would you say until we get a new official release with all the latest goodies that come along with it? ;)

Thanks for your splendid work!

**Comment by aelij** [comment]
I plan to publish a new version to NuGet once Roslyn 3.0 final version is out. But I may provide a compiled preview release earlier on GitHub.

> the code won't even compile

You can install VS 2019 preview side-by-side :)

**Comment by paralaxsd** [comment]
Hey thanks for the heads up, much appreciated!

> You can install VS 2019 preview side-by-side :)
Oh I could but I'm not the only stakeholder in this project. You know how it is: everything gets complicated once a multitude of people are involved.
