### ISSUE TITLE
how to use Microsoft.CodeAnalysis.Diagnostics.DiagnosticData in RoslynPad.Roslyn

### ISSUE THREAD

**Issue by dupeng0224** [aelij/RoslynPad#234]
I Found Microsoft.CodeAnalysis.Diagnostics.DiagnosticData in Microsoft.CodeAnalysis.Workspaces.dll used in RoslynPad.Roslyn，but DiagnosticData is "internal sealed", internal is only used in self assembly, how to use this internal class in RoslynPad.Roslyn?

**Comment by aelij** [comment]
https://github.com/aelij/IgnoresAccessChecksToGenerator
