### ISSUE TITLE
Add a plugin system

### ISSUE THREAD

**Issue by aloisdg** [aelij/RoslynPad#24]
Hello,

It would be really nice to have a plugin system inside RoslynPad. Since you are using WPF, I can recommend to use MEF. I used it and love it. Also it would be nice to use NuGet to manage the plugin system. If you want an example of a software using MEF, you can run Visual Studio ;)

You can try [NuPlug](https://github.com/awesome-inc/NuPlug) or follow one this links:

- [NuGet with MEF](http://matthamilton.net/nuget-with-mef)
- [NuGet as a plugin deployment platform/](http://steven.thuriot.be/nuget-as-a-plugin-deployment-platform/)
- [Creating a NuGet-based plugin engine](http://www.aaron-powell.com/posts/2011-02-20-creating-a-nuget-plugin-engine.html)
- [Manage Your MEF Parts with NuGet](https://ihadthisideaonce.com/2012/02/29/manage-your-mef-parts-with-nuget/)
- [How can I write Nuspec for MEF Plugin File](http://stackoverflow.com/questions/9759002/how-can-i-write-nuspec-for-mef-plugin-file)

Cheers,

**Comment by aelij** [comment]
Hey,

Thanks for the suggestion, but I'm not sure this is what I want to invest in right now.
Creating a good extension API is hard. Composing everything with MEF is not the issue.

What kind of extensibility points did you have in mind?

Eli.

**Comment by aelij** [comment]
Closing for now.

**Comment by aloisdg** [comment]
> What kind of extensibility points did you have in mind?

* Export/ Import code to pastebin, gist or glot.io (I made a lib for glot.io)
* Add themes (using base16-builder for example)
* Count bytes (I golf so it would be handy!)
