### ISSUE TITLE
Build on MacOS with with Core SDK 2.2

### ISSUE THREAD

**Issue by meeseeks-briclinc** [aelij/RoslynPad#240]
I'm trying to follow the steps to build on MacOS with Core SDK 2.2 instead of the 2.1 and I get the following on 'dotnet build':

Build FAILED.

/Users/colind/.nuget/packages/microsoft.net.compilers/3.0.0-beta3-final/tools/Microsoft.CSharp.Core.targets(52,5): error MSB6006: "csc.exe" exited with code 8. [/Users/colind/RoslynPad/roslynpad/src/RoslynPad.Common/RoslynPad.Common.csproj]
/Users/colind/.nuget/packages/microsoft.net.compilers/3.0.0-beta3-final/tools/Microsoft.CSharp.Core.targets(52,5): error MSB6006: "csc.exe" exited with code 8. [/Users/colind/RoslynPad/roslynpad/src/RoslynPad.Roslyn/RoslynPad.Roslyn.csproj]
    0 Warning(s)
    2 Error(s)

Any ideas what this could be?

**Comment by aelij** [comment]
No, sorry. Looks like a bug in Roslyn. You can try upgrading `Microsoft.Net.Compilers` to beta4 in `Directory.Build.props` and running restore again.
