### ISSUE TITLE
v14 - .NET framework - Exception on start

### ISSUE THREAD

**Issue by raghur** [aelij/RoslynPad#244]
Just downloaded v14. However, when I run RoslynPad.exe, I see this 

![image](https://user-images.githubusercontent.com/516267/54506399-454fef80-4962-11e9-978e-49cef4721a01.png)

and I can only close the window.

**Comment by aelij** [comment]
@raghur You should probably clean up your directory, seems like you have an older version of some assembly.

**Comment by raghur** [comment]
Did a fresh download and extracted to a new folder - still getting the same exception. Is there anything else from the environment that's picked up?

**Comment by aelij** [comment]
That can cause a `MissingMethodException` for an internal type? Not that I'm aware of. Very weird  :)
I just downloaded and extracted the version and it works for me. I'll try a different machine later.

**Comment by aelij** [comment]
I've tried on several different machines, this doesn't repro. Closing for now. Please reply if you have more info. You can also try compiling a version for yourself.

**Comment by raghur** [comment]
So installed 4.7.2 again and restarted and now the error has disappeared :-o
