### ISSUE TITLE
Self Contained

### ISSUE THREAD

**Issue by andymac4182** [aelij/RoslynPad#245]
Hi,

Do you think you will provide as a self-contained deployment so this can run without a particular version of dotnet core being installed on the machine?

Cheers,
Andrew

**Comment by aelij** [comment]
That's a nice idea. But I'd have to provide separate binaries for every platform, no? I'll consider it.

**Comment by andymac4182** [comment]
Yeah you would need to publish one per platform you wanted to support.

**Comment by EifelMono** [comment]
Have a look at dotnet warp where you can make 1 single exe file 

https://github.com/Hubert-Rybak/dotnet-warp

or use dotnet-warp as a global tool

https://www.nuget.org/packages/dotnet-warp/

or make Roslynpad as a global tool
so anybody can use it directly after installation from nuget from the shell.

https://docs.microsoft.com/de-de/dotnet/core/tools/dotnet-tool-install

Here is a list with of other dotnet tools
https://github.com/natemcmaster/dotnet-tools

**Comment by aelij** [comment]
RoslynPad v15 now relies on .NET Core **SDK** being installed, so no point in having it self-contained.
