### ISSUE TITLE
No Syntax-Highlighting for certain keywords (for, return, ...)

### ISSUE THREAD

**Issue by Kirides** [aelij/RoslynPad#247]
Roslynpad 14

There is no syntax highlighting for certain keywords
`for`, `foreach`, `if`, `else`, `else if`, `return`, `throw`

![RoslynPad_2019-03-18_14-11-59](https://user-images.githubusercontent.com/13602143/54532448-0cc30c80-4988-11e9-8006-6801497fc72d.png)

**Comment by Kirides** [comment]
Needs `[ClassificationTypeNames.ControlKeyword] = AsFrozen(KeywordBrush),` in `src\RoslynPad.Editor.Shared\ClassificationHighlightColors.cs` At `public ClassificationHighlightColors()`

**Comment by aelij** [comment]
Thanks!
