### ISSUE TITLE
Unable to run on Mac

### ISSUE THREAD

**Issue by gurgendav** [aelij/RoslynPad#249]
Downloaded release version 14.1

Running the cross-platform .NET Core Avalonia version fails with error

> Error:
  An assembly specified in the application dependencies manifest (RoslynPad.deps.json) was not found:
    package: 'System.Drawing.Common', version: '4.5.0'
    path: 'runtimes/unix/lib/netcoreapp2.0/System.Drawing.Common.dll'

This file is present in application directory but it has path as a name.

`runtimes\linux-x64\native\libSkiaSharp.so
runtimes\osx\native\libAvaloniaNative.dylib
runtimes\osx\native\libSkiaSharp.dylib
runtimes\unix\lib\netcoreapp2.0\System.Drawing.Common.dll
runtimes\unix\lib\netstandard1.3\System.Security.Cryptography.ProtectedData.dll
runtimes\win7-x64\native\libSkiaSharp.dll
runtimes\win7-x86\native\libSkiaSharp.dll
runtimes\win\lib\netcoreapp2.0\Microsoft.Win32.SystemEvents.dll
runtimes\win\lib\netcoreapp2.0\System.Drawing.Common.dll
runtimes\win\lib\netcoreapp2.0\System.Text.Encoding.CodePages.dll
runtimes\win\lib\netstandard1.3\System.Security.Cryptography.ProtectedData.dll`

I was able to run application (still having #248 problem) after renaming this files and creating, putting them into folders.

MacOS Mojave 10.14.3 (Latest at time of issue creation)
.NET Core 2.2.105

**Comment by aelij** [comment]
@gurgendav which file did you rename exactly? Source and destination

**Comment by gurgendav** [comment]
All of them

for example 
`runtimes\unix\lib\netcoreapp2.0\System.Drawing.Common.dll`
renamed to `System.Drawing.Common.dll`, and moved to `runtimes\unix\lib\netcoreapp2.0\` folder

**Comment by aelij** [comment]
Sorry, but I don't follow :)

In your example you specified the same folder and file name for source and destination.

**Comment by aelij** [comment]
Also, how do you run the app?

**Comment by aelij** [comment]
I think you unzipped without extracting the `runtimes` subdirectory.

**Comment by gurgendav** [comment]
Sorry, my bad. 

Seems that problem is not with release but my archive utility.
After unzip-ing it didn't create `runtimes` folder and just flattens filenames.

![image](https://user-images.githubusercontent.com/13833058/54624852-9c9bb000-4a87-11e9-94f2-d71915c0cdce.png)
 
I guess that's because of "\" (backslash)

**Comment by ryangribble** [comment]
I just ran into this as well... it must be the default zip file extraction on OSX as I just downloaded the zip file and "opened" it, which extracted the files into folders (but didnt handle the backslash paths as meaning subdirectories).

I suggest re-opening this issue - Given that this is the behaviour of the default zip file handling on Mac OSX, it might be good to look at how the zip files are created for the releases, and seeing if there is a way to make them extract on Mac with subfolders without affecting behaviour on windows.  As a guess I'd say try and have the metadata in the zip file use forward slashes rather than backslashes?

**Comment by aelij** [comment]
Thanks Ryan; I’ll see what I can do in the next release.

**Comment by 0xced** [comment]
This looks like a [bug in the *Archive Utility* app](https://twitter.com/0xced/status/1059909122093649921) which automatically decompress your downloaded files. If you use `unzip` from the command line, the archive will be decompressed properly with directories.
