### ISSUE TITLE
Race condition with multiple .Dump() calls

### ISSUE THREAD

**Issue by phillijw** [aelij/RoslynPad#253]
```
using System.Globalization;

var flags = NumberStyles.AllowExponent | NumberStyles.Number;

Decimal.Parse("0.0000005-", flags).Dump();
Decimal.Parse("-0.0000005", flags).Dump();
Decimal.Parse("5e-7", flags).Dump();
Decimal.Parse("-5e-7", flags).Dump();
Decimal.Parse("0.0000005", flags).Dump();
Decimal.Parse("0.0000005", flags).Dump();
```

Running this code multiple times in a row will yield different results. Sometimes it returns all 6 dumps and sometimes only 3.

**Comment by aelij** [comment]
It's possible not everything gets flushed before the process ends.

**Comment by ohadschn** [comment]
@aelij how does one verify everything was flushed then?

**Comment by aelij** [comment]
@ohadschn That wasn't the issue after all - flushing did occur on `AppDomain.ProcessExit`. The problem was using `StreamReader.EndOfStream`, which works by trying to read from the stream. Removing it fixed the missing dumps.

**Comment by MarqueIV** [comment]
Why did you close my bug and reference this closed bug when the bug still clearly exists in 14.1?

**Comment by aelij** [comment]
@MarqueIV it's common practice on GitHub to close bugs once they are fixed in the main branch, not when they are released. As you can see, the fix is associated with a commit.
