### ISSUE TITLE
Unicode Display problems.

### ISSUE THREAD

**Issue by wanggangzero** [aelij/RoslynPad#256]
### Just look at the output region.

![QQ拼音截图未命名](https://user-images.githubusercontent.com/16075771/54813413-7022a680-4cc8-11e9-9317-354f8180f09c.png)

**Comment by aelij** [comment]
Probably due to the fact that the Console output stream doesn't support Unicode. Should encode the JSON differently if possible.

**Comment by aelij** [comment]
If someone's interested, the relevant code is in `ConsoleDump` (which lives in the process running the code) and maybe also `AssemblyExecutionHost`.

**Comment by wanggangzero** [comment]
First, I am honored to have written the 11111111th issue.
But aelij's solution made me a bit disappointed.
In my mind, Not supporting unicode is simply a fallback.

**Comment by aelij** [comment]
@wanggangzero I've fixed the issue, see the attached commit. It will be available in the next release.

**Comment by xumix** [comment]
@aelij still no releases :(

**Comment by aelij** [comment]
@xumix you can always compile from master
