### ISSUE TITLE
Can't get some Nuget packages

### ISSUE THREAD

**Issue by TuyenTk** [aelij/RoslynPad#257]
Hi team,

I tried to add AutoMapper, RoslynPad was abled to suggest the namespace and function correctly, but when I press F5 it said can not find AutoMapper:

![image](https://user-images.githubusercontent.com/4112561/54861789-0e167f80-4d62-11e9-8eaa-e079baa65cc5.png)

I have pressed the Nuget Restore button before press Run.

**Full code snippet:**

```
#r "nuget:AutoMapper/8.0.0"
#r "nuget:Newtonsoft.Json/12.0.1"

using AutoMapper;
using Newtonsoft.Json;

public class User
{
    public string? Name { get; set; }
    public string? Password { get; set; }
}

public class UserDto
{
    public string? Name { get; set; }
}

var mapper = new MapperConfiguration(cfg => {
  cfg.CreateMap<User, UserDto>();
}).CreateMapper();

var userInDatabase = new User
{
    Name = "John",
    Password = "12345"
};

var userForReturn = mapper.Map<UserDto>(userInDatabase);
var text = JsonConvert.SerializeObject(userForReturn, Formatting.Indented);
Console.WriteLine(text);
```

**Error:**

```
Unhandled Exception: System.IO.FileNotFoundException: Could not load file or assembly 'AutoMapper, Version=8.0.0.0, Culture=neutral, PublicKeyToken=be96cd2c38ef1005'. The system cannot find the file specified.
   at Program.<<Initialize>>d__0.MoveNext()
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
   at Program.<Initialize>()
   at Program.<Main>()
```

Windows 10 1809 64bit
All updates installed
RoslynPad 14.1 portable, saved in Destop folder, all configs are in default state.

**Comment by aelij** [comment]
Can you please click the folder button on the toolbar and attach the `deps.json` file?

**Comment by aelij** [comment]
I think I found the bug, the deps file is not properly copied. You can work around it by switching to a different target framework (or version) and then switching back, it will reset the build directory.

**Comment by TuyenTk** [comment]
@aelij yes that work. I also tried to restart the program and the code ran successfully.

**Comment by jefflafay** [comment]
This bug is still relevant in 14.1 on windows 10. These are workarounds and it should work properly out of the box. It happened the first time I tried adding a nuget package which was a little frustrating as a new user to the app.
