### ISSUE TITLE
Runtime always defaults to Core x64 for new windows

### ISSUE THREAD

**Issue by binarydad** [aelij/RoslynPad#259]
The default is Core x64, but our company isn't on .NET Core yet and all of our libraries (that we test in Roslynpad) are not. Can we have the ability to change the default runtime or at least persist this when new windows are opened?

**Comment by aelij** [comment]
It's actually in the [release notes](https://github.com/aelij/RoslynPad/releases/tag/14) - `DefaultPlatformName` setting :)

**Comment by binarydad** [comment]
Thank you. I've created the file and set the contents below, but cannot fgure out what the value should be. I tried just a string but that isn't working. What should the value be for desktop x86? Thanks again.

{
    "DefaultPlatformName": "Desktop x86"
}

**Comment by aelij** [comment]
The file should already be there if you started RP even once. Under User/Documents/RoslynPad. And yes, the values are the text from the combo box.

**Comment by binarydad** [comment]
That did the trick. Thank you.
