### ISSUE TITLE
IOException when you try run project

### ISSUE THREAD

**Issue by mcpontorez** [aelij/RoslynPad#260]
When you try run any file under any runtimes throws System.IOException.
Windows 10. RoslynPad 14.1 from MS Store
![Screenshot](https://user-images.githubusercontent.com/31940612/55107188-b8373400-50e1-11e9-9951-cb3dd211bb99.PNG)
![Screenshot2](https://user-images.githubusercontent.com/31940612/55107331-1c59f800-50e2-11e9-888f-fff63ae0fad7.PNG)

**Comment by aelij** [comment]
Hey, can you please translate the message? :)

**Comment by aelij** [comment]
Also list the content of the build folder (click the folder icon on the toolbar)

**Comment by LechPa** [comment]
I think that the message states:
The specified file cannot be encrypted

**Comment by Trapov** [comment]
I'm experiencing the same issue. 
All i have in the build directory is just one foder `nuget` with some cache files.
![image](https://user-images.githubusercontent.com/13402883/55286646-fff6dd80-53b7-11e9-9ab1-323828fc5c5d.png)

**Comment by aelij** [comment]
@Trapov Can you please send me (attach here or email) the project.assets.json file?

**Comment by Trapov** [comment]
```json
{
  "runtimeTarget": {
    "name": ".NETCoreApp,Version=v2.2"
  },
  "targets": {
    ".NETCoreApp,Version=v2.2": {
      "RoslynPad.Runtime/0.0.0": {
        "type": "project",
        "runtime": {
          "RoslynPad.Runtime.dll": {}
        }
      }
    }
  },
  "libraries": {
    "RoslynPad.Runtime/0.0.0": {
      "type": "project",
      "serviceable": false,
      "sha512": ""
    }
  }
}
```

**Comment by aelij** [comment]
Hmm. That looks fine. Would you mind attaching a debugger to RoslynPad and getting me a first-chance stack trace?

**Comment by Trapov** [comment]
Yeah, sure.

**Comment by Trapov** [comment]
I think I'm doing something wrong, but couldn't get any stack traces. Steps I did:
1) Cloned the repository and jumped to the 14.1 tag.
2) Built everything and set in Visual Studio where to find the *.pdb files.
3) Tried to compile something with RoslynPad and couldn't hit my breakpoints around the place it approximately crashes or catch the exception.

**Comment by aelij** [comment]
You don't need breakpoints, just setup VS to break on all managed exceptions - Debug > Windows > Exception Settings > Check 'Common Language Runtime`. Thanks!

**Comment by Trapov** [comment]
That's all I got. @aelij 
```
System.IO.IOException   
HResult=0x80071770   
Message=The specified file could not be encrypted.    
Source=mscorlib   
StackTrace:    at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
```

**Comment by aelij** [comment]
If you let it continue (F5) you should get a different stack, until it’s caught.

**Comment by Trapov** [comment]
@aelij no, that's the only exception I'm getting. Nothing more than that.

**Comment by Trapov** [comment]
@aelij Just tried the master branch and it works like a charm. I guess the Microsoft Store app is the one to blame, something happened after the update and it still doesn't work.

**Comment by aelij** [comment]
I think I found the problem - RP is attempting to copy from an encrypted location to a non-encrypted location. See [here](https://docs.microsoft.com/en-us/windows/desktop/fileio/handling-encrypted-files-and-directories) - `ERROR_ENCRYPTION_FAILED`.

I've added a fix, hopefully it will resolve the issue.
