### ISSUE TITLE
Ability to add custom dll to references

### ISSUE THREAD

**Issue by ghost** [aelij/RoslynPad#267]
Added custom dll(Calculator.dll) to RoslynPad.Editor.Windows.
```
public static class Calculator
{
    /// <summary>
    /// Add an Integer
    /// </summary>
    /// <param name="num1"></param>
    /// <param name="num2"></param>
    /// <returns></returns>
    public static int Add(int num1,int num2)
    {
        return num1 + num2;
    }
}
```
it cannot recognize my custom dll summary.
I  want RoslynPad  can recognize my custom dll summary("Add an Integer").
![image](https://user-images.githubusercontent.com/49520393/55954180-00855300-5c99-11e9-967c-1a963e94169d.png)

How to check the Summary in **RoslynPad Setting**??

**Comment by aelij** [comment]
Do you have an XML doc file (`Calculator.xml`) in the same folder where the dll is?
