### ISSUE TITLE
Documents panel may be "Docked as tabbed document" but not put back

### ISSUE THREAD

**Issue by jmairboeck** [aelij/RoslynPad#27]
The documents panel can be "Docked as document" but not put back because all other docking options have been disabled.
I suggest disabling "Dock as tabbed document" as well.

**Comment by aelij** [comment]
Thanks, I'll do that.

**Comment by aelij** [comment]
@jmairboeck Meanwhile you can delete the folder `%localappdata%\RoslynPad` which contains the settings file.

**Comment by jmairboeck** [comment]
@aelij I have already removed the Setting from the Settings file, but thank you nonetheless.
