### ISSUE TITLE
Can't run 14.1 on Linux Debian with .NET Core 2.2 runtime installed.

### ISSUE THREAD

**Issue by david-tamar** [aelij/RoslynPad#270]
Hi, I heared today about RoslynPad and I was completely stunned and amazed by it, so I ran to download RoslynPad v14.1 form [roslynpad.net](https://roslynpad.net/) to try it out on my Linux Debian machine, having both .NET Core 2.2 and 2.1 SDK and Runtime both installed for each of them from the official Microsoft repositories using APT.

**Here are some relevant screenshots:**
My aptitude package manager:
![image](https://user-images.githubusercontent.com/24723374/56935210-50b53f80-6af8-11e9-9910-5c63e579ea04.png)
The error message I'm receiving from `dotnet` when I'm trying to run `RoslynPad.exe`:
![image](https://user-images.githubusercontent.com/24723374/56935303-cb7e5a80-6af8-11e9-9e67-12706e443496.png)

**Comment by aelij** [comment]
That's the Windows version. The xplat version (preview) is available on the [releases](https://github.com/aelij/RoslynPad/releases) page. See the main README for instructions.
