### ISSUE TITLE
Reflection issues with scripting environment

### ISSUE THREAD

**Issue by Kirides** [aelij/RoslynPad#275]
Getting MethodAccessExceptions on Reflection code because code is contained in a private class
This makes prototyping Reflection very cumbersome / impossible because of TypeLoadExceptions and more.

Dynamically created assemblies can not access Types contained inside the script, because they are nested inside a private class.

Issue does not appear on regular Console-App, but on Roslyn "Script"s
e.g.
```
class Program {
 // Errors with Reflection because "public"-nested classes are actually "private" 
}
```

```
public class Program {
 // No more errors 
}```

**Comment by aelij** [comment]
Unfortunately this is not something I have control over AFAIK. The script language is provided by Roslyn, and it creates the class and the Main method.

**Comment by aelij** [comment]
Closing now. If someone comes up with a clever solution for this, please let me know.

**Comment by kzu** [comment]
@aelij could a source generator make the `Program` class partial?

**Comment by aelij** [comment]
@kzu I don't think so, because the Program class is entirely generated, it's not in source.
