### ISSUE TITLE
Exception with OpenCVSharp

### ISSUE THREAD

**Issue by seungyongshim** [aelij/RoslynPad#276]
1. Select Desktop x64 mode
2. Run 
```csharp
#r "nuget:OpenCvSharp4.Windows/4.1.0.20190416"

using System;
using OpenCvSharp;

var a = new Mat(150,150, MatType.CV_16S);
```
![image](https://user-images.githubusercontent.com/6711748/57113836-5c676700-6d81-11e9-9c29-763b664d71f8.png)

**Comment by jhgoodwin** [comment]
Probably worth clarifying if this works any other way (eg as a normal .net core app or something).

**Comment by aelij** [comment]
Packages with native DLLs are currently not supported. I've opened #277 to track this issue.
