### ISSUE TITLE
Enable code collapsing on RoslynCodeEditor

### ISSUE THREAD

**Issue by lanzhiquan** [aelij/RoslynPad#283]
I try to enable code collapsing on AvalonEdit control and I can not enable it properly.

`public FoldingManager foldingManager;`
`public XmlFoldingStrategy foldingStrategy;`

to enable code collapsing I insert this code on Window_Loaded

`foldingManager = FoldingManager.Install(textEditor.TextArea);`
`foldingStrategy = new XmlFoldingStrategy();`
`foldingStrategy.UpdateFoldings(foldingManager, textEditor.Document);`

and to update the collapsing I insert to textEditor_TextChanged this code

`foldingStrategy.UpdateFoldings(foldingManager, textEditor.Document);`

from the Window_Loaded I get only the first collapsing to work (like in the picture the other tags not updated)

the code in textEditor_TextChanged does not work at all

reference :
`https://stackoverflow.com/questions/35571855/enable-code-collapsing-on-avalonedit-control`

**Comment by aelij** [comment]
You're using an `XmlFoldingStrategy` which wouldn't work for C#
