### ISSUE TITLE
Error running .NET Core 3.0.0-preview5-27626-15

### ISSUE THREAD

**Issue by Kirides** [aelij/RoslynPad#284]
The following errors show up once i try to run any code on .NET Core `3.0.0-preview5-27626-15`

```
A JSON parsing exception occurred in 
[C:\Users\USER\AppData\Local\Temp\RoslynPad\Build\e613801f-99b7-4d0f-a40d-
01a0870a7f09\RoslynPad-Program6.deps.json]: Key not found 
```
```
Error initializing the dependency resolver: An error occurred while parsing: 
C:\Users\USER\AppData\Local\Temp\RoslynPad\Build\e613801f-99b7-4d0f-a40d-
01a0870a7f09\RoslynPad-Program6.deps.json
```
![Image](https://puu.sh/DuJkJ.png)

**Comment by aelij** [comment]
The next version will support .NET 3.

**Comment by mikernet** [comment]
I'm getting this error with the latest version on the RosynPad homepage (v14.1) if I pick any .NET Core version >= 3.0.0.

Am I missing something obvious or is this a new bug?

**Comment by aelij** [comment]
No, I just haven't released a version since :) You can build mater to get the fix. Hopefully will release something soon.

**Comment by mikernet** [comment]
Thanks that did it :)
