### ISSUE TITLE
Is RoslynPad supports BenchmarkDotNet?

### ISSUE THREAD

**Issue by Krakean** [aelij/RoslynPad#285]
Hello
I really like RoslynPad because it allows make quick code checks/ideas, when starting Visual Studio for this is kinda overkill just because its too bloated.
But, I was frequently used BenchmarkDotnet within Visual Studio for such things before I explored RoslynPad for myself.
But, as I can see it doesn't like BenchmarkDotNet, at least such sample code doesn't not work nor using netcore 2.2 nor 3.0:

```cs
#r "nuget:BenchmarkDotNet/0.11.5"
using BenchmarkDotNet;
using BenchmarkDotNet.Attributes;
using BenchmarkDotNet.Running;
using System.Buffers;

public class Test
{
    [Benchmark]
    public void RentReturn() => ArrayPool<byte>.Shared.Return(ArrayPool<byte>.Shared.Rent(256));
}

var summary = BenchmarkRunner.Run<Test>();
```

When I try to run it I get this:
> Program containing Benchmark method RentReturn has incorrect access modifiers.
> Declaring type must be public.

But the same code works fine in VisualStudio 2017/2019.

**Comment by aelij** [comment]
Looks like it's a limitation of BenchmarkDotNet, combined with the face that Roslyn compiles a script class with an `internal` modifier. I'll see if there's something that can be done about it.

**Comment by aelij** [comment]
Closing this issue, as there's not much I can do about it. I opened an issue on BenchmarkDotNet.

**Comment by aelij** [comment]
BTW, it is possible to manually run tests, but this ignores most of BDN's attributes, e.g.:

```cs
#r "nuget:BenchmarkDotNet/0.11.5"

using BenchmarkDotNet;
using BenchmarkDotNet.Attributes;
using BenchmarkDotNet.Configs;
using BenchmarkDotNet.Jobs;
using BenchmarkDotNet.Parameters;
using BenchmarkDotNet.Running;
using BenchmarkDotNet.Toolchains.InProcess;
using System.Buffers;

public class Test
{
    [Benchmark]
    public void RentReturn() => ArrayPool<int>.Shared.Return(ArrayPool<int>.Shared.Rent(256));
}

var job = Job.Default.With(InProcessToolchain.Instance);
var config = BenchmarkConverter.GetFullConfig(typeof(Test), null)
    .With(job).CreateImmutableConfig();
var summary = BenchmarkRunner.Run(new BenchmarkRunInfo(new[] { BenchmarkCase.Create(new Descriptor(typeof(Test), typeof(Test).GetMethod(nameof(Test.RentReturn))), job,
    new ParameterInstances(Array.Empty<ParameterInstance>()), config) }, typeof(Test), config));
```

**Comment by aelij** [comment]
FYI using the new ".cs" file mode, it's now possible to run benchmarks using RP. Note you should turn on compiler optimizations (clock button on toolbar).

```cs
#r "nuget: BenchmarkDotNet, 0.13.3"

using BenchmarkDotNet.Attributes;
using BenchmarkDotNet.Configs;
using BenchmarkDotNet.Jobs;
using BenchmarkDotNet.Running;
using BenchmarkDotNet.Toolchains.InProcess.NoEmit;
using System.Buffers;

_ = BenchmarkRunner.Run<Test>();

public class InProcessConfig : ManualConfig
{
    public InProcessConfig()
    {
        AddJob(Job.MediumRun
            .WithToolchain(InProcessNoEmitToolchain.Instance));
    }
}

[Config(typeof(InProcessConfig))]
[MemoryDiagnoser]
public class Test
{
    [Benchmark]
    public void RentReturn() => ArrayPool<int>.Shared.Return(ArrayPool<int>.Shared.Rent(256));
}
```
