### ISSUE TITLE
Dump Encoding

### ISSUE THREAD

**Issue by mshakurov** [aelij/RoslynPad#287]
What happened to the encoding of the strings displayed by the Dump(...) methods?

In the previous version, any encoding lines were displayed correctly.

This is what the command displays:

"**russian language symbols**" .Dump ();

### СЂСѓ Р»СЏ Р»СЏ

**Comment by ttkoma** [comment]
In release 14.1 bug.
On latest master build
- no bug.

**Comment by aelij** [comment]
Duplicate of #256
