### ISSUE TITLE
The overload insight window does not show which index is selected.

### ISSUE THREAD

**Issue by alphaleonis** [aelij/RoslynPad#290]
Suggest that the `RoslynOverloadProvider` sets the `CurrentIndexText` in its `Refresh` method to display a text such as "3 of 5" between the arrows in the overload insight windows to indicate which overload is currently showing. (This is the same as is used in eg. Visual Studio).

It seems to be a simple fix, and I'd be happy to supply a PR if desired.

**Comment by aelij** [comment]
This fix should come from Roslyn, and I believe they improved it in the latest version. I'll check when I update.

**Comment by alphaleonis** [comment]
From Roslyn? Hmm... okay, maybe I'm missing something, but it seemed to me that this was handled by RoslynPad.Editor.Shared\RoslynOverloadProvider.cs which implements the interface from AvaloniaEdit.

Anyway, one way to provide this feature would be to add the line below to the end of `RoslynOverloadProvider.Refresh()`:
`CurrentIndexText = $" {_selectedIndex + 1} of {_items.Count} ";`

**Comment by aelij** [comment]
Oh, you're right of course. I was thinking of something else (automatic selection of the current overload).

Sure, I'd welcome a PR!

**Comment by YanerTavuz** [comment]
Hello, I would like to have this as a nuget package release. 
When can I expect a new release on nuget? 

Warm regards /
YanerTavuz

**Comment by alphaleonis** [comment]
Can we expect a release of a NuGet package including this fix sometime soon @aelij ?

**Comment by aelij** [comment]
I've released new packages last week
