### ISSUE TITLE
Console and Dump (of 14.1) dislays invalid caharcters of strings with non ASCII code pages?

### ISSUE THREAD

**Issue by mshakurov** [aelij/RoslynPad#293]
"Russian Тру Ля Ля".Dump();
displays:
Russian РўСЂСѓ Р›СЏ Р›СЏ

![DisplayError](https://user-images.githubusercontent.com/5284014/60756078-a67afc00-a001-11e9-9e37-1daec01d642f.png)

**Comment by aelij** [comment]
Duplicate of #256
