### ISSUE TITLE
Error "The calling thread must be STA (...)"

### ISSUE THREAD

**Issue by IBIT-ZEE** [aelij/RoslynPad#296]
This works OK in RoslynPad version 13 
but gives this error in version 14.1 (last available)

#r "System.Windows"
#r "System.Windows.Presentation"

using System.Windows;
Window w1 = new Window();
w1.ShowDialog();

* PS
I also try to define a function with [STAThread]
to contain the Window creation 
and call it from the main code...
but the result is the same

?Any ideas

**Comment by aelij** [comment]
It's actually a breaking change, see the [release notes](https://github.com/aelij/RoslynPad/releases/tag/14).

You need to call `await Helpers.RunWpfAsync();`.
