### ISSUE TITLE
Could not load type 'Desktop' from assembly 'Microsoft.CodeAnalysis.Workspaces'

### ISSUE THREAD

**Issue by Andrew-EDSL** [aelij/RoslynPad#299]
Packages/Dependencies
===============

.net framework v4.6.1
Microsoft.CodeAnalysis.CSharp v3.2.1
RoslynPad.Roslyn 2.4.0 

Steps to reproduce/Description of problem
============================

Create a new .net project with just *RoslynPad.Roslyn* installed via nuget:
```    
 static void Main(string[] args)
 {
    RoslynHost host = new RoslynHost();
 }
```

Program executes successfully. Then install *Microsoft.CodeAnalysis.CSharp* via nuget and re-run the program and the result is:

`
System.TypeLoadException: 'Could not load type 'Desktop' from assembly 'Microsoft.CodeAnalysis.Workspaces, Version=3.2.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'.'
`

Extra Info
======
Using Microsoft.CodeAnalysis.CSharp v2.4.0 is OK

**Comment by aelij** [comment]
The RoslynPad.Roslyn package must correspond to the Microsoft.CodeAnalysis* package versions, as explained in the README.

I will be publishing new versions soon to match the latest Roslyn compilers.

**Comment by mjanulaitis** [comment]
This is a very difficult control to re-distribute.  I had it working then upgraded a slew of packages now I the control will not load. I am using Microsoft.CodeAnalysis.CSharp 3.4.0.  Do I need to include a .config file with the binding redirect?
