### ISSUE TITLE
Can't get this to compile.

### ISSUE THREAD

**Issue by EmperorAiman** [aelij/RoslynPad#3]
Hi. 
I tried compiling it and it gave me tons of errors like : 
NuGet Package restore failed for project RoslynPad: Unable to find version '1.2.0-beta1-20160220-01' of package 'Microsoft.CodeAnalysis.Common'..

Can you tell me how to fix it?

**Comment by aelij** [comment]
You must not have the latest version, which uses version `1.3.0-beta1-20160301-05`. See #2
