### ISSUE TITLE
Useful Features is needed 

### ISSUE THREAD

**Issue by AboAnas1992** [aelij/RoslynPad#30]
Roslyn pad is a very useful tool to be used instead of opening heavy weight or installing Gigantic sized IDE.
But in terms of Editing features  it leaks some of the most needed features:
- Formatting
- Code Folding
- Navigation (to members and classes)
- Jump to declaration
- highlight usage
- tool tips
- Renaming Refactoring
- auto completion needs more attention [incomplete name,override ,add event handlers , calling method with delegate parameters].
 * pressing ctrl+space after incomplete member name or class name should consider what I already typed , and selected an autocomplete option must replace that incomplete member name.
    - and also auto complete the [for e.g.: #r "System.Windows.|#] should consider the whole [System.Windows.] as single word for auto completion replacement. 
 * override should auto complete with the full implementation of the method or property , as in VS.
 * add event handler should generate extra auto-complete options such as [(s,e)=>{},delegate(object s, EventArgs e){},GenerateMethod(with renaming active as in VS) ..]
 * calling method with delegate-typed parameter, I might use anonymous method in this parameter, but when I type [(x|#space or =] it is auto completed with what I am not intended to use.

- highlight members types (property, method, field, local var, const) its very useful to understand code just by looking at the highlighted IDs.
- Maybe if it contains Color Schemes it would be very useful.
- Documentation and GAC search makes auto completion very bad and the whole app lags, Documentation needs to be collected Async, and it should be cancel-able if the user scrolls to another completion item.

Formatting ,code Folding,Jump to declaration,tool tip and highlight members are not that hard to be implemented, I already done that.

**Comment by aelij** [comment]
These are some great suggestions, thanks. I'll open issues for several of those.
It will take me some time to implement all of that... But I'm not in a hurry :)
For now I'm closing this issue. Will use it for reference.

That said, keep in mind RoslynPad is not meant to be an full-featured IDE replacement. It's good for a single-document script, used to test small pieces of code. Things like code navigation and color schemes are very low on my priority list.

Regarding the Control+Space and Override issues you mentioned, which RP version are you using? These should work well in 0.8.

**Comment by Ahmed-92** [comment]
thanks for replaying , but I think that most of these features are not that hard to implement, and does not make this tool a full featured IDE.
I would hear from you what is the most important feature from the previous feature.
note: I tested version 0.8 and it works fine for [override auto complete], sorry I was using version  0.7.
