### ISSUE TITLE
Utf compliant output?

### ISSUE THREAD

**Issue by xumix** [aelij/RoslynPad#300]
How can I make Roslynpad display proper international (russian) symbols in Dump output?
Now it displays some strange recoded symbols, looks like utf-8 symbol is displayed in ANSI codepage:
![image](https://user-images.githubusercontent.com/250118/65331437-8224c980-dbc5-11e9-8daa-627e049e51a7.png)

**Comment by xumix** [comment]
![image](https://user-images.githubusercontent.com/250118/65336760-9a014b00-dbcf-11e9-925a-c9e6aefa2784.png)

**Comment by aelij** [comment]
Duplicate of #256
