### ISSUE TITLE
.NET Core 3.0 compatibility

### ISSUE THREAD

**Issue by Kirides** [aelij/RoslynPad#301]
Mentioned in #284 - .NET Core 3 will be supported in a new release.
Now that .NET Core 3 is released, when can we expect work starting towards a working release?

**Comment by jogibear9988** [comment]
@aelij 
AvalonEdit is now released in V6 wich has NetCore support

**Comment by aelij** [comment]
master is already compiled against Core 3.0 (see 221e4568ab0eee2a926ccd596e58b36a606b94a4).
I'm updating the build system to support running 3.0 code. As to when, I cannot say exactly :) Hopefully in the upcoming weeks.

**Comment by Kirides** [comment]
really looking forward to this!

I hope the build-system will support wpf/forms aswell - got many snippets to test against Core :)

**Comment by jogibear9988** [comment]
could you also switch to avalonedit V6?

**Comment by aelij** [comment]
@jogibear9988 Yeah, probably

**Comment by aelij** [comment]
.NET Core 3.1 is now supported in master (see 6cdf08505caeefdc5a04a1aeab0499a2726df684). Will be releasing version 15 soon. Note this version will require the .NET Core **SDK** to work (even to run .NET Framework scripts), since part of the compilation is now handled by MSBuild.

**Comment by Kirides** [comment]
Running master raises an issue (probably because my username contains a space)
![RoslynPad_2019-12-09_08-57-17](https://user-images.githubusercontent.com/13602143/70417713-1f272e00-1a62-11ea-8550-71f5f24e73f9.png)

**Comment by aelij** [comment]
Thanks, @Kirides. Can you submit a PR? :)

**Comment by aelij** [comment]
FYI, the new version also supports .NET Core's "framework references". Here's how you can use WPF:

```cs
#r "framework:Microsoft.WindowsDesktop.App"

using System.Windows;
using System.Windows.Controls;

await Helpers.RunWpfAsync(); // initializes a dispatcher thread

var w = new Window { Content = new Button { Content = "Hello, WPF", IsCancel = true } };
w.ShowDialog()
```

**Comment by shoxlaa** [comment]
someone pls help me icant do anything ((( roslynpad doesn't have docs for beginers  that is sad
