### ISSUE TITLE
Add support for multiple nuget sources

### ISSUE THREAD

**Issue by ghelyar** [aelij/RoslynPad#303]
It would be nice to have support for multiple nuget package sources e.g. Azure DevOps and nuget.org.

This may need to support both V2 and V3 so that personal access tokens can be used, but [using a credential provider](https://docs.microsoft.com/en-us/nuget/reference/extensibility/nuget-exe-credential-providers) would be a bonus if is possible.

**Comment by aelij** [comment]
I haven't tested this, but you can try using the user/machine NuGet configuration:
https://docs.microsoft.com/en-us/nuget/consume-packages/configuring-nuget-behavior

**Comment by ghelyar** [comment]
Thanks, adding a `<packageSourceCredentials>` with a PAT for Azure DevOps to `%appdata%\NuGet\NuGet.Config` worked

**Comment by aelij** [comment]
I've added partial support for this (to be released in v15):
* Available only during restore (not in search)
* The [credential provider](https://github.com/microsoft/artifacts-credprovider) plugin must be installed in the system
