### ISSUE TITLE
references missing

### ISSUE THREAD

**Issue by bangush** [aelij/RoslynPad#306]
I am new to Roslyn, can you please tell me what i do wrong here. @aelij 

CODE

            CSharpParseOptions _parseOptions = CSharpParseOptions.Default;

            _parseOptions = _parseOptions.WithKind(SourceCodeKind.Script); 

            SyntaxTree syntaxTree = CSharpSyntaxTree.ParseText(_editor.Text, _parseOptions);
            string assemblyName = Path.GetRandomFileName();

            MetadataReference[] references = new MetadataReference[]
            {
                MetadataReference.CreateFromFile(typeof(object).Assembly.Location),
                MetadataReference.CreateFromFile(typeof(Enumerable).Assembly.Location)
            };

            CSharpCompilation compilation = CSharpCompilation.Create(
                assemblyName,
                syntaxTrees: new[] { syntaxTree },
                references: references,
                options: new CSharpCompilationOptions(OutputKind.DynamicallyLinkedLibrary));

            using (var ms = new MemoryStream())
            {
                EmitResult result = compilation.Emit(ms);

                if (!result.Success)
                {
                    IEnumerable<Diagnostic> failures = result.Diagnostics.Where(diagnostic =>
                        diagnostic.IsWarningAsError ||
                        diagnostic.Severity == DiagnosticSeverity.Error);

                    foreach (Diagnostic diagnostic in failures)
                    {
                        notifyMessage(diagnostic.Id + " : " + diagnostic.GetMessage());
                    }
                }
                else
                {
                    ms.Seek(0, SeekOrigin.Begin);
                    Assembly assembly = Assembly.Load(ms.ToArray());

                    Type type = assembly.GetType("RoslynCompileSample.Writer");
                    object obj = Activator.CreateInstance(type);
                    type.InvokeMember("Write",
                        BindingFlags.Default | BindingFlags.InvokeMethod,
                        null,
                        obj,
                        new object[] { "Hello World" });
                }
            }

CSX
> Howto resolve below errors in csx script, executed from the above mentioned code.
>// CS7099 : Metadata references are not supported.
>// CS0234 : The type or namespace name 'Windows' does not exist in the namespace 'System' (are you missing an assembly reference?)
>// CS0103 : The name 'MessageBox' does not exist in the current context.
 >// CS0246 : The type or namespace name 'Class1' could not be found (are you missing a using directive or an assembly reference?)

    #r "C:\PathToAssembly\lib\CheckSumAlgorithms.dll"

    using System;
    using System.Linq;
    using System.Security;
    using System.Windows.Forms;

     // Start();
 
     Stop();
 
        #region "codeFolding"

        public void Stop()
         {
            MessageBox.Show(System.IO.File.Exists(@"E:\PathToFile\media.mp4").ToString());
         }

        #endregion"

    public void Start()
    {
        string filename = @"E:\PathToFile\media.mp4";
	
    MessageBox.Show(CheckSumAlgorithms.Crypto.MD5Algorithm(filename).ToLower());
    MessageBox.Show(CheckSumAlgorithms.Crypto.SHA256Algorithm(filename).ToLower());
    MessageBox.Show(CheckSumAlgorithms.Crypto.SHA256Algorithm(filename).ToLower());
    
    }

**Comment by bangush** [comment]
//  InitializeEditor for above issue in Windows Form

        private RoslynCodeEditor _editor;
        private ICSharpCode.AvalonEdit.Folding.FoldingManager foldingManager;

        private void InitializeEditor(string sourceCode)
        {
            if (string.IsNullOrWhiteSpace(sourceCode))
                sourceCode = string.Empty;
            _editor = new RoslynCodeEditor();
            // bin\x86\Release
            try
            {
                var workingDirectory = Directory.GetCurrentDirectory();
                var roslynHost = new RoslynHost(additionalAssemblies: new[]
                {
                    Assembly.Load("RoslynPad.Roslyn.Windows"),
                    Assembly.Load("RoslynPad.Editor.Windows"),
                    Assembly.Load("System"),
                    Assembly.Load("System.Linq"),
                    Assembly.Load("System.Windows.Forms"),
                    Assembly.Load("System.Security")
                },
                references: RoslynHostReferences.DesktopDefault
                .With(typeNamespaceImports: new[] 
                { 
                    typeof(Class1) 
                }
                ));

                foldingManager = FoldingManager.Install(_editor.TextArea);

                cSharp = new Folding.CSharpFoldingStrategy();
                cSharp.UpdateFoldings(foldingManager, _editor.Document);

                _editor.Initialize(roslynHost, new ClassificationHighlightColors(), workingDirectory, sourceCode);
                _editor.FontFamily = new System.Windows.Media.FontFamily(fontFamilyName);
                _editor.SyntaxHighlighting = HighlightingManager.Instance.GetDefinition("C#");
                _editor.FontSize = fontFamilySize;
                _editor.Document.Changed += DocumentOnChanged;
                elementHost1.Child = _editor;
                this.Controls.Add(elementHost1);

            }
            catch (ReflectionTypeLoadException ex)
            {
                StringBuilder sb = new StringBuilder();
                foreach (Exception exSub in ex.LoaderExceptions)
                {
                    sb.AppendLine(exSub.Message);
                    FileNotFoundException exFileNotFound = exSub as FileNotFoundException;
                    if (exFileNotFound != null)
                    {
                        if (!string.IsNullOrEmpty(exFileNotFound.FusionLog))
                        {
                            sb.AppendLine("Fusion Log:");
                            sb.AppendLine(exFileNotFound.FusionLog);
                        }
                    }
                    sb.AppendLine();
                }
                string errorMessage = sb.ToString();
                //Display or log the error based on your application.
                Clipboard.SetText(errorMessage);
                MessageBox.Show(errorMessage);
            }
            finally
            {

            }
        }

**Comment by aelij** [comment]
It looks like you're missing a reference to `System.Windows.Forms`. FYI these kind of questions would be better on StackOverflow.
