### ISSUE TITLE
Error in list display

### ISSUE THREAD

**Issue by ArnaudMarcille** [aelij/RoslynPad#309]
Hello, 

I have found an error when I try to run a loop on a list:
Not all items are covered by the loop, see below some exmple:
![image](https://user-images.githubusercontent.com/28567558/68138805-62edbb80-ff29-11e9-8bba-5ae0e63674ae.png)
![image](https://user-images.githubusercontent.com/28567558/68138896-87e22e80-ff29-11e9-9761-4d0fbe6c1026.png)

I have the RoslynPad 14.1 installed.
![image](https://user-images.githubusercontent.com/28567558/68138933-97617780-ff29-11e9-98af-c66b26f0f690.png)

I have se same problem with all sort of list of objects.

**Comment by lrolvink** [comment]
I got the same problem with RoslynPad 14.1. It shows only the first three results in this scenario.

**Comment by gabeluci** [comment]
I've noticed the same thing. It seems almost like it's killing the program before it catches the last of the output. But it does seem to only do it with loops.

I thought maybe `Console.Out.Flush()` would work, thinking maybe it's just in the buffer and not flushed before the program is killed, but that didn't do it.

Adding `await Task.Delay(anything)` doesn't work either.

What finally worked is this:

```
foreach (var i in new [] { 1, 2, 3, 4 }) {
    Console.WriteLine(i);
}

await Task.Yield();
Console.WriteLine("Done");
```

If you remove either of those last two lines, it only outputs 1-3. But with both of those last lines, it output 1-4 + "done".

More specifically, what works is awaiting *any* incomplete `Task`, followed by outputting anything to the console.

**Comment by lrolvink** [comment]
> I've noticed the same thing. It seems almost like it's killing the program before it catches the last of the output. But it's not only with loops. You'll see it with this too:
> 
> ```
> Console.WriteLine("1");
> Console.WriteLine("2");
> Console.WriteLine("3");
> Console.WriteLine("4");
> ```
> 
> I thought maybe `Console.Out.Flush()` would work, thinking maybe it's just in the buffer and not flushed before the program is killed, but that didn't do it.
> 
> Adding `await Task.Delay(anything)` doesn't work either.
> 
> What finally worked is this:
> 
> ```
> foreach (var i in new [] { 1, 2, 3, 4 }) {
>     Console.WriteLine(i);
> }
> 
> await Task.Yield();
> Console.WriteLine("Done");
> ```
> 
> If you remove either of those last two lines, it only outputs 1-3. But with both of those last lines, it outputs 1-4 + "Done".
> 
> More specifically, what works is awaiting _any_ incomplete `Task`, followed by outputting anything to the console.

You have a point. Before I wanted to test this, the same code that I have seems to give more results now without any modification. I'm not sure related stuff has changed in the meantime.

What for me also did the trick is to just repeat that foreach block. You go of course twice the result but no broken results. But in short it have something to do how the program ends. Maybe ending the code with a 'return 0;' or 'Environment.Exit(0);' is better.

**Comment by aelij** [comment]
Hi, I believe this issue was fixed in 0829875. Can someone please verify by cloning and compiling? Thanks

**Comment by gabeluci** [comment]
I just tried it out this morning, and yes, it is fixed. Both the loop and the 4 `Console.WriteLine` worked just fine.

Thanks!

**Comment by aelij** [comment]
Closing. Hopefully I'll have a new release soon.
