### ISSUE TITLE
.NET Core WPF

### ISSUE THREAD

**Issue by inf9144** [aelij/RoslynPad#312]
Hey,
in the moment you have dependencies to .NET Framework 4.6 https://www.nuget.org/packages/RoslynPad.Editor.Windows/ but you have a .NET Core Version which runs with Avalaonia already. Could you provide .NET Core WPF support? I would be really happy.

Thanks!

**Comment by aelij** [comment]
It's coming in the next version, which will fully support .NET Core 3.0.

**Comment by aelij** [comment]
Duplicate of #301

**Comment by joseazevedo** [comment]
Hello Aelij, is there any wpf core version avaiable ?
