### ISSUE TITLE
current master shows error highlighting

### ISSUE THREAD

**Issue by Kirides** [aelij/RoslynPad#316]
Currently build master displays error highlighting "type System.Object" not found ...." if you swap between atleast two documents

-> 1
Document 1 builds fine - no syntax errors
-> 2
Document 2 builds fine - no syntax errors
-> 1
Document 1 shows error about type not found, but runs fine if `Run` is pressed. Highlighting is not fixed by typing keys.

ExecutionHost.cs - line 392:
```csharp
public void UpdateLibraries(IList<LibraryRef> libraries)
{
    lock (_libraries)
    {
        if (!_libraries.SetEquals(libraries))
        {
            _libraries.Clear();
            _libraries.UnionWith(libraries);

            TryRestore();
        }
    }
}
```
`TryRestore` is not executed for Document 1 because its libraries did not change - this currently leads to an issue with not correctly highlighting the code.

a *temporary* fix would be to move `TryRestore();` to be always executed

**Comment by aelij** [comment]
It was a change in the AvalonDock implementation (I upgraded the NuGet). Using a different distro solved it (https://github.com/Dirkster99/AvalonDock).
