### ISSUE TITLE
How to load source file in host?

### ISSUE THREAD

**Issue by nluyan** [aelij/RoslynPad#318]
I've known use #load "xxx.csx" can load code from other source file, but is there any way could have the same effect in host envirment? I mean do something in RoslynHost or RoslynCodeEditor maybe.
I have a very long reference files list, I don't want them be shown in code.
My English is not good, hope you can understand what I've said.
Thanks.

**Comment by aelij** [comment]
`#load` should be supported in `RoslynHost`, though I have not used it myself. Did you try? What were the results?

**Comment by weihuajiang** [comment]
In the previous version, I have add reference to the RoslynHost, first you have to add your assembly to GAC and RoslynPad, and then modify the InitializeInternal function of MainViewModelBase as below, 
Type[] t = { Type.GetType("STARLine.STARCommand, STARLine"),  //your type full name
                Type.GetType("Scheduler.SchedulerEngineEx, SchedulerEngineEx"),
                Type.GetType("Scheduler.SchedulerView, SchedulerView") };

            RoslynHost = await Task.Run(() => new RoslynHost(CompositionAssemblies,
                RoslynHostReferences.NamespaceDefault.With(typeNamespaceImports: t)))

**Comment by aelij** [comment]
Sorry but I'm not sure I follow. Does this not work in the latest version?

**Comment by aelij** [comment]
Closing. Please reply if you have more information.
