### ISSUE TITLE
New Nuget Package.

### ISSUE THREAD

**Issue by jogibear9988** [aelij/RoslynPad#319]
Is it possible to release a new nuget package with netcore and avalonedit 6 support?

**Comment by jogibear9988** [comment]
@aelij 
do you have an estimate when new nuget packes will be ready?

**Comment by aelij** [comment]
I'm still working on the latest version. Will update the packages when it's done.

**Comment by jogibear9988** [comment]
Thanks for the Info.

Since we are Trying to switch our software to NetCore 3.1, we would need to switch to Avalonedit 6, and this would only be possible with an updated package.

**Comment by mrn-aglic** [comment]
Looking forward to this... the current nuget seems to be incompatible with the current version of Avalonia.

**Comment by inf9144** [comment]
Is the update in sight? I would really appreciate it. If you need any kind of help please let us know.

**Comment by aelij** [comment]
New packages have been published! Using Roslyn 3.6.0.
https://www.nuget.org/packages?q=RoslynPad
