### ISSUE TITLE
Progress report

### ISSUE THREAD

**Issue by stanac** [aelij/RoslynPad#321]
On scripts that take a longer time to execute it would be nice to have some kind of progress report (e.g. script that needs to process 100K files or something similar).

Suggestion is to implement interface like this:

```csharp
ProgressReport.Report(double percentageDone); //  where percentageDone is between 0.0 and 1.0
```

Progress can be displayed next to run button.

@aelij I could work on this and submit a PR if you agreed with the suggestions.

**Comment by aelij** [comment]
Sure, sounds like a nice feature :)

Here are some details. RP processes use stdout to communicate with the parent process.
* Create a new `ProgressResultObject` that would contain the progress data (see `InputReadRequest` for an example)
* In `JsonConsoleDumper` add a method called `DumpProgress` that creates the result object by manually creating its JSON representation (see `DumpExceptionResultObject` for an example). You will also need to add the method to the `IConsoleDumper` interface, and throw a `NotSupportedException` in `DirectConsoleDumper`.
* In the `Helpers` class add public a method `ReportProgress(double? progress)` and an internal event `Action<double?> Progress` (a `null` value would hide the progress)
* In `RuntimeInitializer.AttachConsole` consume the `Helpers.Progress` event and call `consoleDumper.DumpProgress` (inside the `SupportsRedirect` if block)
* In `ExecutionHost`, read the `ProgressResultObject` in `ReadObjectProcessStream` and fire an event `ProgressChanged`
* Consume this event in `OpenDocumentViewModel` and set its value to a bindable property `ReportedProgress` . Also make sure the property value is reset to `null` at the beginning and end of each run (`Run` method).
* Add a progress bar to the toolbar in `DocumentView` (last item) and bind the `ReportedProgress` property's value to it. Make sure it is collapsed when the value is `null`.
