### ISSUE TITLE
Automatic context support

### ISSUE THREAD

**Issue by BillShawn** [aelij/RoslynPad#323]
I have a class
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Net.Sockets;
using System.Text;
using MVision.Core;
using DrawTools;
using HalconTools.Find;

namespace App
{

    #region Auto Code
    partial class MVScript
    {
    	const string @TL_In_Flag = "Flag";
    	const string @TL_In_Image = "Image";
    	const string @TL_MVImageConvert_0 = "MVImageConvert_0";
    	const string @TL_MVPatternMatchTool_0 = "MVPatternMatchTool_0";
    	const string @TL_MVUpdateFixtrueTool_0 = "MVUpdateFixtrueTool_0";
    	const string @TL_MVFindCircleTool_0 = "MVFindCircleTool_0";
    	const string @TL_MVDrawStringTool_0 = "MVDrawStringTool_0";
    	const string @TL_Out_OK0 = "OK0";
    	const string @TL_Out_X0 = "X0";
    	const string @TL_Out_Z0 = "Z0";
    	const string @TL_Out_Code = "Code";
    
    }
    #endregion

    public partial class MVScript : MVScriptBase  //类名MVScript与继承关系不可改
    {
        public override void Init()
        {
            
        }

        public override void Run()
        {
            
        }

    }
}

code region 'Auto Code' is generated through a click event, but this is very likely to change or be artificially modified. I would like to hide this part and let it be generated automatically in the background, but I don’t know how to modify it to achieve this，i need help,please

**Comment by aelij** [comment]
How is this related to RoslynPad?

**Comment by BillShawn** [comment]
First of all, thank you very much for your reply.
The code is automatically generated by secondary development using the RoslynCodeEditor control. I used another online compilation tool before, which supports hiding some code (Github: NRefactory-Completion-Sample), but it is not as powerful as RoslynPad, I like it The tool you provided, but I also want to continue to implement the function of hiding part of the code (mainly hidden fields, these fields are automatically generated), I do n’t know where to modify to make RoslynPad's repair and error identification functions work normally , I need to suggest, whether it is to modify part of the code of RoslynPad or to replace the hidden part of the code with other methods; At present, I use the button click event to automatically generate the code and update it to the RoslynCodeEditor control, but this is risky for me. .
Looking forward to any suggestions, thank you

**Comment by aelij** [comment]
Sorry, I don't have an idea how this can be done, but maybe the folks in the AvalonEdit (which `RoslynCodeEditor` is based on) repo would.

**Comment by aelij** [comment]
Oh, you could load the generated code as an additional document into Roslyn's `Project` object instead of placing it inside the editor. That could work.

**Comment by BillShawn** [comment]
感谢您的回复
在您给出这个附加文档的建议之后，我立即开始尝试，我使用了 RoslynHost.AddDocument(DocumentCreationArgs args)方法尝试加入附加文档，但可惜 并没有感知到附加文档的内的常量内容，我缺少哪些步骤呢？

**Comment by BillShawn** [comment]
thank you for your reply
After you suggested this additional document, I immediately tried it. I used the RoslynHost.AddDocument (DocumentCreationArgs args) method to try to add the additional document, but unfortunately I didn't perceive the constant content of the additional document. What steps am I missing?
