### ISSUE TITLE
Font Size changes not propagating to the output window or tree.

### ISSUE THREAD

**Issue by MarqueIV** [aelij/RoslynPad#326]
I already have code changes for this but I haven't created a PR as I'm not sure you'd agree with this change. BUT... there needs to be *some* way to change the font size of the document tree as well as the output window.  Currently, in my build I have them synced so when you change the slider, all three change, but I could see people not liking that.  At a minimum, there should be some basic settings pane that lets me change that font.

Lemme know if you're ok with the one-slider-to-rule-them-all approach and if so, I'll submit the PR for it.

Windows, latest build.

**Comment by aelij** [comment]
Sorry but I won't accept this change. No editor works like that.

Font sizes are system default so you could change those settings or increase the DPI.

**Comment by MarqueIV** [comment]
Um... Visual Studio Code does exactly that!  Your code and project tree's fonts all change together when you change the font size.

Even if you disagree with them all changing together (which I can understand), Visual Studio 2019 proper lets you [change the environment font](https://stackoverflow.com/questions/23126548/how-do-i-change-the-font-size-of-solution-explorer-in-visual-studio) which is what covers the solution explorer, which is synonymous with your file tree.

Like I said though, I do understand you not wanting them to change all together, but it would be nice to be able to at least set the environment font in some settings pane somewhere.

Speaking of fonts, it would also be good to let us type in an exact font down at the bottom rather than relying on dragging a slider.  Just a usability quip.
