### ISSUE TITLE
Support for net framework 4.7

### ISSUE THREAD

**Issue by sridharbaldava** [aelij/RoslynPad#328]
I was wondering if you were planning to build this for .net framework 4.7 or 4.6 is the last version you want to build for full framework? Also would it be possible to add option to run code against different full framework versions?

**Comment by aelij** [comment]
No, RoslynPad will only be built for .NET Core from now on. The NuGet packages will be multi-targeted though. And of course you can still run .NET Framework scripts.

As for different framework versions, it would require targeting packs and I don't want to rely on them being installed. Unlike .NET Core, only one version of .NET Framework can actually be installed on a machine.
