### ISSUE TITLE
Allow users to set the font size of the document tree and output window

### ISSUE THREAD

**Issue by MarqueIV** [aelij/RoslynPad#330]
I'm reposting a variant of issue #326 since that one was closed.  Specifically, there should be a way to let the user specify the font size of the document tree as well as the output window.  Contrary to your comments there, both Visual Studio and Visual Studio Code let the user adjust that font size.  Neither make you have to rely on changing your system's default font size, nor should they.

- In the case of Visual Studio, it is achieved by setting the 'Environment Font' in the settings which controls everything except the code windows.
- In the case of Visual Studio Code, zooming in/enlarging the font enlarges all fonts equally.

For high-res screens, the current design makes it very difficult to read that output.

It is a simple matter to allow the user to specify this font size. It can be achieved via a user option.  In a perfect world, these would be your three options.

1. Track System Font - This would work as it does presently.
2. Track Editor Font - This would simply track whatever size the editor is using and applies that
3. User-Specified - This is a value you specify in preferences that acts independently of either the system, or the editor size.

I am more than willing to provide a PR that would add the above functionality, but in your other comment, you said you would reject the change I proposed there, so before I do this, I would like to get buy-in from you.  Let me know and if so, I'll put it together over the next few days.

**Comment by aelij** [comment]
I'm always on the fence with adding more options, as RP is just on the brink of having a setting screen, which I've strived to avoid :)

I'd accept a PR adding a `int? EnvironmentFontSize` setting which would be bound to the main Window.FontSize property. For now, let's not add a UI for it. Even VS Code took its time with a visual settings editor.

**Comment by MarqueIV** [comment]
Completely fine without creating a UI. As long as there’s a way to change it, I don’t mind editing a separate file. That said, I didn’t know there was a separate file. Can you point me in the direction of where it is and I’ll create the PR.
