### ISSUE TITLE
Stop automatic formatting of document on uncomment (or any other time)

### ISSUE THREAD

**Issue by MarqueIV** [aelij/RoslynPad#331]
When you comment out some code, the code comments as you would expect.  However, when you uncomment that code again, RoslynPad decides it needs to re-format your entire document.  This is unexpected, and unwanted behavior.  It requires you to take the additional step of undoing the last command (the formatting) any time you uncomment code.

Formatting should not ever be an automatically-applied thing, especially without the ability to customize the rules of formatting.  If you want it bound to a keyboard shortcut or toolbar button or similar, that is fine, but it should never make the assumption that's what a person wants unless they have explicitly stated as much.

Please disable this auto-formatting action when uncommenting code.  Let us apply formatting when and where we want.  Do not make that decision for us.

**Comment by aelij** [comment]
Thanks for the suggestion but RP is meant for "quick and dirty" coding and IMO this setting is more convenient most of the time.

If you want to contribute a PR, I'd accept an app setting `FormatDocumentOnComment` to disable it (without adding a UI button for this option).

**Comment by MarqueIV** [comment]
I would make the argument because it’s quick and dirty you should not make assumptions like applying formatting because it’s no longer quick if we have to constantly undo what the editor is doing. 

How we use it is when we’re trying to figure out some code or some logic to something without having to build and compile our entire application. For instance i just used it to figure out how to do a custom Json converter that had some complex logic. But the goal is ultimately to get that code back in the main app so having it touch our code in ways we don’t want is frustrating. After all if we want to format it, give us a keyboard shortcut. But don’t make those assumptions for us.

I will happily add a PR if you can show me And example of where you would like the settings stored. Editing a separate file like VS code is completely fine. As long as we have the ability to do it.

**Comment by aelij** [comment]
The settings are in the `IAppSettings` interface and implementation. You can see there where it's saved (depends on platform).
