### ISSUE TITLE
How to update assembly references while running RoslynCodeEditor?

### ISSUE THREAD

**Issue by kmubunye** [aelij/RoslynPad#332]
How do I add external reference assemblies while running RoslyncodeEditor.

I created a WPF application and I referenced assemblies using the code below for IntelliSense

RoslynHost = new RoslynHost(additionalAssemblies: new[]
                {
                    Assembly.Load(@"RoslynPad.Roslyn.Windows"),
                    Assembly.Load(@"RoslynPad.Editor.Windows")
                },
                references: RoslynHostReferences.Default.With(typeNamespaceImports: new[]
                {
                    typeof(ScriptMetadataService),
                    typeof(ScriptPicklistMetadataService),
                    typeof(XmlDocument)
                })
            );

How do I add external assemblies during the runtime in the Roslyn code editor without creating a new instance of Roslynhost. I want to be able to get IntelliSense for external reference assemblies?

**Comment by nluyan** [comment]
I have the same question.

**Comment by sridharbaldava** [comment]
You can change add as many assemblies as you like by using typeof
```c#
RoslynHost = new RoslynHost(additionalAssemblies: new[]
{
typeof(XmlDocument).Assembly,
Assembly.Load(@"RoslynPad.Roslyn.Windows"),
Assembly.Load(@"RoslynPad.Editor.Windows")
},
references: RoslynHostReferences.Default.With(typeNamespaceImports: new[]
{
typeof(ScriptMetadataService),
typeof(ScriptPicklistMetadataService),
typeof(XmlDocument)
})
);
```

**Comment by aelij** [comment]
> How do I add external assemblies during the runtime in the Roslyn code editor without creating a new instance of Roslynhost. I want to be able to get IntelliSense for external reference assemblies?

If you want to add references to an existing document, you can:
* Use `#r "/path/to/assembly.dll"`
* Use `RoslynHost.UpdateDocument` to update the compilation. For example, this is how a rename works:
   https://github.com/aelij/RoslynPad/blob/7487233eef297e8cf43c74005085a57c878d4bba/src/RoslynPad.Common.UI/ViewModels/OpenDocumentViewModel.cs#L345-L348
   In your case you'd need to update the `Project` with new `MetadataReferences`, then get the `Document` back from the updated project and use it in  `UpdateDocument`. Note all Roslyn objects are immutable, so each operation creates a new tree.
