### ISSUE TITLE
Build

### ISSUE THREAD

**Issue by AltGI** [aelij/RoslynPad#333]
I'm using the current public release of this app and I would like to build from sources.

This is what I get

> 1>------ Build started: Project: RoslynPad.Roslyn, Configuration: Debug Any CPU ------
> 2>------ Build started: Project: RoslynPad.Runtime, Configuration: Debug Any CPU ------
> 1>CodeFixes\CodeFixService.cs(660,52,660,77): error CS0246: The type or namespace name 'IConfigurationFixProvider' could not be found (are you missing a using directive or an assembly reference?)
> 1>CodeFixes\CodeFixService.cs(659,82,659,107): error CS0246: The type or namespace name 'IConfigurationFixProvider' could not be found (are you missing a using directive or an assembly reference?)
> 1>CodeFixes\CodeFixService.cs(74,84,74,109): error CS0246: The type or namespace name 'IConfigurationFixProvider' could not be found (are you missing a using directive or an assembly reference?)
> 1>CodeFixes\CodeFixService.cs(82,46,82,71): error CS0246: The type or namespace name 'IConfigurationFixProvider' could not be found (are you missing a using directive or an assembly reference?)
> 1>Done building project "RoslynPad.Roslyn.csproj" -- FAILED.
> 3>------ Build started: Project: RoslynPad.Roslyn.Windows, Configuration: Debug Any CPU ------
> 2>RoslynPad.Runtime -> D:\Sources\Roslynpad\src\RoslynPad.Runtime\bin\Debug\netstandard2.0\RoslynPad.Runtime.dll
> 4>------ Build started: Project: RoslynPad.Build, Configuration: Debug Any CPU ------
> 3>RoslynPad.Roslyn.Windows -> D:\Sources\Roslynpad\src\RoslynPad.Roslyn.Windows\bin\Debug\netcoreapp3.1\RoslynPad.Roslyn.Windows.dll
> 4>ExecutionHost.cs(103,113,103,125): error CS1061: 'IRoslynHost' does not contain a definition for 'ParseOptions' and no accessible extension method 'ParseOptions' accepting a first argument of type 'IRoslynHost' could be found (are you missing a using directive or an assembly reference?)
> 4>ExecutionHost.cs(228,49,228,61): error CS1061: 'IRoslynHost' does not contain a definition for 'ParseOptions' and no accessible extension method 'ParseOptions' accepting a first argument of type 'IRoslynHost' could be found (are you missing a using directive or an assembly reference?)
> 4>ExecutionHost.cs(341,58,341,70): error CS1061: 'IRoslynHost' does not contain a definition for 'ParseOptions' and no accessible extension method 'ParseOptions' accepting a first argument of type 'IRoslynHost' could be found (are you missing a using directive or an assembly reference?)
> 4>ExecutionHost.cs(368,62,368,74): error CS1061: 'IRoslynHost' does not contain a definition for 'ParseOptions' and no accessible extension method 'ParseOptions' accepting a first argument of type 'IRoslynHost' could be found (are you missing a using directive or an assembly reference?)
> 4>ExecutionHost.cs(490,50,490,73): error CS1061: 'IRoslynHost' does not contain a definition for 'CreateMetadataReference' and no accessible extension method 'CreateMetadataReference' accepting a first argument of type 'IRoslynHost' could be found (are you missing a using directive or an assembly reference?)
> 4>Done building project "RoslynPad.Build.csproj" -- FAILED.
> 5>------ Build started: Project: RoslynPad.Common.UI, Configuration: Debug Any CPU ------
> 3>RoslynPad.Roslyn.Windows -> D:\Sources\Roslynpad\src\RoslynPad.Roslyn.Windows\bin\Debug\net462\RoslynPad.Roslyn.Windows.dll
> 6>------ Build started: Project: RoslynPad.Editor.Windows, Configuration: Debug Any CPU ------
> 5>CSC : error CS0006: Metadata file 'D:\Sources\Roslynpad\src\RoslynPad.Build\bin\Debug\netcoreapp3.1\RoslynPad.Build.dll' could not be found
> 5>Done building project "RoslynPad.Common.UI.csproj" -- FAILED.
> 6>RoslynPad.Editor.Windows -> D:\Sources\Roslynpad\src\RoslynPad.Editor.Windows\bin\Debug\net462\RoslynPad.Editor.Windows.dll
> 6>RoslynPad.Editor.Windows -> D:\Sources\Roslynpad\src\RoslynPad.Editor.Windows\bin\Debug\netcoreapp3.1\RoslynPad.Editor.Windows.dll
> 7>------ Build started: Project: RoslynPad, Configuration: Debug Any CPU ------
> 7>D:\Sources\Roslynpad\src\RoslynPad\DocumentTreeView.xaml(20,126): error MC3066: The type reference cannot find a public type named 'DocumentViewModel'. Line 20 Position 126.
> 7>D:\Sources\Roslynpad\src\RoslynPad\DocumentView.xaml(132,88): error MC3066: The type reference cannot find a public type named 'OpenDocumentViewModel'. Line 132 Position 88.
> 7>D:\Sources\Roslynpad\src\RoslynPad\MainWindow.xaml(31,68): error MC3066: The type reference cannot find a public type named 'OpenDocumentViewModel'. Line 31 Position 68.
> 7>Done building project "RoslynPad.csproj" -- FAILED.
> ========== Build: 3 succeeded, 4 failed, 0 up-to-date, 0 skipped ==========

Looks like some of the MS code has been changed to internal, How can I build the latest ?

Thanks

**Comment by aelij** [comment]
The Roslyn code has always been internal. I'm using my [IgnoresAccessChecksToGenerator](https://github.com/aelij/IgnoresAccessChecksToGenerator) to be able to compile it.

The build is passing in GitHub Actions, so it's hard to tell what went wrong on your machine... :) So my best advice is - check you're using the latest VS, clone again and retry.

**Comment by AltGI** [comment]
Hi, thanks for your answer. 

I finally found the issue. 

I had 2 different versions of Microsoft.CodeAnalysis.Workspaces.Common nugget package (3.1.0 and 3.4.0) installed on my computer.

MSBuild was using the 3.4.0 but the IgnoresAccessChecksToGenerator was "publicizing" the 3.1.0 library.

I works without quirks after deleting the old one.

Thanks for giving me a clue.
