### ISSUE TITLE
Editor doesn't accept new `using` syntax in .net core 3

### ISSUE THREAD

**Issue by TuyenTk** [aelij/RoslynPad#334]
**Describe the bug**
Editor doesn't accept new `using` syntax in .net core 3

**To Reproduce**

```csharp
#r "nuget:Microsoft.Data.SqlClient/1.1.1"

using Microsoft.Data.SqlClient;

var count = 0;

using var conn = new SqlConnection("*********************");
conn.Open();

var command = new SqlCommand("Select [Id], [Name] from Table Where [DateCreated] > @dateCreated", conn);
command.Parameters.AddWithValue("@dateCreated", DateTime.UtcNow.AddMinutes(-30));
// int result = command.ExecuteNonQuery();

using var reader = command.ExecuteReader();
while (reader.Read())
{
    count++;
    Console.WriteLine($"{count}. {reader["Name"]}");
}

Console.WriteLine($"Finish read {count} rows");
```
Screenshot:

![image](https://user-images.githubusercontent.com/4112561/75753267-55eba800-5d22-11ea-880f-5de61fddc5b3.png)

**Expected behavior**
Editor should see the code as valid

**Version**
- OS: Windows Pro 1909
- Build (or commit ID if built from source): 1dc77f5d939fb19e505879cceba4c565fd137d49

**Comment by aelij** [comment]
This is a limitation of the Roslyn Script language kind. Since top-level variables are translated into class **fields**, they cannot be disposed this way.

You can place a variable in a scope (e.g. `if` or any curlies) which would make it a real variable, where the syntax works. For example:

```cs
{
   using var reader = command.ExecuteReader();
}
```
