### ISSUE TITLE
Unable to run .NET Core 3.x.x code

### ISSUE THREAD

**Issue by Guris** [aelij/RoslynPad#338]
When any file is opened or new is created in RoslynPad, default framework is set to *Core x64* and selected version is 3.1.3.
When I try tu run the code I get the following output:

![image](https://user-images.githubusercontent.com/1776912/78867738-e1530a00-7a41-11ea-9443-1cc10e6e0e0f.png)

Framework is installed within SDK 3.1.201 and I use it with VS2019 to build and run .NET Core apps on daily basis.

Running code with *Core x64 2.x.x (2.2.7)* or *Desktop x64* profile works.
When switched to 2.2.7 and back to 3.x.x errors in code stop showing but running the app results in different error:
![image](https://user-images.githubusercontent.com/1776912/78869765-5ecc4980-7a45-11ea-88d2-160152387169.png)

**Version**
- OS: Windows 10 Enterprise 10.0.18363 Build 18363
- Build: 14.1 downloaded from roslynpad.net main site

**Comment by aelij** [comment]
.NET Core 3.x is only supported in v15 (not released yet). For now you can build from sources.

**Comment by Guris** [comment]
1. .NET Core 3.x should not be set as default framework in 14.1 version. It should not be on the list then.
2. I used to build from sources. But now it's broken - some Pythia references in *RoslynPad.Roslyn* project I'm unable to solve. (The type or namespace name 'Pythia' does not exist in the namespace 'Microsoft.CodeAnalysis.ExternalAccess' (are you missing an assembly reference?)) Any help with this please?

**Comment by aelij** [comment]
> .NET Core 3.x should not be set as default framework in 14.1 version. It should not be on the list then.

Hindsight is 20/20 ;) I could not foresee it would not work. That's why in v15 I'm using MSBuild to resolve references.
