### ISSUE TITLE
Can't seem to build latest source using VS2019

### ISSUE THREAD

**Issue by redoz** [aelij/RoslynPad#339]
**Describe the bug**

I pulled the source (from master), opened the sln file in VS2019 16.5.4 with the latest SDK 3.1.201 and try to compile, I get errors saying it can't find ```IPythiaSignatureHelpProviderImplementation``` as well as ```IHostDiagnosticAnalyzerPackageProvider```. 

Not sure if I'm missing some dependency but I didn't see anything extra in the readme at least.

**Version**
- OS:
Windows 10 (10.0.18363.778)
- Build (or commit ID if built from source):
e8b11bb86eaa38b5e8e1c4a69c48ab26eefb202c

**Comment by david-beckman** [comment]
@redoz I was able to successfully compile both on the command line and in VS2019. I am also on the latest SDK (3.1.201) and VS2019 (16.5.4). All I get are two warnings:
```
C:\Program Files\dotnet\sdk\3.1.201\Microsoft.Common.CurrentVersion.targets(2081,5): warning MSB3277: Found conflicts between different versions of "System.Drawing.Common" that could not be resolved.  These reference conflicts are listed in the build log when log verbosity is set to detailed. [C:\...\RoslynPad\src\RoslynPad.Avalonia\RoslynPad.Avalonia.csproj]
C:\Program Files\dotnet\sdk\3.1.201\Microsoft.Common.CurrentVersion.targets(2081,5): warning MSB3277: Found conflicts between different versions of "System.Security.Cryptography.ProtectedData" that could not be resolved.  These reference conflicts are listed in the build log when log verbosity is set to detailed. [C:\...\RoslynPad\src\RoslynPad.Avalonia\RoslynPad.Avalonia.csproj]
```
Note that there are a few references in project files to NET461 and NET462. I also have the SDKs for those installed, but I don't think those would apply from the command line. Are you able to build via the command line, or do you get the same failure from both CLI & VS2019?

**Comment by aelij** [comment]
The CI build is working, so it must be something on your machine. Try building in a clean env.

**Comment by redoz** [comment]
Yeah indeed, it seems to have fixed itself in the last week or so, maybe a VS update, so I guess it was just my machine. Sorry about the noise.
