### ISSUE TITLE
Linq error

### ISSUE THREAD

**Issue by josago97** [aelij/RoslynPad#344]
**Describe the bug**
Not all of the alleged items in the collection are printing

**To Reproduce**
Execute this code:
`Enumerable.Range(5, 1)
.SelectMany(n => Enumerable.Range(1, n))
.ToList().ForEach(Console.WriteLine);`

The console sometimes show: 1, 2, 3

![image](https://user-images.githubusercontent.com/26380095/83706248-488ed400-a617-11ea-9a72-9d7ffa91fca9.png)

**Expected behavior**
The console should show: 1, 2, 3, 4, 5

**Version**
- OS: Windows 10
- Build (or commit ID if built from source): RoslynPad 14.1

**Comment by aelij** [comment]
Duplicate of #253 (fixed in master)
