### ISSUE TITLE
A build does not overwrite same-name assembly with conflicting nuget packages.

### ISSUE THREAD

**Issue by atillabyte** [aelij/RoslynPad#348]
**Describe the bug**
If I install a separate package whose assembly shares the same name as a previously installed but dereferenced nuget package, the old assembly remains in the build directory, and is not overwritten by the new assembly which causes a runtime exception specifying that the assemblies do not match.

**To Reproduce**
Install Venture from nuget, reference PlayerIOClient with '#r' and build. Remove reference and install PlayerIOClient-Signed, reference PlayerIOClient and build. When debugging, an exception is raised.

**Expected behavior**
The unreferenced assembly should be removed from the build folder and replaced with the assembly which is referenced.

**Version**
- OS: Windows 8.1
- Build (or commit ID if built from source):

**Comment by aelij** [comment]
Can you provide a full sample with code?

**Comment by atillabyte** [comment]
Source:
```csharp
using PlayerIOClient;

//var client = PlayerIO.SimpleConnect("everybody-edits-su9rn58o40itdbnw69plyw", "guest", "guest", "simpleUsers"); // Venture
//var client = PlayerIO.QuickConnect.SimpleConnect("everybody-edits-su9rn58o40itdbnw69plyw", "guest", "guest", null); // PlayerIOClient-Signed

Console.WriteLine(client.ConnectUserId);
```
Video demonstration: https://streamable.com/v3x2sy

**Comment by aelij** [comment]
Can you add the nuget references `#r`?

**Comment by atillabyte** [comment]
```csharp
#r "nuget:Venture/1.7.2"
#r "nuget:PlayerIOClient-Signed/3.5.2"
```

**Comment by aelij** [comment]
Seems to be working in `master`. Which build are you using?

**Comment by aelij** [comment]
Oh, I see in the video. 14.1's build works quite differently. Try building v15 from master.
