### ISSUE TITLE
Support .Net Core 3.1 LTS

### ISSUE THREAD

**Issue by TheKitro** [aelij/RoslynPad#349]
**Describe the bug**
Hi .Net Core 3.1 is published a while ago. I use it in all my new Tools. It have LTS Support.
But in Roslynpad I get always Errors, when I try to use it in my Roslynpad scripts.

**To Reproduce**
Install .Net Core 3.1 and start Roslynpad.

**Expected behavior**
Support for .Net Core 3.1 LTS

**Version**
- OS: Windows 10
- Build (or commit ID if built from source):

Is there an estimated time, for publishing next Version?

**Comment by aelij** [comment]
.NET Core 3 is supported in master (you can clone the repo and build). I need to stabilize it a bit before releasing.
