### ISSUE TITLE
Unicode characters are not supported in Results Window

### ISSUE THREAD

**Issue by ycherkes** [aelij/RoslynPad#356]
Results window doesn't show correct Unicode characters for non-English strings:

![image](https://user-images.githubusercontent.com/13467759/88792604-25f6e280-d1a4-11ea-8cc0-3e0a11a7ea57.png)

**Comment by aelij** [comment]
## Please do not ignore the issue template.

Which version is this?

**Comment by ycherkes** [comment]
14.1. Just tried it in v15 - all works fine.

**Comment by ycherkes** [comment]
Does v15 exist in Microsoft Store?

**Comment by aelij** [comment]
It will take some time. Meanwhile you can download the release here.
