### ISSUE TITLE
Open File support for wildcard(*.*) extension

### ISSUE THREAD

**Issue by TheKitro** [aelij/RoslynPad#359]
Roslynpad support to open files with the extension *.csx
I use Roslynpad on my *.cs files and sometimes other files with included C# Code.

If I click on "Open File" I only found *.csx Files.

Please can you extend the Extension Selector for further extensions like: "*.cs","*.linq" and "*.*".
If "*.csx" is the default extension that's fine, but I want to be able to choose other extensions as well.

Best Regards Kitro

**Comment by aelij** [comment]
RoslynPad currently only supports the .csx format. .cs files can have namespaces, which are not supported in the script variant of C#. So I will keep the current filter.

FYI, if you want to change the default filter in any Windows file dialog, you can just type `*.*` and press Enter, it will then allow you to select any file.
