### ISSUE TITLE
cs files are compiled in the same project

### ISSUE THREAD

**Issue by BillShawn** [aelij/RoslynPad#362]
Roslyn Pad 14.1
i add a method in RoslynHost.cs ,code is 

        private DocumentId ProjectAddDocument(RoslynWorkspace workspace, Project project, DocumentCreationArgs args, string documentName, Document? previousDocument = null)
        {
            var document = CreateDocument(project, args);
            var documentId = document.Id;
            workspace.SetCurrentSolution(document.Project.Solution);
            workspace.OpenDocument(documentId, args.SourceTextContainer);

            _workspaces.TryAdd(documentId, workspace);

            if (args.OnDiagnosticsUpdated != null)
            {
                _diagnosticsUpdatedNotifiers.TryAdd(documentId, args.OnDiagnosticsUpdated);
            }

            var onTextUpdated = args.OnTextUpdated;
            if (onTextUpdated != null)
            {
                workspace.ApplyingTextChange += (d, s) =>
                {
                    if (documentId == d) onTextUpdated(s);
                };
            }

            return documentId;
        }
        
and i add a new method in RoslynCodeEditor.cs , code is 
public DocumentId Initialize(IRoslynHost roslynHost, Project project, IClassificationHighlightColors highlightColors, string workingDirectory,string documentName, string documentText)
        {
            _roslynHost = roslynHost ?? throw new ArgumentNullException(nameof(roslynHost));
            _classificationHighlightColors = highlightColors ?? throw new ArgumentNullException(nameof(highlightColors));

            _braceMatcherHighlighter = new BraceMatcherHighlightRenderer(TextArea.TextView, _classificationHighlightColors);

            _quickInfoProvider = _roslynHost.GetService<IQuickInfoProvider>();
            _braceMatchingService = _roslynHost.GetService<IBraceMatchingService>();
            _braceCompletionProvider = _roslynHost.GetService<IBraceCompletionProvider>();

            var avalonEditTextContainer = new AvalonEditTextContainer(Document) { Editor = this };

            var creatingDocumentArgs = new CreatingDocumentEventArgs(avalonEditTextContainer, ProcessDiagnostics);
            OnCreatingDocument(creatingDocumentArgs);

            _documentId = creatingDocumentArgs.DocumentId ??
                roslynHost.ProjectAddDocument(project, new DocumentCreationArgs(avalonEditTextContainer, workingDirectory,
                    args => ProcessDiagnostics(args), text => avalonEditTextContainer.UpdateText(text)),documentName);

            AppendText(documentText);
            Document.UndoStack.ClearAll();
            AsyncToolTipRequest = OnAsyncToolTipRequest;

            RefreshHighlighting();

            _contextActionsRenderer = new ContextActionsRenderer(this, _textMarkerService) { IconImage = ContextActionsIcon };
            _contextActionsRenderer.Providers.Add(new RoslynContextActionProvider(_documentId, _roslynHost));

            var completionProvider = new RoslynCodeEditorCompletionProvider(_documentId, _roslynHost);
            completionProvider.Warmup();

            CompletionProvider = completionProvider;

            return _documentId;
        }

the issue is it works normally when only one cs file is added,but more than one cs file is added, only the last file can work normally.   How can I modify to achieve the purpose of my title

**Comment by aelij** [comment]
Sorry but I don't understand what you're trying to achieve. An editor can work with one file.
