### ISSUE TITLE
dotnet RoslynPad.dll not working on MacOS

### ISSUE THREAD

**Issue by ibrahim-erx** [aelij/RoslynPad#367]
**Describe the bug**
Following is the result of running `dotnet RoslynPad.dll` as mentioned in Readme
```
It was not possible to find any compatible framework version
The framework 'Microsoft.WindowsDesktop.App', version '3.1.0' was not found.
  - No frameworks were found.

You can resolve the problem by installing the specified framework and/or SDK.

The specified framework can be found at:
  - https://aka.ms/dotnet-core-applaunch?framework=Microsoft.WindowsDesktop.App&framework_version=3.1.0&arch=x64&rid=osx.10.15-x64
```

**To Reproduce**
1. Download latest release and unzip
2. `dotnet RoslynPad.dll`

**Expected behavior**
Start RoslynPad

**Version**
- OS: Mac OS Catalina 10.15.7 (19H2)
- Build (or commit ID if built from source): Not built from source. Downloaded release

**Comment by aelij** [comment]
The latest release doesn't have the xplat version yet (see #366). As per the instructions in the readme, you need to download `RoslynPadNetCore.zip`.
