### ISSUE TITLE
Make the update availability notification clearer

### ISSUE THREAD

**Issue by ohadschn** [aelij/RoslynPad#37]
Most programs just pop up a message box, but I'm assuming you didn't go that route intentionally.
However I think the current notification at the bottom right is too easy to miss. 
I think a message box only at the first sight of an update (or at most one message box per new version) would make sense, mentioning that if you don't want to update now you can do so via the bottom-right update button (probably have a small screenshot of it in the message box to clarify).

**Comment by aelij** [comment]
I dislike "in your face" update notifications. VS is doing a great job there, and I took a cue from it. Maybe I can add some text that would make it more apparent an update is available.

**Comment by ohadschn** [comment]
I feel that it's much more noticeable in VS:

- The button is at the top
- The button is bigger
- The button is highlighted

Adding some text would also be a good idea, possibly a number indicating the number of new versions released since the last update (something like Bootstrap's badges).

**Comment by aelij** [comment]
Maybe moving it to the top and highlighting it would be better. I'll consider it.

BTW, there was actually a suggestion for extensibility (#24) but that's very low on my priority list right now.

**Comment by aelij** [comment]
What do you think?

![update](https://cloud.githubusercontent.com/assets/496737/17614546/e6ca4e98-606f-11e6-866c-0b5a861672cd.png)

**Comment by ohadschn** [comment]
Much better for sure, but I need to see how noticeable it is when maximized. Will probably be even more noticeable at the top.

**Comment by aelij** [comment]
Let's try the bottom first. Putting it on the top would require either: pushing everything down - or - drawing in the non-client area (which can be quite a hassle).
