### ISSUE TITLE
Exception: The type '...' exists in both

### ISSUE THREAD

**Issue by mshakurov** [aelij/RoslynPad#371]
Windows 10 x64
RoslynPad 15.1 (downloaded from roslynpad.net)

1. Open RoslynPad 15.1
3. Create new document
3. Switch selector to .Net Framework x64 (or x32)
4. Enter code:

#r "System.Windows.Forms"
using System.Windows.Forms;
try
{
}
catch (Exception ex)
{
}

You will get an error like this:
CS0433: The type 'Exception' exists in both 'System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e' and 'mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'

What am I doing wrong?

**Comment by mshakurov** [comment]
Oh, I got it! if multiple platforms (.NET Standard, .NET Core, and .NET Framework) are installed on the machine, then the above problem occurs.
Is it possible to somehow get around this problem?

**Comment by aelij** [comment]
I'm not sure why this happens, it used to work :) I will investigate when I find some time.

**Comment by mshakurov** [comment]
> I'm not sure why this happens, it used to work :) I will investigate when I find some time.

_off topic: I'm in no hurry, I'm comfortable with version 14.1. I, and probably all of us, are already very grateful to you for your work! It is a very lightweight and fully functional "urgent" tool, very useful at work. If you will selling a license on the cheap, many will spare no expense. Other analogues are either too expensive and heavy or not so functional._
