### ISSUE TITLE
Styleing completionwindow

### ISSUE THREAD

**Issue by JanTamis** [aelij/RoslynPad#377]
After trying to set the style of the CustomCompletionWindow i found out this cant be done because it is a private class.

**Describe the solution you'd like**
Convert the private CustomCompletionWindow class to a public class so it can be styled.

**Describe alternatives you've considered**
A property can be added to set the style of the completion window.

**Comment by aelij** [comment]
`CustomCompletionWindow` inherits from `CompletionWindow` and doesn't change the style key, so you could use the base class to style it.
