### ISSUE TITLE
Unhandled Exception when click `Report a problem...`

### ISSUE THREAD

**Issue by cupsos** [aelij/RoslynPad#378]
**Describe the bug**

![RoslynReportException](https://user-images.githubusercontent.com/24942851/100056517-21e48400-2e69-11eb-8167-eddffddaf2b5.gif)

Default value of `ProcessStartInfo.UseShellExecute` is changed to `false` on .NET Core. [.NET Docs](https://docs.microsoft.com/en-us/dotnet/api/system.diagnostics.processstartinfo.useshellexecute?view=net-5.0#definition)  

So i think this code in `src/RoslynPad.Common.UI/ViewModels/MainViewModelBase.cs`

```csharp
private static void ReportProblem()
{
    Task.Run(() => Process.Start("https://github.com/aelij/RoslynPad/issues"));
}
```

should be changed to

```csharp
private static void ReportProblem()
{
    Task.Run(() => Process.Start(
        new ProcessStartInfo
        {
            FileName = "https://github.com/aelij/RoslynPad/issues",
            UseShellExecute = true,
        }));
}
```

**To Reproduce**
Just click. Always happen.

**Expected behavior**
Open `https://github.com/aelij/RoslynPad/issues` by default web browser.

**Version**
- OS: Windows 10 20H2
- Build (or commit ID if built from source): v15.1

**Comment by aelij** [comment]
Fixed in #379
