### ISSUE TITLE
System.Object is not defined or imported

### ISSUE THREAD

**Issue by mjanulaitis** [aelij/RoslynPad#380]
The viewer highlights everything as an error.  On mouse over the System.Object is not defined or imported is displayed.

**Steps to Reproduce**
Create a new WPF project targeting .Net 4.8 then add the following NuGet components:

RoslynPad.Roslyn.Windows v3.6
RoslynPad.Editor.Windows v1.2

Add the following code:

.xaml
`
<Window x:Class="WpfApp1.MainWindow"
        xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
        xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
        xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
        xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
        xmlns:local="clr-namespace:WpfApp1"
        xmlns:editor="clr-namespace:RoslynPad.Editor;assembly=RoslynPad.Editor.Windows"
        mc:Ignorable="d"
        Title="MainWindow" Height="450" Width="800"
        >
    <Grid>
        <editor:RoslynCodeEditor  
                    x:Name="editor"                    
                    IsReadOnly="False"
                    HorizontalScrollBarVisibility="Auto"
                    VerticalScrollBarVisibility="Auto"
                    ShowLineNumbers="True"/>
    </Grid>
</Window>
`

.cs
`using System.IO;
using System.Reflection;
using System.Windows;
using RoslynPad.Editor;
using RoslynPad.Roslyn;

namespace WpfApp1
{
    public partial class MainWindow : Window
    {
        public MainWindow()
        {
            InitializeComponent();
            Loaded += MainWindow_Loaded;
        }

        private void MainWindow_Loaded(object sender, RoutedEventArgs e)
        {
            var _host = new RoslynHost(additionalAssemblies: new[]
                        {
                        Assembly.Load("RoslynPad.Roslyn.Windows"),
                        Assembly.Load("RoslynPad.Editor.Windows"),
                    });

            var workingDirectory = Directory.GetCurrentDirectory();
            var documentId = editor.Initialize(_host, new ClassificationHighlightColors(), workingDirectory, "");
        }
    }
}`

Finally build and run.  Once loaded paste the following code:
`
int a = 0;
`

**Expected behavior**
The code should not have any errors.

**Version**
- Windows 10:
- Listed above in the Nuget instructions.
![RoslynError](https://user-images.githubusercontent.com/11945074/102557418-5cb49300-4088-11eb-9db0-68d9ffdf9d5f.png)

**Comment by mmitti** [comment]
I faced same issue, but i resolved by adding RoslynHostReferences as same as following example.

https://github.com/aelij/RoslynPad/blob/f30fc0471975014ae10484dcbc81389734847543/samples/RoslynPadReplSample/MainWindow.xaml.cs#L43-L53

**Comment by aelij** [comment]
As @mmitti indicated, you need to add references. See the sample.
