### ISSUE TITLE
add file extensions to the #load option

### ISSUE THREAD

**Issue by kerenayal** [aelij/RoslynPad#381]
Hi Eli,
I'm trying to use #load to load a specific self made C# file with a different extension,
I was trying to look for where to add this one to the available options but didn't find any.

Also,
Loading file can only work with the full path, used to work with the older AvalonEdit and Rosyln and it supports relative path.
Is there any way I can do something to enable the relative path?

Any help would be appreciated.
Thanks.

**Comment by aelij** [comment]
I'm not sure what you mean by file extension. It should work with any file name.
And relative path works after you save the document.
