### ISSUE TITLE
Can not Compile with VS2019 and Win10 64bit

### ISSUE THREAD

**Issue by feilongsword** [aelij/RoslynPad#386]
**Describe the bug**
Severity	Code	Description	Project	File	Line	Suppression State
Error	XDG0008	The name "MainViewModel" does not exist in the namespace "clr-namespace:RoslynPad.UI;assembly=RoslynPad.Common.UI".	RoslynPad	G:\projects\OpenSource\RoslynPad\src\RoslynPad\DocumentTreeView.xaml	10	
Error	XDG0062	A null or zero length string does not represent a valid Type.	RoslynPad	G:\projects\OpenSource\RoslynPad\src\RoslynPad\DocumentTreeView.xaml	10	
Error	XDG0008	The name "FilterCollectionViewConverter" does not exist in the namespace "clr-namespace:RoslynPad".	RoslynPad	G:\projects\OpenSource\RoslynPad\src\RoslynPad\DocumentTreeView.xaml	15	
Error	XDG0008	The name "DocumentViewModel" does not exist in the namespace "clr-namespace:RoslynPad.UI;assembly=RoslynPad.Common.UI".	RoslynPad	G:\projects\OpenSource\RoslynPad\src\RoslynPad\DocumentTreeView.xaml	19	
Error	XDG0062	A null or zero length string does not represent a valid Type.	RoslynPad	G:\projects\OpenSource\RoslynPad\src\RoslynPad\DocumentTreeView.xaml	19	
Error	XDG0062	The resource "FilterCollectionViewConverter" has an incompatible type.	RoslynPad	G:\projects\OpenSource\RoslynPad\src\RoslynPad\DocumentTreeView.xaml	20	
Error	XDG0008	The name "TreeListViewItem" does not exist in the namespace "clr-namespace:RoslynPad.Controls".	RoslynPad	G:\projects\OpenSource\RoslynPad\src\RoslynPad\DocumentTreeView.xaml	48	
Error	XDG0062	A null or zero length string does not represent a valid Type.	RoslynPad	G:\projects\OpenSource\RoslynPad\src\RoslynPad\DocumentTreeView.xaml	48	
Error	XDG0008	The name "TreeListViewItem" does not exist in the namespace "clr-namespace:RoslynPad.Controls".	RoslynPad	G:\projects\OpenSource\RoslynPad\src\RoslynPad\DocumentTreeView.xaml	49	
Error	XDG0062	A null or zero length string does not represent a valid Type.	RoslynPad	G:\projects\OpenSource\RoslynPad\src\RoslynPad\DocumentTreeView.xaml	49	
Error	XDG0062	Key cannot be null. (Parameter 'key')	RoslynPad	G:\projects\OpenSource\RoslynPad\src\RoslynPad\DocumentTreeView.xaml	49	
Error	XDG0062	A null or zero length string does not represent a valid Type.	RoslynPad	G:\projects\OpenSource\RoslynPad\src\RoslynPad\DocumentTreeView.xaml	54	
Error	XDG0008	The name "TreeListView" does not exist in the namespace "clr-namespace:RoslynPad.Controls".	RoslynPad	G:\projects\OpenSource\RoslynPad\src\RoslynPad\DocumentTreeView.xaml	125	

**To Reproduce**
Build
**Expected behavior**
Compile Success
**Version**
- OS: Windows 10 64bit
Is there anything wrong? or anything else is needed before build?
I got .Net Core 3.1.402 installed and set sdk version to it in global.json.

**Comment by aelij** [comment]
Please include the entire build output in text, not screenshot.

**Comment by feilongsword** [comment]
> 
> 
> Please include the entire build output in text, not screenshot.

Thks for your kindly recommendation. I paste the build output.

**Comment by feilongsword** [comment]
> Please include the entire build output in text, not screenshot.

I can compile now. it seems like it's Github Desktop's fault. I cleared my working directory and download the lastest sourcecode as a zip file, and the issue got resolved.
