### ISSUE TITLE
Execute selection

### ISSUE THREAD

**Issue by buybackoff** [aelij/RoslynPad#39]
Since there is no other way to inspect contents of variables, interactive execution with ability to call .Dump() on any variable is a crucial missing feature for me now. Not sure if I would be able to add this myself, have just only started to dig into the project.

**Comment by aelij** [comment]
I'm not sure I understand this suggestion. You can use `Dump()` on any expression. What do you mean by "interactive execution"?

**Comment by buybackoff** [comment]
I want to evaluate selection of a file, not an entire file. Basic REPL
functionality, Selection + Alt + Enter like in C#/F# interactive. Dump()
was just a use case.

**Comment by aelij** [comment]
Oh, now I get it. This should be very simple to implement.

**Comment by buybackoff** [comment]
Also, why you do not use [Scripting API](https://github.com/dotnet/roslyn/wiki/Scripting-API-Samples) directly and do almost the same work in custom code? It looks like everything could be done with it. Especially *execution from a previous state* sample is relevant for REPL.

**Comment by aelij** [comment]
I originally used the Scripting API, but currently it doesn't emit PDBs, which means that when you get an exception, you have no way of knowing which script line caused it (see #28). I opened an issue in the  Roslyn repo, but they haven't gotten around to it yet.

I don't use most of the features of the scripting API (passing variables, continuations, etc.) So the code I had to write to execute scripts is very small (the scripting feature itself is built into the compiler, and the scripting API is just a small wrapper over it.)

Also, in the future, I will probably also allow the 'Regular' language mode (with a Main method) since scripts do not allow you to define namespaces and classes with extension methods, and if you have existing code that you just want to paste in and test, it may not work in RP.

**Comment by buybackoff** [comment]
Thanks for explanation! Sounds cool! If the state update could be done
manually then your solution is even better.

**Comment by aelij** [comment]
It's also important to note that RoslynPad is **not** REPL.

**Comment by aelij** [comment]
You may

**Comment by aelij** [comment]
You may also want to take a look at Xamarin's [Workbooks](https://developer.xamarin.com/guides/cross-platform/workbooks/).

**Comment by buybackoff** [comment]
Roslyn version 2.3 now supports debugging info: https://github.com/dotnet/roslyn/pull/16489, this projects updates easily to 2.3 with only single line requiring a change to build.

I looked into the Roslyn source internals and it is quite easy to implement REPL-like behavior either with the built-in Scripting API or with the current RoslynPad logic. As you said, RoslynPad does the same thing but with some changes. Actually, the recent compilation options change (optimization level, unsafe, overflow settings) is still missing from scripting API.

Could you please update on your plans with selection execution/REPL? It's very useful thing and I will be able to implement it myself later, but hope to see this feature in the upstream eventually. The easiest solution is just to adapt methods `RunFromAsync/ContinueFromAsync` from Roslyn without changing any existing API.

**Comment by aelij** [comment]
Execute selection and REPL are two completely different things. As I said before, I don't see RoslynPad supporting REPL at the moment. It's just not compatible with the current form of editing a complete code document IMO.

Supporting selection execution is easy, but if you select a different code segment that relies on variables or types from the previous one, it'll fail (try it in the other *Pad ;).

I don't mind adding some sort of API that would allow you to use REPL in your embedded version of RP though.

**Comment by buybackoff** [comment]
Actually, I completely switched to Roslyn scripting API for execution. I have even [rebuilt and resigned](https://github.com/buybackoff/roslyn/commits/2.3_resign) Roslyn to make some subtle changes. And executing selection with Roslyn API is supported out of the box (`scriptState.ContinueWith`). The coolest feature of RoslynPad is editing experience, which is practically independent of execution.

BTW, one of the reason I resigned the upstream was a comment somewhere in their issues that they will remove public key for tests or something like this. Resigning and rebuilding locally was very simple, so your approach of depending on internals is future-proof.

**Comment by buybackoff** [comment]
I now have my own "the other *Pad" based on this *Pad, with blackjack and REPL ;) I could share code but it is really just direct use of the scripting API. Your editing design time experience is great and is not related to execution, thanks for that again! Will be in sync with upstream on this part.
