### ISSUE TITLE
Nullable type setting from Build.Props not working?

### ISSUE THREAD

**Issue by jacobrienstra** [aelij/RoslynPad#391]
Hi! I'm not sure if this is an actual bug or if I somehow screwed up my VS settings;

When I tried to build from a clean repo, I got error CS8601 Possible null reference assignment on the few instances of `= default`
I found this: [https://stackoverflow.com/questions/66973999/how-to-get-rid-of-compilation-error-cs8601-possible-null-reference-assignement](https://stackoverflow.com/questions/66973999/how-to-get-rid-of-compilation-error-cs8601-possible-null-reference-assignement) and got around it by using `default!` 

I think the Directory.Build.Props <nullable> setting is supposed to prevent this but for whatever reason, that wasn't being used when I built from VS 2019

Any idea why this might be? Is this a problem with my setup? Or a quirk of how VS code handles those build props?

**Comment by aelij** [comment]
Roslyn just gets better at detecting null use cases. I just haven't built the project in a while. Will fix next push :)
