### ISSUE TITLE
Dark Theme, New Release and Cross-Platform?

### ISSUE THREAD

**Issue by RealAquilus** [aelij/RoslynPad#393]
I know there are some other issues open about Dark Mode, has been this implemented?
Also the last official release is a bit old when a new one will come out and since RoslynPad is built on Avalonia can it run on Linux and MacOS too?

Another (and last) question, can some GUI program be made with RoslynPad? I didn't find a way to use WinForm or WPF, or Avalonia (and other things like imgui.net ecc)
Thanks, and love for RoslynPad!

**Comment by aelij** [comment]
If you know there are issues, why open a new one? :)

And please review the README for your other questions.
