### ISSUE TITLE
Using Console and System.Windows.Media.Media3D in RoslynPad

### ISSUE THREAD

**Issue by pcarret** [aelij/RoslynPad#395]
Hello,

I am trying to use RoslynPad for the very first time and I cant get rid of compilation error

CS0433: The type 'Console' exists in both 'System.Console, Version=4.1.2.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' and 'mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'

**To Reproduce**
Use joined csx 

**Expected behavior**

**Version**
- OS: Win10
[Media3d.zip](https://github.com/aelij/RoslynPad/files/6718211/Media3d.zip)

- Build (or commit ID if built from source):
- RoslynPad 15.1
-

**Comment by aelij** [comment]
Use `#r "framework:Microsoft.WindowsDesktop.App"` (or `desktopapp` snippet) instead of directly referencing `PresentationCore`
