### ISSUE TITLE
Can't use assemblies using value tuples in .NET Framework x64

### ISSUE THREAD

**Issue by gfody** [aelij/RoslynPad#398]
select `.NET Framework x64` and something like:

```
#r "path/to/some_assembly_with_ref_to_system_valuetuple.dll"

var x = (3, 4);
```

..red squiggles appear underneath `(3, 4)` with message:

```
Predefined Type 'System.ValueTuple`2' is declared in multiple referenced assemblies:
 'mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089' and
 'System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e'
```

the assembly I'm referencing targets .NET Framework 4.7.2 and has a nuget package reference to System.ValueTuple 4.5.0

if I remove the referenced assembly the red squiggles go away, if I target .NET Core the squiggles go away (but then I get other problems).  is there any way to get this working?

RoslynPad v15.1
- OS: Windows 10 Version 21H1 (OS Build 19043.1110)
- Build (or commit ID if built from source): I'm using the windows app store build

**Comment by aelij** [comment]
Hey, can you please try this scenario with the version in master? I think it's fixed.

**Comment by gfody** [comment]
this is working now thanks!

I got a crash in this build that I can't repro in 15.1:  if I highlight a substring in the referenced assembly's path and overwrite it (I was highlighting "net472" and changing it to "net48" - it crashes on FileSystemCompletionHelper.cs, line 43 (it seems to crash as soon as I change the path anywhere in the middle - if I backspace from the right it's fine)

**Comment by gfody** [comment]
so even though it builds and runs now, there are a number of compiler warnings:
![CS1685](https://user-images.githubusercontent.com/1146032/128612234-c81f5793-b3c3-4db3-9cc7-58a8ac522bd6.png)
..and I found [this thread](https://stackoverflow.com/a/6518336) where they suggest using this line to flush out the conflict:
```
System.Runtime.CompilerServices.ExtensionAttribute x = null;
```
..if I paste that in I get this:

```
CS0433: The type 'ExtensionAttribute' exists in both 'System.Private.CoreLib, Version=5.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e' and 'mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'
```
this only happens if I'm referencing an assembly and only if I choose .NET Framework x64
