### ISSUE TITLE
#load command

### ISSUE THREAD

**Issue by Mungo64** [aelij/RoslynPad#40]
Is there a reason why the #load command in the csx source  leads to 'source code references are not allowed'  error.
Would it be possible to add that functionality as it is baiscally available in roslyn scripting ?

**Comment by aelij** [comment]
I'll look into it. I'm not sure how completion would behave in such cases.

Making `#load` work should be simple enough - just need to specify a `SourceReferenceResolver`.

**Comment by Mungo64** [comment]
Thanks:
Just look here: There is one which allows local and remote (http) sources.
https://github.com/filipw/Roslyn.Resolvers.Demo

**Comment by aelij** [comment]
There's a built-in resolver in Roslyn. Do you think it would be useful to allow HTTP sources as well?

**Comment by Mungo64** [comment]
I use csx-scripts to process inputdata from the globaldata object which i can access in a csx-script, when i host it myself. This actually works in a rest webservice, where i can post data to the service and call the script. I could use the #load command to simulate the input data in the editor, because there i have no configurable global object, which i can access. if the editor could load the file from my service (via http), i could dynamically create this data and the editor could really test my script with original input data. Of course i could edit another file and specify the input data by hand, this would be good enough, but i think it would be no big effort to make the #load command more universal...

**Comment by Mungo64** [comment]
pressed the wrong button.... so i reopen it....

**Comment by aelij** [comment]
I've added the default resolver, so local references should work now. I'll consider the remote one for a future version.
