### ISSUE TITLE
Latest version of Avalonia support

### ISSUE THREAD

**Issue by rusensinan** [aelij/RoslynPad#404]
The current packages from NUGET with the latest version of RoslynPad does not work with the latest version of Avalonia.

Would be great if we can make it RoslyPad compatible with the new Avalonia version.

PS: I would like to contribute the project but momentarily neither I have time or sufficient experience with the RoslynPad development pipeline.

**Comment by aelij** [comment]
`master` has already been updated with latest Avalonia. Will publish NuGet with the next release.
