### ISSUE TITLE
Roslyn 2.0.0-beta5

### ISSUE THREAD

**Issue by xen2** [aelij/RoslynPad#44]
Roslyn 2.0.0-beta5 has just been released on NuGet.

I have attempted an update (that you could cherry-pick as a base):
https://github.com/SiliconStudio/RoslynPad/tree/roslyn_2.0.0-beta5

Note: I couldn't get `System.IO.Compression.FileSystem` to work with latest IO.Compression 4.1.0, so that still need to be fixed (for the call to `ExtractToDirectory`)

**Comment by aelij** [comment]
Oh, I'm already on it :) I'm the one who requested they put it on NuGet. Thanks though.
