### ISSUE TITLE
Graceful cancellation

### ISSUE THREAD

**Issue by buybackoff** [aelij/RoslynPad#45]
Currently the host is killed with `Process.Kill` without any chance for a cleanup. I haven't found a way to pass a cancellation token inside a script. I rewrote Execution host to run in-process - each script in a new thread - and use Thread.Abort, which guarantees that a critical section inside `finally` is executed. The same could be done with a remote host - it should start a thread and support a command to abort it.

Ideally, we should provide a `CancellationToken` that should be available in a script as a [global variable](https://github.com/dotnet/roslyn/wiki/Scripting-API-Samples#parameter), e.g. `CANCELLATION_TOKEN`. Then after a certain timeout we should show a message asking if we want to forcefully abort execution. `Process.Kill` should not be used at all and after Thread.Abort a host process should stop normally. `IService.ExecuteAsync` could accept a token and all this termination logic could be just hidden in implementation.

The code below should print two lines from `catch` and `finally` on abort:

```
using System.Threading.Tasks;
using System.Threading;
var cts = new CancellationTokenSource();
var token = cts.Token;
try
{
    var t = Task.Run(() =>
     {
         try
         {
             var c = 0L;
             while (!token.IsCancellationRequested)
             {
                 c++;
                 if (c % 100000000 == 0)
                 {
                     Console.WriteLine(c);
                 }
             }
         }
         catch (Exception e)
         {
             Console.WriteLine(e.Message);
         }
     }, token);

    Thread.Sleep(50000);
    cts.Cancel();
}
catch (ThreadAbortException ex)
{
    Console.WriteLine("Thread is aborted");
    cts.Cancel();
}
finally
{
    Console.WriteLine("Finished");
}

```

It will also be useful to somehow (custom thread pool/scheduler) terminate Tasks started from a script, but at least it is the user to blame for writing code without cancellations, and tasks could be cancelled from `catch/finally` blocks as above.

**Comment by aelij** [comment]
Hi Victor. I'm not sure I like this idea. Relying on thread-aborts is not a safe way to complete execution. Even in your example above, there's no guarantee that the task would finish when you call `Cancel`. The process may continue running, and would have to be killed anyhow.

I can see two solutions for this scenario:
* Provide a way to get input from the user (e.g. `Console.ReadKey()`) which would execute code to gracefully cancel (#18).
* Provide an API (e.g. `RoslynPadRuntime.CancellationToken`).

WDYT?

**Comment by aelij** [comment]
(In the API case, there would be an additional button on the toolbar, "Stop". Recycling/killing the process would remain as is.)

**Comment by buybackoff** [comment]
CancellationToken in the best solution, if it possible to pass it per script, not one globally

**Comment by aelij** [comment]
Could you explain why non-global is important? I didn't understand that point in #48 either. In RP there's a process per tab, and each process runs only a single instance of the script concurrently.

**Comment by buybackoff** [comment]
because I run RP scripts in a shared host process, not in a separate runner
process

**Comment by aelij** [comment]
You mean you run them outside of RP?

**Comment by buybackoff** [comment]
Yes, I slightly modified the WPF project and run its main window from another process. All these issues are basically about passing globals, like Roslyn scripting API supports, the UI thing is secondary.

**Comment by buybackoff** [comment]
Yes, I slightly modified the WPF project and run its main window from
another process. All these issues are basically about passing globals, like
Roslyn scripting API supports, the UI thing is secondary.

**Comment by aelij** [comment]
I'm deferring this right now. I will add an API to allow you to pass in a globals class; that should help all of your use cases.
