### ISSUE TITLE
MetadataResolver parameter is missing

### ISSUE THREAD

**Issue by buybackoff** [aelij/RoslynPad#47]
On this [line](https://github.com/aelij/RoslynPad/blob/master/src/RoslynPad.Hosting/ExecutionHost.cs#L564) options.MetadataResolver should be added, otherwise NuGet does't work. That happened in [this](https://github.com/aelij/RoslynPad/commit/2555edb81f5bd255fa49ef88eaa986462b94fea0#diff-6d2fee3aa2b185343d4e6e8f138f28b5R564) commit and is also present in 0.10 distribution.

**Comment by aelij** [comment]
Sigh :) Thanks for reporting this. I've issued a patch.
