### ISSUE TITLE
Pass global variables

### ISSUE THREAD

**Issue by buybackoff** [aelij/RoslynPad#48]
Cannot find a way how to pass global variables to a script. Same issue as I mentioned in #45 about CancellationToken, but could be useful in general for other cases. Compilation accepts type of globals [here](https://github.com/aelij/RoslynPad/blob/master/src/RoslynPad.Roslyn/Scripting/ScriptRunner.cs#L254), but cannot pass an actual value and access it from script.
After looking into Roslyn [Scripting API](https://github.com/dotnet/roslyn/wiki/Scripting-API-Samples#parameter), tried to pass an instance of Globals as `object[0]` to the entry point and access Foo from script:

```
public class Globals
{
    public string Foo { get; set; }
}
```

When I run host in-process, long-running scripts print output to all running scripts, because they channel the output via static `ObjectExtensions.Dump`. With a global variable we could provide dump channel per a script and use only `Dump()` instead of `Console.Write` (which is redirected to a custom TextWriter globally in AppDomain) to avoid printing output in all running scripts.

**Comment by aelij** [comment]
Hi Victor, I'm not sure I quite understand the scenario. Since RP only runs a single script in a host process at a time, there's no issue with `Dump` being globally routed.

Where would you provide the instance of the globals in RP?

**Comment by buybackoff** [comment]
Roslyn 2.3 works great with its scripting API for execution. Couldn't find a way to pass globals to RP's manual compiler.

**Comment by quasar-pankaj** [comment]
This scenario seems to be what I am currently trying to do. I am working on an application that uses RoslynPad to write scripts. In the application I have some objects that I would like to pass to the RP as globals. Using https://github.com/aelij/RoslynPad/issues/129 I was able to get my custom classes to show up in the editor. But how can I pass global objects to the editor?

**Comment by aelij** [comment]
@quasar-pankaj please see [my answer on SO](https://stackoverflow.com/a/47397511).

**Comment by Panuon** [comment]
> @ quasar-pankaj请[在SO上](https://stackoverflow.com/a/47397511)查看[我的答案](https://stackoverflow.com/a/47397511)。

This can only be used for known types. 
What if it's a dynamically generated variable?
