### ISSUE TITLE
Variables in lambdas are forcefully completed after space

### ISSUE THREAD

**Issue by buybackoff** [aelij/RoslynPad#49]
When using with LINQ for parsing data it is quite annoying when every time I have to press escape when variable length is more than 1, e.g. in `.Aggregate("", (acc, st) => acc + "[ " + st + " ] ")` `acc` is replaced with `AccessViolationException`, `st` with `string`. Meaningful names are convenient for LINQ, and this forced autocompletion is annoying. Haven't learned the internals enough to fix it myself.

**Comment by aelij** [comment]
Thanks, it should be relatively easy to fix.
