### ISSUE TITLE
Create installer

### ISSUE THREAD

**Issue by ohadschn** [aelij/RoslynPad#52]
Personally I like having all installed apps managed via the add/remove programs and not in some util folder I unzip stuff into. It's also better for multi-user environments.

More importantly, Cortana only finds installed apps. This means that in Windows 10,  you won't be able to find it if you type `RoslynPad` into the start menu search (even if you have a shortcut on the desktop that's pinned to the Start menu).

**Comment by aelij** [comment]
I'm thinking about releasing RP as a Centennial app. That way it could be installed and updated via the store.

**Comment by aelij** [comment]
RP has been released to the Microsoft Store. Closing
