### ISSUE TITLE
Source won't build on clone

### ISSUE THREAD

**Issue by W1zb1t** [aelij/RoslynPad#54]
Whether I download or clone I have the same issue that the code will not compile due to failures in restoring the nuget packages. The failure seems to trace to a circular reference claim on the reflection package:
Error occurred while restoring NuGet packages: Circular dependency references not supported. Package 'RoslynPad.Hosting'.

**Comment by W1zb1t** [comment]
Just as a note I am using VS2015

**Comment by aelij** [comment]
Thanks for reporting this, however I wasn't able to repro this on two different machines. Perhaps there's something wrong with your local setup or NuGet cache?

**Comment by modulexcite** [comment]
I agree with @aelij as I can build it from source on different machines and continue to do so.

**Comment by W1zb1t** [comment]
Will restest when I get a chance. Will open a new case and ref back to this if I still have the same issue and can give better reproduction instructions.

**Comment by aelij** [comment]
Please post to this issue, no need for a new one.
