### ISSUE TITLE
Expose editor as a reusable control (on NuGet)

### ISSUE THREAD

**Issue by Nfactor26** [aelij/RoslynPad#55]
Hi ,

I have been working on an application where i need to have a code editor with intellisense for C#.
RoslynPad does exactly the same and in fact more . However, it is a standalone application.
It would be really nice to have it as a custom control which can be plugged in other wpf application.
Please consider adding this feature if possible.

Regards,
Nish26

**Comment by aelij** [comment]
Thanks for the suggestion. Some work has already been done in #43. But it will take me a while to complete this feature.

**Comment by StingyJack** [comment]
Having at least the line numbering on the left would also nice for other tool windows.

**Comment by aelij** [comment]
The following packages have been published:

* `RoslynPad.Roslyn`: Includes all exposed Roslyn services
* `RoslynPad.Roslyn.Windows`: WPF UI elements for `RoslynPad.Roslyn`
* `RoslynPad.Roslyn.Avalonia`: Avalonia UI elements for `RoslynPad.Roslyn`
* `RoslynPad.Editor.Windows`: WPF (AvalonEdit) implementation of `RoslynCodeEditor` and services
* `RoslynPad.Editor.Avalonia`: Avalonia (AvaloniaEdit) implementation of `RoslynCodeEditor` and services

`RoslynPad.Roslyn*` package versions will correspond to Roslyn's.

There's also a [sample](https://github.com/aelij/RoslynPad/tree/master/samples) that shows how to implement REPL using `RoslynCodeEditor`.

**Comment by jogibear9988** [comment]
@aelij is it possible to update the nuget packages?

**Comment by aelij** [comment]
I will update them as soon as the new version is ready.
