### ISSUE TITLE
Version 20 can't work on MacBookAir(M2, Sequoia 15.0) nor Windows 11 Enterprise(23H2, 22631.4169)

### ISSUE THREAD

**Issue by liyanjie2048** [aelij/RoslynPad#552]
Version 20 can't work on MacBookAir(M2, Sequoia 15.0) nor Windows 11 Enterprise(23H2, 22631.4169).
MacBook: alert broken and move to trash bin.
Windows 11: alert nothing, couldn't show the window.

**Comment by aelij** [comment]
Thanks for reporting this!

* Windows - I uploaded a new version (missing Themes directory in zip)
* macOS - Have you noticed the new instructions in the release notes?
  > In macOS Sequoia you must go to Settings > Privacy & Security to approve non-notarized apps after the first run (more information)
