### ISSUE TITLE
Improve #r performance

### ISSUE THREAD

**Issue by ohadschn** [aelij/RoslynPad#56]
Pressing `"` after `#r` takes a while to complete. I'm not sure why, but perhaps caching that list might improve performance. 

Also, it would be nice if the `"` would be auto-added after typing in `#r `. I keep forgetting the quotes are required and it takes me a moment to figure out why auto completion doesn't kick in.

**Comment by aelij** [comment]
The perf is not that great in the VS interactive window either. This code path accesses the GAC, so I'm not sure what we can do (perhaps some caching?). There's some IO going on on the UI thread. I tried making it async but the completion didn't work well...

**Comment by k59319** [comment]
It was unexpected to see that the program freezes at this point. The progress bar indicating that assemblies are loading from GAC would be helpful.
