### ISSUE TITLE
Highlight matching parenthesis

### ISSUE THREAD

**Issue by ohadschn** [aelij/RoslynPad#57]
A small but very convenient feature is the one that highlights the matching parenthesis (`()`,`[]`,`{}`,`<>`) for the one currently on the cursor. This is especially useful for multi-line and multi-parenthesis expressions.

**Comment by aholmes** [comment]
@aelij I'd like to tackle this. Do you have any specific PR requirements?

**Comment by aelij** [comment]
Thanks, @aholmes!

* All the changes should be in the `RoslynPad.Editor.Windows` assembly
* Store the highlight color in `ClassificationHighlightColors`
* I suggest you take a look at SharpDevelop, they've probably implemented this for their AvalonEdit-based editor

**Comment by aholmes** [comment]
@aelij Great! I have everything set up, so I'll get to this as soon as I can, life permitting.

**Comment by aelij** [comment]
Also implemented <kbd>Ctrl</kbd>+<kbd>]</kbd> for navigating between braces.

**Comment by aholmes** [comment]
Awesome! 👌 I didn't realize so much code was involved - no wonder I had a hard time.

**Comment by aelij** [comment]
Most of it was copied from Roslyn :)
