### ISSUE TITLE
Compile Script to exe

### ISSUE THREAD

**Issue by modulexcite** [aelij/RoslynPad#58]
Is it possible to provide an option to compile a script to an assembly (exe/dll) using the command line compilers available in MSBuild?

**Comment by aelij** [comment]
This feature is included in 0.10. It doesn't use MSBuild though, just Roslyn.

**Comment by modulexcite** [comment]
That works too, thanks.

**Comment by modulexcite** [comment]
I only see the option for compiling it to an assembly (dll), don't see an option for an executable (exe). Am I missing something or was that intentional?

**Comment by aelij** [comment]
Roslyn emits a Task entry point for scripts. I'm not sure you can compile them to executables... but I'll try.

**Comment by modulexcite** [comment]
Awesome, thanks for taking the time to investigate it further.
Have a great long weekend.
