### ISSUE TITLE
Syntax Highlighting flickering

### ISSUE THREAD

**Issue by xen2** [aelij/RoslynPad#60]
If code is big enough, text will start to flicker on each character change -- everything become black or white for an instant then highlighted again (especially for the part before the text cursor).

I was thinking it was a syntax highlight caching issue (i.e. we can use previous highlighting state until we compute new one), but might be bigger than this.

Note: I might investigate it again soon -- but still opened an issue in the meantime so that it is part of the issue tracker.

**Comment by aelij** [comment]
How big was the code when this happened? Can you post a sample? I tried as many as 2000 lines and didn't see the flickering.
