### ISSUE TITLE
Allow for multiple nuget location

### ISSUE THREAD

**Issue by workabyte** [aelij/RoslynPad#61]
we have our own internal nuget server and it would be nice if there was an app setting at the least for pulling nuget packages from other locations.

**Comment by jsjodha** [comment]
For Time being you can use global Nuget.Config. add your sources to list "%AppData\Nuget\NuGet.Config%"

**Comment by aelij** [comment]
I've decided to close this as VS also uses the user's NuGet.config.

**Comment by Roemer** [comment]
But in VS you can also have a local nuget.config file in your project. I think it recursively gets all nuget.config files and merges them (starting from the current directory, going to the drive root and then adding the users one and then adding the global one).
