### ISSUE TITLE
Change tracking improvements

### ISSUE THREAD

**Issue by ohadschn** [aelij/RoslynPad#66]
It seems that once a file is saved, change tracking doesn't work.

1. Open a new tab.
2. Insert some text - notice the asterisk on the tab indicating the document was changed.
3. Delete the text - notice the asterisk disappear (as expected).
4. Add some more text and save the file.
5. Delete the text you added in step (4) and notice the asterisk is still there (even though the current text is exactly the same as it was on the last save).

On a related note, it would be nice to be able to save empty files (sometimes I want to give something a name before I even start coding).

**Comment by aelij** [comment]
Document change tracking never works this way. Try in Notepad++ and VS. It's not like Git tracking. If you modify the document in any way, it remains "dirty".

**Comment by aelij** [comment]
I'll leave this open for the "related note" request :)

**Comment by ohadschn** [comment]
My bad, step (5) should have said "delete the text you added in step (4) by pressing Ctrl+Z". In NPP that reverts the "dirty" indication. Though I admit it's a bit esoteric :)
