### ISSUE TITLE
#r auto-completion results in a duplicate namespace component (the first one)

### ISSUE THREAD

**Issue by ohadschn** [aelij/RoslynPad#67]
1. Type in `#r "System.N` 
2. Select `System.Net` from the auto-completion dropdown
3. Hit TAB or ENTER
4. It will get completed to `#r "System.System.Net` (notice the double `System` component).

BTW, it would be nice if auto-completion closed the quotes too :)

**Comment by aelij** [comment]
Evidently this bug also exists in C# Interactive window in VS. It's probably in the `ReferenceDirectiveCompletionProvider` I copied from Roslyn.

**Comment by LMLB** [comment]
It seems to me like it only uses the text after the last dot (instead of the quote) for the auto-completion.

**Comment by LMLB** [comment]
There's another edge case with the `#r` auto-completion, here are some examples:

- If I type `#r "System.Windows` and then type a period (`.`), I get `#r "System.Runtime.InteropServices.WindowsRuntime.`
- If I type `#r "Microsoft` and then type a period (`.`), I get `#r "Microsoft-Windows-HomeGroupDiagnostic.NetListMgr.Interop.`
