### ISSUE TITLE
Copy/cut/paste context menu

### ISSUE THREAD

**Issue by ohadschn** [aelij/RoslynPad#69]
It seems that nothing happens when right-clicking in most areas. There are a lot of possibilities here that could be inspired by editors such as Visual Studio, NPP, and LINQPad. The most basic one would be copy/cut/paste.

Having the ability to right-click rows in the result window would be nice too, with options such as "copy value" being IMHO more intuitive than the current copy button.

**Comment by aelij** [comment]
This is too general for one issue :) Let's break it down...

**Comment by aelij** [comment]
See #72
