### ISSUE TITLE
Nuget Packages

### ISSUE THREAD

**Issue by jogibear9988** [aelij/RoslynPad#73]
As you started to work on "Reusability", would it be possible to provide nuget packages?

**Comment by aelij** [comment]
I haven't worked on reusabilty at all :)

Which assembly do you think would be useful as a NuGet package in its current state? Perhaps just `RoslynPad.Roslyn`. Can you share what you're trying to build?

**Comment by jogibear9988** [comment]
I look tomorrow....

I've an Application, where I've a Script Editor inside. But you can only Edit a part of the Code, means I use 3 Text Editors, one for the fixed part, wher eis my class name, default usings, function name, one editor for the code the user can enter, and one for the footer (closing brakets and return value). I'd like the user can use CodeCompletition in the middle editor

**Comment by aelij** [comment]
Tracking this in #55
