### ISSUE TITLE
Read referenced assemblies without locking file

### ISSUE THREAD

**Issue by buybackoff** [aelij/RoslynPad#78]
Is it possible to avoid locking assembly files while scripts are running and without restarting host process every time?

```
#r "...\MyAssembly.dll"
using System.Threading;
using MyAssembly.MyNamespace;
var x = MyClass.SomeStaticValue;
x.Dump();
Thread.Sleep(100000)
```

I want to be able to recompile my dll after starting a script, but now the file is locked for writing until I restart a host process.

It is very convenient to use RoslynPad for live testing of assemblies, i.e. I write MyAssembly in VS, then quickly change it or write some functionality in scripts and then put is back to MyAssembly.

**Comment by aelij** [comment]
I believe this can be solved by shadow-copying the assemblies. Roslyn has support for that.
