### ISSUE TITLE
"using" snippet is wrong for namespaces

### ISSUE THREAD

**Issue by buybackoff** [aelij/RoslynPad#79]
When in namespaces section, typing `using-> Tab` (any part of the word before the space) expands to this:

![image](https://cloud.githubusercontent.com/assets/489852/24020751/a4d110fa-0aae-11e7-9f96-c3fde9576d49.png)

In VS, a single `u` expands to two options "using/unsafe", and two symbols `us` are enough. Not a big deal, but muscle memory often makes me use `us->Tab` subconsciously.

**Comment by aelij** [comment]
In regular C#, using directives can only appear at the top of the file or right below a namespace. So Roslyn can easily distinguish between the using directive and the using statement.

This is not the case in the script variant of C#, so I don't think I can solve this. RoslynPad only completes snippets when hitting <kbd>Tab</kbd>, but you can use <kbd>Enter</kbd> to complete as well.

**Comment by buybackoff** [comment]
Enter is OK, will learn to always use it or to just avoid hitting Tab. It is just the same minor usability issue like single-letter variables in lambdas that you have fixed recently (and which was much more frequent).
