### ISSUE TITLE
Dump of Hierarchy produces confusing results

### ISSUE THREAD

**Issue by theit8514** [aelij/RoslynPad#80]
I'm working on debugging a Hierarchy generator using RoslynPad and have been running into a limitation on the Dump() command.

When I Dump an object that contains multiple levels of data, I seem to only be able to drill down into 4 layers.

![image](https://cloud.githubusercontent.com/assets/1175401/24420420/d4d82fc0-13c0-11e7-963f-cf725b0813cc.png)

After the 4th layer, there is a Children node, but there is no drilldown for it and no indication that there are further values. If I Dump an object deeper into the tree, I can finally see those values.

![image](https://cloud.githubusercontent.com/assets/1175401/24420481/00190420-13c1-11e7-9464-734595a21fe0.png)

If this is not a bug with the Dump command and is working as intended, can there be an indicator that there are values but the software can't drill down?

**Comment by aelij** [comment]
This behavior is by design. Allowing an unlimited depth is impractical because the result is calculated at the moment of the dump, not when you expand (I wanted snapshot semantics). I may add a way to configure the depth (e.g. in a Dump method argument).

Adding an indicator is a good idea.

**Comment by theit8514** [comment]
Thanks for the quick reply. I completely understand on the unlimited depth issue.

To clarify the identifier a little bit, right now it's difficult to determine which of the two is being shown:
* 'this is an empty list' (Second image, Name file3.txt)
* 'this is a list with items which can't be drilled down' (First image, Name Folder4)

They both appear as the type name instead of the collection description `<enumerable Count: 2>`.

**Comment by aelij** [comment]
I've added an enumeration count even if it doesn't expand. Additionally, you can now control the depth of dumped graphs, e.g. `x.Dump(maxDepth: 10)`.
