### ISSUE TITLE
RoslynPad fails to get reference assemblies path / no System.xml

### ISSUE THREAD

**Issue by fabianoliver** [aelij/RoslynPad#81]
Hi,

RoslynPad displayed/throw an Exception for me immediately after starting, and wouldn't open any documents. I think the issue was that it failed to get a path the reference assemblies; in my case, it discovered the folder
C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.6.2
But while System.dll is present, System.xml isn't on my machine,.

Not sure if there was a specific reason for looking for a System.xml as well, but I've removed the check for this file in particular, meaning it does pick up this folder, thereby also fixing the exceptions I was facing.

in RoslynHost.cs, lines 229 and following, I've replaced the code with

                var directory = Directory.EnumerateDirectories(path)
                    .Select(x => new {path = x, version = GetFxVersionFromPath(x)})
                    .OrderByDescending(x => x.version)
                    .FirstOrDefault(x => File.Exists(Path.Combine(x.path, "System.dll")) /*&&
                                         File.Exists(Path.Combine(x.path, "System.xml"))*/);

**Comment by aelij** [comment]
RoslynPad looks for the latest reference assembly directory that contains both `System.dll` and `System.xml` so it could provide documentation with completion/signature help/quick info.

You case is a bit curious. Can you please check if you have a `System.xml` file anywhere in this directory?
```
C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework
```
On my machine, it uses `v4.6.1`.

I'll change the code so `System.xml` is optional.

**Comment by fabianoliver** [comment]
Hi,

ony my machine, I have

A) folders "v3.5", "v4.0", "v4.5", "v4.5.1", "v4.5.2", "v4.6", "v4.6.1" and "v.4.6.2", and
B) folder "v4.X"

in C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework.
The ones under A) all only contain the DLLs, no (relevant) XML files.
The folder B) (v4.X) has a subfolder "de", which contains all the xml files including System.xml, and nothing else (i.e. no DLLs).

**Comment by aelij** [comment]
Interesting. Must be the different locale. I'll try to access these XML docs as well.
