### ISSUE TITLE
How is RoslynPad.Roslyn accessing internal members

### ISSUE THREAD

**Issue by rufio620** [aelij/RoslynPad#83]
I have been been studying this code to see how it works and it appears that the RoslyPad.Roslyn project is somehow accessing internal members of the Microsoft Roslyn nuget packages. E.g. SignatureHelpItem.cs references Microsoft.CodeAnalysis.SignatureHelp.SignatureHelpItem which appears to be internal. Can you please shed some light on how you are able to access these members? Thanks.

P.S. This is a really cool project!

**Comment by aelij** [comment]
I'm using LOTS of internal stuff from Roslyn. It would've been a lot harder to create RoslynPad without them.

The trick is to name the assembly to one of Roslyn's `InternalsVisibleTo` test assemblies, whose .snk (with private keys) is public in their repo. So `RoslynPad.Roslyn` is actually named `Roslyn.Services.Editor.UnitTests`. :)

You can read more in this blog post: https://arbel.net/2016/03/27/simple-access-to-roslyns-internals/

Even if you don't have a private .snk, you can extract the **public** key from an assembly (using `sn.exe`) and then use [public signing](https://github.com/dotnet/corefx/blob/master/Documentation/project-docs/public-signing.md). Note this won't work if you want to GAC the assembly or use it in a partial trust context.
