### ISSUE TITLE
RoslynPad crashes when combining const and var

### ISSUE THREAD

**Issue by fdub** [aelij/RoslynPad#84]
When I tried to introduce a constant to my snippet, in the line before some variable assignment (using var), RoslynPad was crashing. I tried some variations and found out an easy way to reproduce the error: 

If the editor contains this text
`const var i=`
with the cursor at the end of the line and you type some letter (e.g. _e_), RoslynPad crashes.

**Comment by aelij** [comment]
Can you please check for a stack trace in the Windows Event Viewer, Application log? There should be a ".NET Runtime" event.

**Comment by fdub** [comment]
Eventvwr doesn't show a stack trace and even running the source doesn't show any after the exception. Only that it's a StackOverflowException. 

After a short attempt to step through the code I get stuck at RoslynCodeEditorCompletionProvider line 60, the async call to completionService.GetCompletionsAsync, after which this StackOverflowException without any stack trace is shown...

**Comment by aelij** [comment]
Apparently this is a bug in Roslyn - see https://github.com/dotnet/roslyn/issues/17779
I'm closing this issue, as this bug can be tracked there.
