### ISSUE TITLE
Could not load file or assembly 'System.IO.FileSystem, Version=4.0.1.0

### ISSUE THREAD

**Issue by SlowLogicBoy** [aelij/RoslynPad#90]
Hey, just downloaded RoslynPad 12 and I got this, when tried to run script:

`Could not load file or assembly 'System.IO.FileSystem, Version=4.0.1.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)`

`Microsoft.CodeAnalysis.Scripting.dll` wants to load older version of `System.IO.FileSystem`, even though 
```
    <assemblyBinding xmlns="urn:schemas-microsoft-com:asm.v1">
      <dependentAssembly>
        <assemblyIdentity name="System.IO.FileSystem" publicKeyToken="b03f5f7f11d50a3a" culture="neutral" />
        <bindingRedirect oldVersion="0.0.0.0-4.0.2.0" newVersion="4.0.2.0" />
      </dependentAssembly>
    </assemblyBinding>
```

exists in RoslynPad.exe.config

**Comment by SlowLogicBoy** [comment]
Fixed it by copying `RoslynPad.exe.config`
And renaming it to `RoslynPad.Host32.exe.config` and `RoslynPad.Host64.exe.config`

**Comment by aelij** [comment]
Thanks for reporting this! I've updated the zip.
