### ISSUE TITLE
Expose CSharpCompilationOptions to ScriptRunner and ExecutionHost constructors

### ISSUE THREAD

**Issue by buybackoff** [aelij/RoslynPad#91]
Allow to specify some CSharpCompilationOptions from ExecutionHost and ScriptRunner constructor. E.g. I need `OptimizationLevel.Release` and prefer `checkOverflow: true` by default which differ from the current settings. I could hard-code this for my needs since I cannot see a reason why not to use them by default, but do not want to maintain a local copy of the `RoslynPad.Roslyn` project.

Or you may consider changing the current settings at least from `Debug` to `Release` (you have TODOs [there](https://github.com/aelij/RoslynPad/blob/master/src/RoslynPad.Roslyn/Scripting/ScriptRunner.cs#L253), probably the intent was to make all the three ones editable?).

**Comment by aelij** [comment]
The TODOs have been copied from the Roslyn codebase :) But I'm open to allowing changing those settings.
