### ISSUE TITLE
Auto save problem

### ISSUE THREAD

**Issue by SlowLogicBoy** [aelij/RoslynPad#99]
I save document manually, close roslynpad and open again, it opens autosave which is outdated (a lot). Accidentally saving opened autosave file overrides my current file. Burned quite badly just now :)

This is a huge problem for those who has a habbit of ctrl+s every change.

**Comment by aelij** [comment]
Yikes, sorry :)

**Comment by SlowLogicBoy** [comment]
No problem, I knew this problem existed quite some time, just this time I didn't check so I though I will file this one :)
